### ISSUE TITLE
Fix android minimum sdk and remove example folder from pub.dev

### ISSUE THREAD

**Issue by luis901101** [juliuscanute/qr_code_scanner#108]
The qr_code_scanner 0.0.13 currently published in pub.dev has two problems:

1. The Android minSdkVersion is set to 24... I think 19 will work too and will be more compatible (In fact this is already fixed in master branch)
2. The .resources folder is included in the pub.dev publication... I think this is not necessary in fact that increases up to 35 MB the plugin download which is a lot of data for a dependency which is around 100 KB. The .resources should be included in .gitignore only for pub.dev publishing purposes

So I think it would be great a simple fix/publish for this.

**Comment by dspicher** [comment]
- As you mentioned, `minSdkVersion` is already decreased on master and will be out with the next release, which should be soon.
- I just removed some unused `.gif` files from `.resources`, it is now only 4 MB.

**Comment by luis901101** [comment]
Ok thanks
