### ISSUE TITLE
Stop repeatedly triggering onQRViewCreated

### ISSUE THREAD

**Issue by mrmikezhang** [juliuscanute/qr_code_scanner#11]
Hi, 

First of all, thank you for the plugin. I have a few questions which I couldn't seem to find answers to, so I hope you can help shed some light on it.

1. How do I stop the scanner from triggering onQRViewCreated callback method after the first scan is received? It seems like it's running in a while loop and the onQRViewCreated is constantly being called, even though I am not scanning.

2. Is there a way to limit the amount of log messages? Right now it pretty much fill the whole screen in no time, and there's no way to stop it.

Thank you very much. Look forward to hearing from you.

**Comment by LeonDevLifeLog** [comment]
No. 1 not support for now. but you can do that from another way. eg. Use a result flag.

No. 2 problem due to some bug. It will be fixed. and only print log messages when camera open.

Answers base on Android.

**Comment by mrmikezhang** [comment]
Thank you for getting back to me and for the answers. 

1. I will try to see if I can get that to work.
2. Good to know, look forward to the next release, :)

Have a nice day

**Comment by nitneuq33** [comment]
Hello, i have the same observation about continious call of  onQRViewCreated. I'm neeby, I don't understand result flag. Currently I don't know how to stop _onQRViewCreated  when the Qrcode is found. If you have a little example. Thank you

**Comment by Contract16** [comment]
You can manually pause the camera (which will pause the scan) as such:
```
  void _onQRViewCreated(BuildContext context, QRViewController controller) {
    this.controller = controller;
    controller.scannedDataStream.listen((scanData) {
      controller.pauseCamera();  // Pause the camera
      setState(() {
        // Set some state
      });
    });
  }
```

If you don't want to show a paused camera view, you could set a bool such as `isScanning` to `false` and display the camera if `isScanning` is `true`, else display something else where the camera would be.

To resume camera scan you just need to do `controller?.resumeCamera();`

**Comment by enricobenedos** [comment]
I've the same problem on iOS! 
@Contract16 your code not solve the situation because in `_onQRViewCreated ` you are subscribing to an event. Even if you call `controller.pauseCamera()`, in the same moment a lot of events are generated.

**Comment by FerBueroTrebino** [comment]
For me the solution I've found was to create a bool firstDetection : 

```
  void _onQRViewCreated(QRViewController controller) {
    this.controller = controller;
    bool firstDetection = true;

    controller.scannedDataStream.listen((scanData) {
      if (firstDetection) {
        firstDetection = false;
        // Do something with scanData
      }
    });
  }

```

**Comment by gabucito** [comment]
If you don't mind using another library, you could try using throttleTime from the rxdart library.
Basically when it scans once it will wait whatever Duration you want before scanning another barcode.
I find this a better approach than pausing/resuming the camera.
```
void _onQRViewCreated(QRViewController controller) {
    this.controller = controller;
    this
        .controller
        .scannedDataStream
        .throttleTime(Duration(milliseconds: 1500)) // You add a throttleTime pipe to the stream
        .listen((barcode) {
      HapticFeedback.heavyImpact(); // to make it vibrate on scan
      print(barcode); // do something with the barcode
    });
  }
```

**Comment by juliansteenbakker** [comment]
I have tested this on both Android 10 and iOS 12 but found out that _onQRViewCreated only gets called one time. If you still encounter this problem, please mention which device & OS you are using.

**Comment by juliansteenbakker** [comment]
> I have tested this on both Android 10 and iOS 12 but found out that _onQRViewCreated only gets called one time. If you still encounter this problem, please mention which device & OS you are using.

I think i have mistaken you. _onQRViewCreated only gets called one time however the stream receives continues information from the scanner. The stream indeed get's called every time the scanner scans a QR code.

**Comment by juliansteenbakker** [comment]
If you only want to allow a single detection you can just stop the stream after the first detection by assigning a variable to the stream and calling `.cancel()` on the variable. 
```
  void _onQRViewCreated(QRViewController controller) {
    this.controller = controller;
    var scannedDataStream;
    scannedDataStream = controller.scannedDataStream.listen((scanData) {
      setState(() {
        result = scanData;
        controller.pauseCamera();
        scannedDataStream.cancel();
      });
    });
  }
```

**Comment by singhmitesh** [comment]
> If you don't mind using another library, you could try using throttleTime from the rxdart library.
> Basically when it scans once it will wait whatever Duration you want before scanning another barcode.
> I find this a better approach than pausing/resuming the camera.
> 
> ```
> void _onQRViewCreated(QRViewController controller) {
>     this.controller = controller;
>     this
>         .controller
>         .scannedDataStream
>         .throttleTime(Duration(milliseconds: 1500)) // You add a throttleTime pipe to the stream
>         .listen((barcode) {
>       HapticFeedback.heavyImpact(); // to make it vibrate on scan
>       print(barcode); // do something with the barcode
>     });
>   }
> ```

@gabucito thanks, it worked for me
