### ISSUE TITLE
iOS (Android not tested): PlatformQrView does not get disposed after closing widget

### ISSUE THREAD

**Issue by shinsenter** [juliuscanute/qr_code_scanner#113]
On iOS 14, the green dot which indicates the app is accessing phone's camera is still ON even I has closed the widget.

**Comment by cyrilOrderoo** [comment]
I have crashes on iOS devices only after the widget have been closed. it can happen at any time after the widget is closed( 2min, 5min, ...) the application completely crashes. Seen on iphone 11 and iphone 8 on iOS 13.5.0 but never happened on  iPhone SE on iOS 13.3.1.

**Comment by ljaniszewski** [comment]
I happen to have the same problem. Any solutions to this?

**Comment by dspicher** [comment]
@shinsenter @cyrilOrderoo @ljaniszewski can you please test whether #122 fixes your issue? I will merge this as soon as one of you confirms.

**Comment by sjoerd0301** [comment]
@dspicher It fixes hang ups when recreating the platform view

**Comment by Falynsky** [comment]
@dspicher I also checked this fix from #122, works well, could you merge this fix?
