### ISSUE TITLE
plugin minSdkVersion is 20

### ISSUE THREAD

**Issue by jawa0919** [juliuscanute/qr_code_scanner#116]
zxing can use  minSdkVersion 19
but Platform View minSdkVersion 20
https://docs.flutter.io/flutter/widgets/AndroidView-class.html

**Comment by worawutt** [comment]
If I use qr_code_scanner dependency by path like path: ../qr_code_scanner, I can use minSdkVersion 21. But If I use via pub, It's require minSdkVersion 24!! 
How I can use version 21 via pub?

**Comment by jawa0919** [comment]
> If I use qr_code_scanner dependency by path like path: ../qr_code_scanner, I can use minSdkVersion 21. But If I use via pub, It's require minSdkVersion 24!!
> How I can use version 21 via pub?

 can use git
Docs here: https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages

**Comment by juliansteenbakker** [comment]
Please see #123 for more information. Version 0.0.14 should work with SDK 20 and up. I'm working on a version with minSDK 19.
