### ISSUE TITLE
Doesnt scan a barcode in vertical orientation

### ISSUE THREAD

**Issue by dagba** [juliuscanute/qr_code_scanner#118]
Doesnt scan a barcode in vertical orientation

**Comment by worawutt** [comment]
Same with me. I test on pdf417.

**Comment by juliansteenbakker** [comment]
Please comment if you still have this issue on 0.1.0.

**Comment by kunit1** [comment]
I see this issue on 0.3.0
Should I open a new issue?

**Comment by Shubhankt1** [comment]
I faced a similar issue. In iPhone X (iOS 14.3), it doesn't scan the QR if the mobile is over z-axis in vertical orientation. But, if I make the device completely straight vertically, it quickly scans the QR.
Pl help.

**Comment by AlaaMarawi** [comment]
Same problem, sometimes pausing and resuming the scan solves the problem
