### ISSUE TITLE
Scanner obtains many false positives

### ISSUE THREAD

**Issue by frankvollebregt** [juliuscanute/qr_code_scanner#119]
I have reprogrammed the example app to store all unique codes in a set. When scanning a barcode (especially when slightly tilted or out of frame) it very frequently misinterprets the codes.

Is there a sensitivity setting or something similar to minimize these mistakes? Right now, the package (though very fast) does not provide me with the accuracy I would like to have.

Tested on a Xiaomi Mi A2 running Android 10 and a Samsung Tab S5e running Android 10.

Below a GIF showing the issue happening

![falsepositives](https://user-images.githubusercontent.com/23523399/89412504-81d2e580-d727-11ea-8eb1-316e96894a04.gif)

If there's a way to improve the accuracy, that would be great.

**Comment by lumpov** [comment]
the same issue

**Comment by Cayke** [comment]
Same here

**Comment by juliansteenbakker** [comment]
The accuracy is determined by the underlying framework we are using. Since both the android framework (zxing) and iOS framework (MTBarcodescanner) are in a maintenance only state I'm considering migrating to an other framework such as MLKit. See #176 for progress of this issue.
