### ISSUE TITLE
Turn flashlight on and off and Add ability to scan once instead of multiple times

### ISSUE THREAD

**Issue by shivamabhi** [juliuscanute/qr_code_scanner#12]

**Comment by juliuscanute** [comment]
@shivamabhi why not use a flag or move to another screen upon recognition?

@shivamabhi I'll add flashlight on and off soon.

**Comment by juliuscanute** [comment]
flash light support added, will document the correct usage. Incase you feel you need calling once, raise a separate issue for it.
