### ISSUE TITLE
Make QRViewController methods return Future<>

### ISSUE THREAD

**Issue by pedroafonsouza** [juliuscanute/qr_code_scanner#126]
![Screenshot from 2020-08-17 11-25-25](https://user-images.githubusercontent.com/26653120/90407498-fb01ff00-e07c-11ea-9688-859b4315b9ed.png)

By default from lib, the resume, pause, flipCamera and dispose methods return void. It would be interesting to return a Future <dynamic> as internal invocations do.

**Comment by dspicher** [comment]
Would it be useful even if they return `Future<void>`?

**Comment by pedroafonsouza** [comment]
@dspicher Certainly Future<dynamic> would be better. Because sometimes in my app i need await the flipCamera() or dispose() methods, so, would be a great improvement.

**Comment by pedroafonsouza** [comment]
@dspicher any update about that?

**Comment by juliansteenbakker** [comment]
I have released v0.3.0 which changed all methods to Futures.
