### ISSUE TITLE
Not opening scanner on iOS

### ISSUE THREAD

**Issue by jasnicaa** [juliuscanute/qr_code_scanner#127]
Hi, thanks for the library!

I am having problems with iPhone 11. After allowing usage of a camera scanner is not showing in the controller. Anything on this?

**Comment by pedroafonsouza** [comment]
@jasnicaa maybe if you ask the permission of camera before you build the QRView will work.
Ensure that camera permission is enabled before build QRView.

**Comment by jasnicaa** [comment]
it asks for the permission when I start scanner. I am not aware how it would be possible to ask for the permission earlier?

**Comment by pedroafonsouza** [comment]
In Android the camera permission handle works well. For iOS i dont build the QRView until camera permission is enabled (in my case). But, yes... that would be an awesome improvement.

**Comment by jasnicaa** [comment]
Well yeah ok I could try that but it would be a workaround. I would like to know why is not working.

**Comment by drandom3** [comment]
I also have this problem, I have the camera permission granted and confirmed a screen before the scanner screen and still get a permission error.

**Comment by AmirAshvins** [comment]
Same here. I am getting permitted to use the Camera but still get the permission error

**Comment by juliansteenbakker** [comment]
Can you please test with 0.1.0? I am not able to reproduce this bug. If you still have this issue please comment.
