### ISSUE TITLE
IOS Sim. This app does not have permission to use the Camera

### ISSUE THREAD

**Issue by joeblew99** [juliuscanute/qr_code_scanner#13]
Getting this when running the example.

It has the correct setting in the info.plist too

````

<dict>
	<key>NSCameraUsageDescription</key>
	<string>Can we access your camera in order to scan barcodes?</string>
````

**Comment by Vanethos** [comment]
You cannot access or use the camera in the iOS simulator, see this SO answer https://stackoverflow.com/a/25486148

**Comment by juliuscanute** [comment]
Closing as this does not apply to a simulator.
