### ISSUE TITLE
Requires at least SDK 24 (Android 7.0).

### ISSUE THREAD

**Issue by Liliana99** [juliuscanute/qr_code_scanner#130]
Hi,

Thanks so much , great job!!

It is possible to install with sdk low than 24???

**Comment by pedroafonsouza** [comment]
Hi @Liliana99 actually the 0.0.13 version cannot. but in the next version you'll be able to build with min SDK 19.
Meanwhile you can use the 0.0.12 version, or use the github repository at pubspec.yaml like this:

```
qr_code_scanner:
    git:
      url: git://github.com/juliuscanute/qr_code_scanner.git
```

**Comment by Liliana99** [comment]
Ok, thank you!!!!!

**Comment by zuntilZ** [comment]
> Hi @Liliana99 actually the 0.0.13 version cannot. but in the next version you'll be able to build with min SDK 19.
> Meanwhile you can use the 0.0.12 version, or use the github repository at pubspec.yaml like this:
> 
> ```
> qr_code_scanner:
>     git:
>       url: git://github.com/juliuscanute/qr_code_scanner.git
> ```

I using version 0.0.12 and still error again.

**Comment by ndhbr** [comment]
Is there any plan to release the next update?
