### ISSUE TITLE
Build IOS Error

### ISSUE THREAD

**Issue by dufei816** [juliuscanute/qr_code_scanner#134]
/Users/mac/Desktop/jace/flutter/.pub-cache/hosted/pub.flutter-io.cn/qr_code_scanner-0.0.13/ios/Classes/FlutterQrPlugin.m:2:9: 'qr_code_scanner/qr_code_scanner-Swift.h' file not found

**Comment by lcsteil** [comment]
I had the same problem, I can't run on the IOS simulator because of that.

`Xcode's output:

    /Users/*****/Development/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.0.13/ios/Classes/QRView.swift:9:8: error: no such
    module 'MTBBarcodeScanner'
    import MTBBarcodeScanner
           ^

    /Users/*****/Development/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.0.13/ios/Classes/QRView.swift:9:8: error: no such
    module 'MTBBarcodeScanner'
    import MTBBarcodeScanner
           ^

    warning: Could not read serialized diagnostics file: Invalid File: Invalid diagnostics signature (in target 'qr_code_scanner' from project
    'Pods')

    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description`

**Comment by dromedian** [comment]
I only get the error when I try to compile it from xcode and distribute it, I get this error:

```
@import qr_code_scanner;

Module qr_code_scanner not found
```

**Comment by TrueNight** [comment]
> I only get the error when I try to compile it from xcode and distribute it, I get this error:
> 
> ```
> @import qr_code_scanner;
> 
> Module qr_code_scanner not found
> ```

Same here

**Comment by albert0m** [comment]
my problem was that the Pod project and my project had two different Deployment target versions

**Comment by TrueNight** [comment]
> my problem was that the Pod project and my project had two different Deployment target versions

How do you solve this?

**Comment by TrueNight** [comment]
I resolved this issue with this https://github.com/flutter/flutter/issues/43986#issuecomment-573171119

**Comment by juanmendez** [comment]
In my case was to go into XCode, select Runner in the left panel, and in the right panel tap on signing & capabilities, and under team set myself. I tried after to build in iOS and worked. I was previously seeing a warning related to signing & capabilities which I was ignoring.

**Comment by juliansteenbakker** [comment]
I've updated the podspec in the latest release. Please check if the issue is still occurring or not.
