### ISSUE TITLE
on Android, it auto resume when back from background.

### ISSUE THREAD

**Issue by vandong9** [juliuscanute/qr_code_scanner#138]
On Android(Pixel 2), This not happen on iOS (iphone 7):
1. When getting result from scan, 
2. Call Pause
3. Press home button of device
4. Open app again from background
5. See that scan auto change to resume
Log when open app from background: 
D/CameraPreview(18736): pause()
D/CameraPreview(18736): resume()
D/CameraInstance(18736): Opening camera
D/CameraInstance(18736): Configuring camera
I/CameraManager(18736): Camera Display Orientation: 90

**Comment by RaashVision** [comment]
Its happening to me too. It was working fine. Suddenly happen since yesterday
