### ISSUE TITLE
Cant run project on ios device

### ISSUE THREAD

**Issue by akasiid** [juliuscanute/qr_code_scanner#14]
[!] Unable to determine Swift version for the following pods:

`qr_code_scanner` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.beta.3/lib/cocoapods/installer/xcode/target_validator.rb:122:in `verify_swift_pods_swift_version'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.beta.3/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.beta.3/lib/cocoapods/installer.rb:578:in `validate_targets'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.beta.3/lib/cocoapods/installer.rb:158:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.beta.3/lib/cocoapods/command/install.rb:51:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.beta.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.beta.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'

[!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by pmcarlos** [comment]
Same problem here

**Comment by shinevu** [comment]
please add `s.swift_version = '4.2'` into file `ios/qr_code_scanner.podspec` above `end`

**Comment by pmcarlos** [comment]
> please add `s.swift_version = '4.2'` into file `ios/qr_code_scanner.podspec` above `end`

Where is this files supossed to be since i dont found in that route

**Comment by shinevu** [comment]
> > please add `s.swift_version = '4.2'` into file `ios/qr_code_scanner.podspec` above `end`
> 
> Where is this files supossed to be since i dont found in that route

here is: qr_code_scanner/ios/qr_code_scanner.podspec

**Comment by c0h1b4** [comment]
I got this error: 

The Swift pod `qr_code_scanner` depends upon `MTBBarcodeScanner`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

**Comment by juliuscanute** [comment]
duplicate

**Comment by breederComrade** [comment]
Same problem here
