### ISSUE TITLE
Cannot scan UK government QR code

### ISSUE THREAD

**Issue by BenShelbourne** [juliuscanute/qr_code_scanner#143]
The UK government have allowed business owners to create their own QR codes for customers visiting their shops. The QR code does not resolve to a web address but a JWT which contains the information. I want to be able to scan these QR codes but this scanner does not recognise them and trigger an event. I would appreciate it if this could be fixed/added. Thanks

I have attached a sample QR code for testing purposes.

[4094c3f8-f71b-4674-8948-d8ca225c7697_53WWX3V4.pdf](https://github.com/juliuscanute/qr_code_scanner/files/5318591/4094c3f8-f71b-4674-8948-d8ca225c7697_53WWX3V4.pdf)

**Comment by WingCH** [comment]
I tried to scan your QR code on both iOS and android devices, it worked!

![IMG_2575](https://user-images.githubusercontent.com/19588517/97069933-654b9880-1606-11eb-9dc8-be652f1feb18.PNG)

![IMAGE 2020-10-24 14:41:40](https://user-images.githubusercontent.com/19588517/97069997-08041700-1607-11eb-9d03-9455c4400021.jpg)
