### ISSUE TITLE
Stream pauses after sended back with home button and bringed front - iOS

### ISSUE THREAD

**Issue by EmreSURK** [juliuscanute/qr_code_scanner#154]
While the camera was working, if the user presses the home button and sends the app to the background, the camera stream pauses on iOS. 

Expected: Camera stream should go on after re-activating the app.

**Comment by juliansteenbakker** [comment]
Can you please test this with version 0.2.1? I can't reproduce this behaviour on my iPad. If this issue still persists feel free to comment.
