### ISSUE TITLE
How to set Scannable Area

### ISSUE THREAD

**Issue by austyking** [juliuscanute/qr_code_scanner#156]
Is there a way to set the scannable area so that only a part of the camera's view could stream data?

I want to have the whole screen filled with the QRView but only a portion, say, a squared center, would be able to scan the qrcode

**Comment by ffalpha** [comment]
Are you referring to something like this ?
![Screenshot_1605022740](https://user-images.githubusercontent.com/31257148/98696053-55b7a800-2399-11eb-80ba-dd0eb3e3182d.png)

**Comment by austyking** [comment]
Exactly...but also want to prevent the dark areas from scanning

**Comment by ffalpha** [comment]
You can add a simple overlay to your QR view using following code. If you want to make your QR view smaller you can put inside a container. I hope this will help. 

`QRView(
                overlay: QrScannerOverlayShape(
                borderColor: Theme.of(context).primaryColor,
                borderRadius: 10,
                borderLength: 30,
                borderWidth: 10,
                cutOutSize: 300,
              ),`

**Comment by austyking** [comment]
Okay thanks man. I will give this a try, and get back to you

**Comment by austyking** [comment]
It's working as expected. Thanks

**Comment by lyseiha** [comment]
But can i change border to use my own png file?

> You can add a simple overlay to your QR view using following code. If you want to make your QR view smaller you can put inside a container. I hope this will help.
> 
> `QRView( overlay: QrScannerOverlayShape( borderColor: Theme.of(context).primaryColor, borderRadius: 10, borderLength: 30, borderWidth: 10, cutOutSize: 300, ),`
