### ISSUE TITLE
Can't run project on iOS devide

### ISSUE THREAD

**Issue by pmcarlos** [juliuscanute/qr_code_scanner#16]
Downloading dependencies
    -> Installing Flutter (1.0.0)
    -> Installing MTBBarcodeScanner (5.0.8)
      > Copying MTBBarcodeScanner from `/Users/pmcarlos/Library/Caches/CocoaPods/Pods/Release/MTBBarcodeScanner/5.0.8-5b97f` to `Pods/MTBBarcodeScanner`
    -> Installing qr_code_scanner (0.0.2)
    -> Installing shared_preferences (0.0.1)
      - Running pre install hooks
    [!] The following Swift pods cannot yet be integrated as static libraries:
    The Swift pod `qr_code_scanner` depends upon `MTBBarcodeScanner`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/xcode/target_validator.rb:141:in `verify_swift_pods_have_module_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/xcode/target_validator.rb:38:in `validate!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:459:in `validate_targets'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:138:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'
Error output from CocoaPods:
↳
    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Hi I am having this problem,
I have added s.swift_version = '4.2' to the podpsec but it's not working

**Comment by c0h1b4** [comment]
I got this error: 

The Swift pod `qr_code_scanner` depends upon `MTBBarcodeScanner`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

**Comment by juliuscanute** [comment]
let me know if this is still the case...i'll wait for some time before closing.

**Comment by maimanazani** [comment]
I got the same problem.

**Comment by juliuscanute** [comment]
Is @c0h1b4 suggestion not working? in any case try to obtain the latest update, and help us help you by providing the logs incase it is different from the one shown up.

**Comment by maimanazani** [comment]
After setting `use_modular_headers!` in podfile, I got this errors:

/Users/aiman/Development
    tools/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.9+1/ios/Classes/FLTCookieManager.m:33:52:
    warning: 'WKWebsiteDataTypeCookies' is only available on iOS 9.0 or newer [-Wunguarded-availability]
      NSSet *websiteDataTypes = [NSSet setWithArray:@[ WKWebsiteDataTypeCookies ]];
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~
    In module 'WebKit' imported from /Users/aiman/Development
    tools/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.9+1/ios/Classes/FLTCookieManager.h:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2
    .sdk/System/Library/Frameworks/WebKit.framework/Headers/WKWebsiteDataRecord.h:47:28: note:
    'WKWebsiteDataTypeCookies' has been marked as being introduced in iOS 9.0 here, but the deployment target is iOS
    8.0.0
    WK_EXTERN NSString * const WKWebsiteDataTypeCookies API_AVAILABLE(macosx(10.11), ios(9.0));
                               ^
    /Users/aiman/Development
    tools/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.9+1/ios/Classes/FLTCookieManager.m:33:52:
    note: enclose 'WKWebsiteDataTypeCookies' in an @available check to silence this warning
      NSSet *websiteDataTypes = [NSSet setWithArray:@[ WKWebsiteDataTypeCookies ]];
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~
    /Users/aiman/Development
    tools/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.9+1/ios/Classes/FLTCookieManager.m:34:3:
    warning: 'WKWebsiteDataStore' is only available on iOS 9.0 or newer [-Wunguarded-availability]
      WKWebsiteDataStore *dataStore = [WKWebsiteDataStore defaultDataStore];
      ^~~~~~~~~~~~~~~~~~
    In module 'WebKit' imported from /Users/aiman/Development
    tools/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.9+1/ios/Classes/FLTCookieManager.h:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2
    .sdk/System/Library/Frameworks/WebKit.framework/Headers/WKWebsiteDataStore.h:41:12: note: 'WKWebsiteDataStore'
    has been marked as being introduced in iOS 9.0 here, but the deployment target is iOS 8.0.0
    @interface WKWebsiteDataStore : NSObject <NSSecureCoding>
               ^
    /Users/aiman/Development
    tools/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.9+1/ios/Classes/FLTCookieManager.m:34:3:
    note: enclose 'WKWebsiteDataStore' in an @available check to silence this warning
      WKWebsiteDataStore *dataStore = [WKWebsiteDataStore defaultDataStore];
      ^~~~~~~~~~~~~~~~~~
    /Users/aiman/Development
    tools/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.9+1/ios/Classes/FLTCookieManager.m:34:36:
    warning: 'WKWebsiteDataStore' is only available on iOS 9.0 or newer [-Wunguarded-availability]
      WKWebsiteDataStore *dataStore = [WKWebsiteDataStore defaultDataStore];
                                       ^~~~~~~~~~~~~~~~~~
    In module 'WebKit' imported from /Users/aiman/Development
    tools/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.9+1/ios/Classes/FLTCookieManager.h:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2
    .sdk/System/Library/Frameworks/WebKit.framework/Headers/WKWebsiteDataStore.h:41:12: note: 'WKWebsiteDataStore'
    has been marked as being introduced in iOS 9.0 here, but the deployment target is iOS 8.0.0
    @interface WKWebsiteDataStore : NSObject <NSSecureCoding>
               ^
    /Users/aiman/Development
    tools/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.9+1/ios/Classes/FLTCookieManager.m:34:36:
    note: enclose 'WKWebsiteDataStore' in an @available check to silence this warning
      WKWebsiteDataStore *dataStore = [WKWebsiteDataStore defaultDataStore];
                                       ^~~~~~~~~~~~~~~~~~
    /Users/aiman/Development
    tools/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.9+1/ios/Classes/FLTCookieManager.m:36:35:
    warning: 'WKWebsiteDataRecord' is only available on iOS 9.0 or newer [-Wunguarded-availability]
      void (^deleteAndNotify)(NSArray<WKWebsiteDataRecord *> *) =
                                      ^~~~~~~~~~~~~~~~~~~
    In module 'WebKit' imported from /Users/aiman/Development
    tools/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.9+1/ios/Classes/FLTCookieManager.h:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2
    .sdk/System/Library/Frameworks/WebKit.framework/Headers/WKWebsiteDataRecord.h:66:12: note: 'WKWebsiteDataRecord'
    has been marked as being introduced in iOS 9.0 here, but the deployment target is iOS 8.0.0
    @interface WKWebsiteDataRecord : NSObject
               ^
    /Users/aiman/Development
    tools/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.9+1/ios/Classes/FLTCookieManager.m:36:35:
    note: enclose 'WKWebsiteDataRecord' in an @available check to silence this warning
      void (^deleteAndNotify)(NSArray<WKWebsiteDataRecord *> *) =
                                      ^~~~~~~~~~~~~~~~~~~
    /Users/aiman/Development
    tools/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.9+1/ios/Classes/FLTCookieManager.m:37:17:
    warning: 'WKWebsiteDataRecord' is only available on iOS 9.0 or newer [-Wunguarded-availability]
          ^(NSArray<WKWebsiteDataRecord *> *cookies) {
                    ^~~~~~~~~~~~~~~~~~~
    In module 'WebKit' imported from /Users/aiman/Development
    tools/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.9+1/ios/Classes/FLTCookieManager.h:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2
    .sdk/System/Library/Frameworks/WebKit.framework/Headers/WKWebsiteDataRecord.h:66:12: note: 'WKWebsiteDataRecord'
    has been marked as being introduced in iOS 9.0 here, but the deployment target is iOS 8.0.0
    @interface WKWebsiteDataRecord : NSObject
               ^
    /Users/aiman/Development
    tools/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.9+1/ios/Classes/FLTCookieManager.m:37:17:
    note: enclose 'WKWebsiteDataRecord' in an @available check to silence this warning
          ^(NSArray<WKWebsiteDataRecord *> *cookies) {
                    ^~~~~~~~~~~~~~~~~~~
    5 warnings generated.
    === BUILD TARGET qr_code_scanner OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/aiman/Development
    tools/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.0.10/ios/Classes/FlutterQrPlugin.m:2:9: fatal
    error: 'qr_code_scanner/qr_code_scanner-Swift.h' file not found
    #import "qr_code_scanner/qr_code_scanner-Swift.h"
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by ShivamArora** [comment]
The closest fix I found for this issue was to include this line in the `Podfile`.

```
target 'Runner' do
  use_frameworks!           #Required by qr_code_scanner
```

Took a reference for this from the `example` itself on this line:
https://github.com/juliuscanute/qr_code_scanner/blob/b02ae9cafe6087ba99bc0c47bfa2950f6ce02122/example/ios/Podfile#L37

**Comment by 0xVesion** [comment]
Your suggestion also helped me @ShivamArora ! Thank you :)

**Comment by satishsoni777** [comment]
I am also getting same error, is anyone fixed this issue.?

**Comment by maimanazani** [comment]
@satishsoni777 which error you are getting?

**Comment by satishsoni777** [comment]
Thanks @ShivamArora now is working fine. and thanks for quick reply @maimanazani

**Comment by yuchuan08** [comment]
> Your suggestion also helped me @ShivamArora ! Thank you :)

Thank you very much
