### ISSUE TITLE
Repository maintenance

### ISSUE THREAD

**Issue by enricobenedos** [juliuscanute/qr_code_scanner#160]
Hey @juliuscanute,
I really like this package and it is very good because flutter framework at the moment does not support/maintain "natively" a qr scan plugin. It also the only really well working between other scan plugins.

But it seems that the repo has been abandoned and there are some things that need to be adjusted as camera close/disposing on iOS device and other things. There a lot of very interesting PR that will solve a lot of small bugs.

I know that is a open source project and it is public and free donated to the community, but is it possible to keep it updated at least for bugs and compatibility with devices and framework update?

Thanks

**Comment by juliuscanute** [comment]
I am sorry for I am unable to spend time on this project, it wouldn't be in a state it is now if it is wasn't for the community and it saddens me that all the efforts will go waste because of my negligence. Anybody interested in taking this up kindly send me an email I'll grant you the rights you need to take over.

**Comment by enricobenedos** [comment]
I think I'm not the right developer for this repo maintenance because I don't know very well iOS and Android native programming. But I hope that from this issue someone propose himself to become maintainer of this beautiful plugin.

**Comment by juliansteenbakker** [comment]
@juliuscanute I'd like to volunteer to take over this repo. I've developed serveral library and I'm currently developing an application that depends on this package.

**Comment by juliuscanute** [comment]
Thanks!  @juliansteenbakker & @enricobenedos even if you are interested in handling either one of those(Android or iOS) do let me know.

I have added Julian as a collaborator for this project will need you email ID which you can send me privately to grant package upload access.

**Comment by juliansteenbakker** [comment]
> I have added Julian as a collaborator for this project will need you email ID which you can send me privately to grant package upload access.

My mail is juliansteenbakker@outlook.com 
Thank you for granting the rights! Tomorrow I'll start going trough the open issues and PR's.

**Comment by juliuscanute** [comment]
Thank you Julian!

You'll need to send your google account, Sorry for not being direct you can append @gmail.com to my github username.

https://dart.dev/tools/pub/cmd/pub-uploader

> Important: The pub uploader add <email> command sends an invitation that the invited user must accept. For the invitation to work, <email> must be the primary email address of the associated Google account.

**Comment by juliansteenbakker** [comment]
Hello,

My google account is juliansteenbakker@gmail.com<mailto:juliansteenbakker@gmail.com>

Thanks in advance!

On 9 Dec 2020, at 22:55, juliuscanute <notifications@github.com<mailto:notifications@github.com>> wrote:



Thank you Julian!

You'll need to send your google account, Sorry for not being direct you can append @gmail.com to my github username.

https://dart.dev/tools/pub/cmd/pub-uploader

Important: The pub uploader add command sends an invitation that the invited user must accept. For the invitation to work, must be the primary email address of the associated Google account.

**Comment by juliuscanute** [comment]
Thank you Julian, 

You'll have your uploader invitation now 😊
