### ISSUE TITLE
The scan area set by IOS is invalid

### ISSUE THREAD

**Issue by Lanhaoo** [juliuscanute/qr_code_scanner#165]
The scan area set by IOS is invalid. The QR code can be recognized outside the scanning area

**Comment by Rasmunis** [comment]
I have a similar experience.

**Comment by huynhphan89** [comment]
Same issue for me

**Comment by juliansteenbakker** [comment]
[I have created a fix which is pushed to 165-scan-area-ios branch.](https://github.com/juliuscanute/qr_code_scanner/tree/165-scan-area-ios) Can you please check if this solves your problem?

**Comment by juliansteenbakker** [comment]
Changes merged. Will be released in v0.2.0.
