### ISSUE TITLE
Unit defined in android.app.Application.ActivityLifecycleCallbacks

### ISSUE THREAD

**Issue by afkhalid** [juliuscanute/qr_code_scanner#166]
I am getting this error that I dont know how to fix

e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\qr_code_scanner-0.0.14\android\src\main\kotlin\net\touchcapture\qr\flutterqr\QRView.kt: (41, 77): Object is not abstract and does not implement abstract member public abstract fun onActivityPaused(@NonNull p0: Activity): Unit defined in android.app.Application.ActivityLifecycleCallbacks
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\qr_code_scanner-0.0.14\android\src\main\kotlin\net\touchcapture\qr\flutterqr\QRView.kt: (42, 13): 'onActivityPaused' overrides nothing
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\qr_code_scanner-0.0.14\android\src\main\kotlin\net\touchcapture\qr\flutterqr\QRView.kt: (48, 13): 'onActivityResumed' overrides nothing
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\qr_code_scanner-0.0.14\android\src\main\kotlin\net\touchcapture\qr\flutterqr\QRView.kt: (54, 13): 'onActivityStarted' overrides nothing
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\qr_code_scanner-0.0.14\android\src\main\kotlin\net\touchcapture\qr\flutterqr\QRView.kt: (57, 13): 'onActivityDestroyed' overrides nothing
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\qr_code_scanner-0.0.14\android\src\main\kotlin\net\touchcapture\qr\flutterqr\QRView.kt: (60, 13): 'onActivitySaveInstanceState' overrides nothing
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\qr_code_scanner-0.0.14\android\src\main\kotlin\net\touchcapture\qr\flutterqr\QRView.kt: (63, 13): 'onActivityStopped' overrides nothing
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\qr_code_scanner-0.0.14\android\src\main\kotlin\net\touchcapture\qr\flutterqr\QRView.kt: (66, 13): 'onActivityCreated' overrides nothing

**Comment by afkhalid** [comment]
I can see if I were to change the code to be like

```override fun onActivityPaused(p0: Activity) {
                if (p0 == registrar.activity()) {
                    barcodeView?.pause()
                }
            }

            override fun onActivityResumed(p0: Activity) {
                if (p0 == registrar.activity()) {
                    barcodeView?.resume()
                }
            }

            override fun onActivityStarted(p0: Activity) {
            }

            override fun onActivityDestroyed(p0: Activity) {
            }

            override fun onActivitySaveInstanceState(p0: Activity, p1: Bundle) {
            }

            override fun onActivityStopped(p0: Activity) {
            }

            override fun onActivityCreated(p0: Activity, p1: Bundle?) {
            }``` it would work fine. I dont know kotlin but I tried my best implementing the abstract class as it should be.

**Comment by juliansteenbakker** [comment]
I have encountered this issue myself a few days ago and that seems indeed to be the fix. It would be great if you want to make a PR for this! Also, can you post the output of `flutter doctor -v` here? I want to know which version of Flutter and Dart are affected by this issue since i didn't got this error on another PC.

**Comment by afkhalid** [comment]
Thanks, @juliansteenbakker. Here is the Doctor Output

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1198], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.51.1)
[√] Connected device (1 available)

```

**Comment by afkhalid** [comment]
I created this PR as well https://github.com/juliuscanute/qr_code_scanner/pull/167

**Comment by travelog-gypsy** [comment]
Similar kind of issue facing for geolocation, whether i need to follow work around mentioned in previous thread to fix this?

> Task :geolocation:compileDebugKotlin FAILED
e: /Users/name/travelog/app/flutter/.pub-cache/hosted/pub.dartlang.org/geolocation-1.1.2/android/src/main/kotlin/app/loup/geolocation/GeolocationPlugin.kt: (18, 8): Class 'GeolocationPlugin' is not abstract and does not implement abstract member public abstract fun onActivityPaused(@NonNull p0: Activity): Unit defined in android.app.Application.ActivityLifecycleCallbacks
e: /Users/name/travelog/app/flutter/.pub-cache/hosted/pub.dartlang.org/geolocation-1.1.2/android/src/main/kotlin/app/loup/geolocation/GeolocationPlugin.kt: (106, 3): 'onActivityPaused' overrides nothing
e: /Users/name/travelog/app/flutter/.pub-cache/hosted/pub.dartlang.org/geolocation-1.1.2/android/src/main/kotlin/app/loup/geolocation/GeolocationPlugin.kt: (110, 3): 'onActivityResumed' overrides nothing
e: /Users/name/travelog/app/flutter/.pub-cache/hosted/pub.dartlang.org/geolocation-1.1.2/android/src/main/kotlin/app/loup/geolocation/GeolocationPlugin.kt: (114, 3): 'onActivityStarted' overrides nothing
e: /Users/name/travelog/app/flutter/.pub-cache/hosted/pub.dartlang.org/geolocation-1.1.2/android/src/main/kotlin/app/loup/geolocation/GeolocationPlugin.kt: (118, 3): 'onActivityDestroyed' overrides nothing
e: /Users/name/travelog/app/flutter/.pub-cache/hosted/pub.dartlang.org/geolocation-1.1.2/android/src/main/kotlin/app/loup/geolocation/GeolocationPlugin.kt: (122, 3): 'onActivitySaveInstanceState' overrides nothing
e: /Users/name/travelog/app/flutter/.pub-cache/hosted/pub.dartlang.org/geolocation-1.1.2/android/src/main/kotlin/app/loup/geolocation/GeolocationPlugin.kt: (126, 3): 'onActivityStopped' overrides nothing
e: /Users/name/travelog/app/flutter/.pub-cache/hosted/pub.dartlang.org/geolocation-1.1.2/android/src/main/kotlin/app/loup/geolocation/GeolocationPlugin.kt: (130, 3): 'onActivityCreated' overrides nothing

**Comment by KarthikRamanan16** [comment]
> Similar kind of issue facing for geolocation, whether i need to follow work around mentioned in previous thread to fix this?
> 
> This error got from flutter run
> 
> > Task :geolocation:compileDebugKotlin FAILED
> > e: /Users/name/travelog/app/flutter/.pub-cache/hosted/pub.dartlang.org/geolocation-1.1.2/android/src/main/kotlin/app/loup/geolocation/GeolocationPlugin.kt: (18, 8): Class 'GeolocationPlugin' is not abstract and does not implement abstract member public abstract fun onActivityPaused(@nonnull p0: Activity): Unit defined in android.app.Application.ActivityLifecycleCallbacks
> > e: /Users/name/travelog/app/flutter/.pub-cache/hosted/pub.dartlang.org/geolocation-1.1.2/android/src/main/kotlin/app/loup/geolocation/GeolocationPlugin.kt: (106, 3): 'onActivityPaused' overrides nothing
> > e: /Users/name/travelog/app/flutter/.pub-cache/hosted/pub.dartlang.org/geolocation-1.1.2/android/src/main/kotlin/app/loup/geolocation/GeolocationPlugin.kt: (110, 3): 'onActivityResumed' overrides nothing
> > e: /Users/name/travelog/app/flutter/.pub-cache/hosted/pub.dartlang.org/geolocation-1.1.2/android/src/main/kotlin/app/loup/geolocation/GeolocationPlugin.kt: (114, 3): 'onActivityStarted' overrides nothing
> > e: /Users/name/travelog/app/flutter/.pub-cache/hosted/pub.dartlang.org/geolocation-1.1.2/android/src/main/kotlin/app/loup/geolocation/GeolocationPlugin.kt: (118, 3): 'onActivityDestroyed' overrides nothing
> > e: /Users/name/travelog/app/flutter/.pub-cache/hosted/pub.dartlang.org/geolocation-1.1.2/android/src/main/kotlin/app/loup/geolocation/GeolocationPlugin.kt: (122, 3): 'onActivitySaveInstanceState' overrides nothing
> > e: /Users/name/travelog/app/flutter/.pub-cache/hosted/pub.dartlang.org/geolocation-1.1.2/android/src/main/kotlin/app/loup/geolocation/GeolocationPlugin.kt: (126, 3): 'onActivityStopped' overrides nothing
> > e: /Users/name/travelog/app/flutter/.pub-cache/hosted/pub.dartlang.org/geolocation-1.1.2/android/src/main/kotlin/app/loup/geolocation/GeolocationPlugin.kt: (130, 3): 'onActivityCreated' overrides nothing

Im having this same issue on the geolocator plugin ... have u been able to solve this .. if so please share the solution

**Comment by juliansteenbakker** [comment]
> Similar kind of issue facing for geolocation

> Im having this same issue on the geolocator plugin ... have u been able to solve this .. if so please share the solution

This error seems to be because Geolocator is not null-safe. The latest update dates from early 2020. I suggest using another plugin that is null-safe

**Comment by KarthikRamanan16** [comment]
> > Similar kind of issue facing for geolocation
> 
> > Im having this same issue on the geolocator plugin ... have u been able to solve this .. if so please share the solution
> 
> This error seems to be because Geolocator is not null-safe. The latest update dates from early 2020. I suggest using another plugin that is null-safe

oh ... ok on it .. thnx
