### ISSUE TITLE
android 4.4 crash

### ISSUE THREAD

**Issue by sywxf** [juliuscanute/qr_code_scanner#169]
`
Running "flutter pub get" in cameratest...
Launching lib/main.dart on PE TL20 in debug mode...
lib/main.dart:1
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
E/AndroidRuntime(19324): FATAL EXCEPTION: main
E/AndroidRuntime(19324): Process: com.example.cameratest, PID: 19324
E/AndroidRuntime(19324): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.cameratest/com.example.cameratest.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable/launch_background.xml from drawable resource ID #0x7f060054
E/AndroidRuntime(19324): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
E/AndroidRuntime(19324): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2345)
E/AndroidRuntime(19324): 	at android.app.ActivityThread.access$1100(ActivityThread.java:139)
E/AndroidRuntime(19324): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
E/AndroidRuntime(19324): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(19324): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(19324): 	at android.app.ActivityThread.main(ActivityThread.java:5315)
E/AndroidRuntime(19324): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(19324): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(19324): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
E/AndroidRuntime(19324): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
E/AndroidRuntime(19324): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(19324): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/launch_background.xml from drawable resource ID #0x7f060054
E/AndroidRuntime(19324): 	at android.content.res.Resources.loadDrawable(Resources.java:2154)
E/AndroidRuntime(19324): 	at com.huawei.android.content.res.ResourcesEx.loadDrawable(ResourcesEx.java:663)
E/AndroidRuntime(19324): 	at android.content.res.Resources.getDrawable(Resources.java:741)
E/AndroidRuntime(19324): 	at io.flutter.embedding.android.FlutterActivity.getSplashScreenFromManifest(FlutterActivity.java:495)
E/AndroidRuntime(19324): 	at io.flutter.embedding.android.FlutterActivity.provideSplashScreen(FlutterActivity.java:469)
E/AndroidRuntime(19324): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onCreateView(FlutterActivityAndFragmentDelegate.java:301)
E/AndroidRuntime(19324): 	at io.flutter.embedding.android.FlutterActivity.createFlutterView(FlutterActivity.java:520)
E/AndroidRuntime(19324): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:414)
E/AndroidRuntime(19324): 	at android.app.Activity.performCreate(Activity.java:5327)
E/AndroidRuntime(19324): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
E/AndroidRuntime(19324): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2259)
E/AndroidRuntime(19324): 	... 11 more
E/AndroidRuntime(19324): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #4: <item> tag requires a 'drawable' attribute or child tag defining a drawable
E/AndroidRuntime(19324): 	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:164)
E/AndroidRuntime(19324): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:937)
E/AndroidRuntime(19324): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
E/AndroidRuntime(19324): 	at android.content.res.Resources.loadDrawable(Resources.java:2150)
E/AndroidRuntime(19324): 	... 21 more
Error connecting to the service protocol: _flutter.listViews: (-32000) Bad state: The client closed with pending request "_flutter.listViews".
`

Please tell me what to do

**Comment by juliansteenbakker** [comment]
Android 4.4 (api 19) is currently not supported. You can track its progress at #170.
