### ISSUE TITLE
flutter build apk -> failed (resources not found android:attr/fontVariationSettings android:attr/ttcIndex) + solution

### ISSUE THREAD

**Issue by gianlucabonetti** [juliuscanute/qr_code_scanner#17]
Hello
Using the standard imported package, my application works in the emulator, but I cannot package it as release.
I can use the app-debug.apk generated for the emulator on my devices, yet I cannot package properly.

This is the error, which seems to be related to AndroidX (which I don't use in my Flutter app)

```
...
Execution failed for task ':qr_code_scanner:verifyReleaseResources'.    
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  Output:  /home/gl/dev/projects/nautilusboarding/build/qr_code_scanner/intermediates/res/merged/release/values/values.xml:199: error: resource android:attr/fontVariationSettings not found.
  /home/gl/dev/projects/nautilusboarding/build/qr_code_scanner/intermediates/res/merged/release/values/values.xml:200: error: resource android:attr/ttcIndex not found.
  error: failed linking references.                                     
...
```                                                                  

My solution for being able to generate the app-release.apk package, is to patch the file in:
Project -> External Libraries -> Flutter Plugins -> qr_code_scanner_0.0.5/android/gradle.properties
by *removing* the AndroidX references

```
--- gradle.properties.orig	2019-05-11 15:39:22.631938230 +0200
+++ gradle.properties	2019-05-11 15:39:25.063938165 +0200
@@ -1,3 +1 @@
 org.gradle.jvmargs=-Xmx1536M
-android.enableJetifier=true
-android.useAndroidX=true
```

Seems that AndroidX is not required for qr_code_scanner itself to work
Now I can properly build the release package.

Cheers
Gianluca

**Comment by c0h1b4** [comment]
Got the same error, but your solution is not working.

**Comment by c0h1b4** [comment]
Use the PR version, and AndroidX works

**Comment by juliuscanute** [comment]
Latest is migrated to androidx
