### ISSUE TITLE
Android minSDK support at least 21

### ISSUE THREAD

**Issue by alavalmahesh** [juliuscanute/qr_code_scanner#170]
Android minSDK support at least 21

**Comment by juliansteenbakker** [comment]
Please tell me what issue you are having right now. The applications doesn't support api 19 but it should work on 21. I don't have an Android api 21 device so i can't test it right now. Do you keep getting a white screen or is there an error? Please provide more information.

**Comment by alavalmahesh** [comment]
once I set minSDK 21 for android, its suggesting me to minSDK should be 24. its not running the app until I change to 21

**Comment by juliansteenbakker** [comment]
Are you using 0.0.14 or the git repository in your pubspec?

**Comment by alavalmahesh** [comment]
Yes, I am using 0.0.14.

You also mentioned Requires at least SDK 24 (Android 7.0)

**Comment by juliansteenbakker** [comment]
Yes, version 0.0.13 has 24 as requirement. 0.0.14 has 19 as requirement, however there is a bug so it only works from 20 and up. I am still working on fixing that bug. Sometimes when you enter a new version in your pubspec it doesn't download the new version. You can run `flutter pub cache repair` which forces all packages to redownload.

**Comment by juliansteenbakker** [comment]
If you still have this problem on API 21 please let me know. I am closing this for now.
