### ISSUE TITLE
When will you publish PR #167 to pub.dev?

### ISSUE THREAD

**Issue by afkhalid** [juliuscanute/qr_code_scanner#172]
Hi,
I can still see the latest version s 0.0.14 which doesn't include the fix in PR #167. When will you publish the change on that PR?! Thanks!

**Comment by juliansteenbakker** [comment]
Ill try tomorrow or monday. [You can always use the Github repository instead of pub.dev version using:](https://dart.dev/tools/pub/dependencies#git-packages)
`  qr_code_scanner:
    git:
      url: git:://github.com/juliuscanute/qr_code_scanner.git`
