### ISSUE TITLE
[FEATURE] Need a function that supports importing pictures to identify QR codes

### ISSUE THREAD

**Issue by Xutaotaotao** [juliuscanute/qr_code_scanner#175]
**Is your feature request related to a problem? Please describe.**
Need a function that supports importing pictures to identify QR codes

**Describe the solution you'd like**
Need a function that supports importing pictures to identify QR codes

**Additional context**
Need a function that supports importing pictures to identify QR codes

**Comment by juliansteenbakker** [comment]
Duplicate of #37
