### ISSUE TITLE
[Feature] Switch to MLKit

### ISSUE THREAD

**Issue by juliansteenbakker** [juliuscanute/qr_code_scanner#176]
As both zxing and MTBarcodeScanner are both no longer actively maintained i think it's good to look at other frameworks. Right now zxing is giving some trouble supporting older Android SDK's (<24).

Issues to be solved:

- Min SDK (#261). With MLKit we can bring down the MinSDK to 16 instead of 20.

**Comment by hyzyla** [comment]
Hi do you need some help for this issue? I don't have any experience with that library, bit I can be helpful in some way

**Comment by douglasjam** [comment]
I can confirm the need for switching or enhancing it. 

Just tested 2 different solutions in  parallel, this scanner and the one from [this repo](https://github.com/AmolGangadhare/flutter_barcode_scanner) 

And I can confirm that the other one using Android works scans much faster, not caring about the angle or current and adjusting the focus super fast.

Since I love this one so much and it's capacity to customize the UI, streaming, and overlay I think it's worth it.

Go for it, if you need support let us know.

**Comment by juliansteenbakker** [comment]
It's been a while since i opened this issue and i have been working on a version that uses MLKit. I have an almost working version for Android which has much better performance than the current ZXing library. It however makes use of a texture, which has the advantage that it works on every API that flutter supports with openGL. The downside is that it does not communicate with the native code, and as such we can't enable zoom or tap to focus. I am also working on a version that uses hybrid-composition or a native view like the current implementation does however this needs some more time to be ready.

Another issue is that the current packages already uses a native view. This native view is registered on start-up of the app and may cause trouble if we want to use another native view. Besides this is the problem of embedding MLKit library which increases the size of the package. For people only wanting to use the current way of scanning this may be unwanted.

This week I'll be trying to integrate the new framework in the current framework. When I have the results of this I'll post an update.

**Comment by tagirahmad** [comment]
> It's been a while since i opened this issue and i have been working on a version that uses MLKit. I have an almost working version for Android which has much better performance than the current ZXing library. It however makes use of a texture, which has the advantage that it works on every API that flutter supports with openGL. The downside is that it does not communicate with the native code, and as such we can't enable zoom or tap to focus. I am also working on a version that uses hybrid-composition or a native view like the current implementation does however this needs some more time to be ready.
> 
> Another issue is that the current packages already uses a native view. This native view is registered on start-up of the app and may cause trouble if we want to use another native view. Besides this is the problem of embedding MLKit library which increases the size of the package. For people only wanting to use the current way of scanning this may be unwanted.
> 
> This week I'll be trying to integrate the new framework in the current framework. When I have the results of this I'll post an update.

Hello, what's the progress now of adding zoom functionality?

**Comment by blazern** [comment]
Hello, @juliansteenbakker!
It's been almost 2 months since the last update here.

Could you please share current issue status?
And maybe you would find useful some help from the community? :)

**Comment by juliansteenbakker** [comment]
Sorry for all the delay, i have been very busy. However i got the Android part working. You can check that out in the mlkit branch.

**Comment by srikanth-burra** [comment]
Sorry, but I am new to flutter. Is there a possibility to use the code in MLKit branch now in my app or do I have to wait till a version is released ? (If yes, please guide me with the procedure.)

**Comment by juliansteenbakker** [comment]
> Sorry, but I am new to flutter. Is there a possibility to use the code in MLKit branch now in my app or do I have to wait till a version is released ? (If yes, please guide me with the procedure.)

It's not production ready, its a first concept and only works on Android.

**Comment by juliansteenbakker** [comment]
I just released v1.0.0-alpha.1 with MLKit support. Please keep in mind that the class names are subject to change since this is an Alpha version.

**Comment by jabirmayar** [comment]
Hello, thank you for the MlKit ,  is another version coming anytime soon?

**Comment by nssoftengineer** [comment]
I am also facing the same problem with one of QR scanning is working fine but during getting images from the gallery this particular QR always failing. Other QR I am able to read data but particular QR not working.

sharing QR and dependencies below:
![failureQR](https://user-images.githubusercontent.com/5018099/150279763-c92311b1-9341-4fb0-82a5-3b459171064c.png)

 // Barcode model dependencies
    implementation 'com.google.mlkit:barcode-scanning:17.0.1'

getting this log only 

D/TransportRuntime.JobInfoScheduler: Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
D/TransportRuntime.SQLiteEventStore: Storing event with priority=DEFAULT, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler: Upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
V/FA: Connecting to remote service
V/FA: Connection attempt already in progress
D/FA: Connected to remote service
V/FA: Processing queued up service tasks: 2

 .addOnSuccessListener(barcodes -> {
                            for (Barcode barcode : barcodes) {
                                Log.d(TAG, "onSuccess: " + barcode.getRawValue());
                                if (barcode.getRawValue() != null) {
                                    isQrSuccess = true;
                                    handleResult(barcode.getRawValue());
                                } else {
                                    dealWithQRScanFailure();
                                }
                            }
                        })
                        .addOnFailureListener(new OnFailureListener() {
                            @Override
                            public void onFailure(@NonNull Exception e) {
                                Log.d(TAG, "onFailure: ");

                            }
                        }).addOnCompleteListener(new OnCompleteListener<List<Barcode>>() {
                            @Override
                            public void onComplete(@NonNull Task<List<Barcode>> task) {
                                Log.d(TAG, "onComplete: ");
                                if (!isQrSuccess) {
                                    dealWithQRScanFailure();
                                }
                            }
                        });

only addOnCompleteListener getting onComplete listener executing others success or failure listener, not executing.

**Comment by juliansteenbakker** [comment]
After almost 2 years i have published a new package with MLKit support, using the latest CameraX library on Android and native AVFoundation on iOS. Please see #491 for more info.
