### ISSUE TITLE
build error 0.1.0

### ISSUE THREAD

**Issue by yunchiri** [juliuscanute/qr_code_scanner#179]
Android
Thanks good library

I installed latest version 

simulator is ok
but build appbundle is error
I changed minSdkVersion -> 21 but error

what can i change? 

error log

> Build file 'C:\dev\sdk\flutter\.pub-cache\hosted\pub.dartlang.org\qr_code_scanner-0.1.0\android\build.gradle' line: 24
> 
> * What went wrong:
> A problem occurred evaluating root project 'flutter_qr'.
>  Failed to apply plugin [id 'com.android.internal.version-check']
>     Minimum supported Gradle version is 6.5. Current version is 5.6.2. If using the gradle wrapper, try editing the distributionUrl in C:\dev\sdk\flutter\.pub-cache\hosted\pub.dartlang.org\qr_code_scanner-0.1.0\android\gradle\wrapper\gradle-wrapper.properties to gradle-6.5-all.zip
> 
> 
> 
> 
> BUILD FAILED in 830ms
> 
> 
> The plugin qr_code_scanner could not be built due to the issue above.
> 

my build gralde

> 
> def localProperties = new Properties()
> def localPropertiesFile = rootProject.file('local.properties')
> if (localPropertiesFile.exists()) {
>     localPropertiesFile.withReader('UTF-8') { reader ->
>         localProperties.load(reader)
>     }
> }
> 
> def flutterRoot = localProperties.getProperty('flutter.sdk')
> if (flutterRoot == null) {
>     throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
> }
> 
> def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
> if (flutterVersionCode == null) {
>     flutterVersionCode = '1'
> }
> 
> def flutterVersionName = localProperties.getProperty('flutter.versionName')
> if (flutterVersionName == null) {
>     flutterVersionName = '1.0'
> }
> 
> def keystoreProperties = new Properties()
> def keystorePropertiesFile = rootProject.file('key.properties')
> if (keystorePropertiesFile.exists()) {
>     keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
> }
> 
> 
> apply plugin: 'com.android.application'
> apply plugin: 'com.google.gms.google-services'
> apply plugin: 'kotlin-android'
> apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
> 
> android {
>     compileSdkVersion 29
> 
>     sourceSets {
>         main.java.srcDirs += 'src/main/kotlin'
>     }
> 
>     lintOptions {
>         disable 'InvalidPackage'
>     }
> 
>     defaultConfig {
>         // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
>       
>         minSdkVersion 21
>         targetSdkVersion 29
>         versionCode flutterVersionCode.toInteger()
>         versionName flutterVersionName
>     }
> 
>     signingConfigs {
>         release {
>             keyAlias keystoreProperties['keyAlias']
>             keyPassword keystoreProperties['keyPassword']
>             storeFile file(keystoreProperties['storeFile'])
>             storePassword keystoreProperties['storePassword']
>         }
>     }
> 
>     buildTypes {
>         release {
>             // TODO: Add your own signing config for the release build.
>             // Signing with the debug keys for now, so `flutter run --release` works.
>             signingConfig signingConfigs.release
>         }
>     }
> }
> 
> flutter {
>     source '../..'
> }
> 
> dependencies {
>     implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
>     implementation platform('com.google.firebase:firebase-bom:26.0.0')
>     implementation 'com.google.firebase:firebase-analytics-ktx'
> }

`

**Comment by juliansteenbakker** [comment]
Hello, you need to update your gradle by editing `distributionUrl` in `gradle-wrapper.properties` to `distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip`

**Comment by yunchiri** [comment]
Thanks I tried 
my `gradle-wrapper.properties` changed


`# distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip`
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip`

**And `flutter clean && flutter build appbundle`**

> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file 'C:\dev\sdk\flutter\.pub-cache\hosted\pub.dartlang.org\qr_code_scanner-0.1.0\android\build.gradle' line: 24
> 
> * What went wrong:
> A problem occurred evaluating root project 'flutter_qr'.
>  Failed to apply plugin [id 'com.android.internal.version-check']
>     Minimum supported Gradle version is 6.5. Current version is 5.6.2. If using the gradle wrapper, try editing the distributionUrl in C:\dev\sdk\flutter\.pub-cache\hosted\pub.dartlang.org\qr_code_scanner-0.1.0\android\gradle\wrapper\gradle-wrapper.properties to gradle-6.5-all.zip


so i fix 
` C:\dev\sdk\flutter\.pub-cache\hosted\pub.dartlang.org\qr_code_scanner-0.1.0\android\gradle\wrapper\gradle-wrapper.properties`

`# distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip`
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip`


**And `flutter clean && flutter build appbundle`**

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not determine the dependencies of task ':compileReleaseAidl'.
>  SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at 'C:\dev\sdk\flutter\.pub-cache\hosted\pub.dartlang.org\qr_code_scanner-0.1.0\android\local.properties'.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2s
> 
> 
> The plugin qr_code_scanner could not be built due to the issue above.


is there are anything i missing?

**Comment by juliansteenbakker** [comment]
Hmm thats weird. [After some searching i stumbled across this post. ](https://stackoverflow.com/questions/61086708/flutter-sdk-location-not-found-define-location-with-sdk-dir-in-the-local-prope)Maybe you can try this part in particular:
> Upgrade gradle:
> 
> To upgrade gradle in a flutter project, File -> Open and select the Android folder which is part of your Flutter application. When that finishes loading, it will prompt you to upgrade gradle to the latest version. This will resolve the issue

**Comment by yunchiri** [comment]
It's my problem what  android icon image problem
fix images after finlly build success

ps. I don't understand why error fail  location is this library -_-

Thanks for good library and your feedback

**Comment by juliansteenbakker** [comment]
Good to see you solved it!
