### ISSUE TITLE
[BUG] The apps requesting photo and camera permissions in apps start time

### ISSUE THREAD

**Issue by WingCH** [juliuscanute/qr_code_scanner#185]
**Describe the bug**
When I upgrade the version to 0.1.0, the apps requesting photo and camera permissions in apps start time.
The previous version is only requesting when in use qr_code_scanner
tested in android 10

**Screenshots**
![2020-12-18 18 36 27](https://user-images.githubusercontent.com/19588517/102605404-3104dc00-4160-11eb-9423-de0c7a32628a.jpg)

**Comment by atov** [comment]
Same here , trying to figure out. 

qr_code_scanner -> 0.1.0
os-> android 10

**Comment by huyun0-0** [comment]
I also met, please help me
