### ISSUE TITLE
[BUG] Camera Not Working in release build

### ISSUE THREAD

**Issue by mrgulshanyadav** [juliuscanute/qr_code_scanner#189]
**Describe the bug**
Camera not showing in the release build of android as well as iOS, while it is working perfectly in debug mode. It is showing a grey screen in release mode instead of showing a camera view.

**Flutter information**
Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)
    • Flutter version 1.22.5 at F:\src\flutter
    • Framework revision 7891006299 (11 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

**Device (please complete the following information):**
 - Device: iPad 7th Gen, Realme 5s, Samsung Galaxy Tab 5se
 - OS: Android and iOS

**Screenshots**

![Screenshot of the issue on Realme 5s](https://user-images.githubusercontent.com/32040775/102782485-6eb37000-43bf-11eb-8db1-5852bd7984dd.jpeg)

**Additional context**
I have tried in multiple devices, added permissions in Info.plist as well as in AndroidManifest.xml for debug/release/profile all

**Comment by juliansteenbakker** [comment]
I have just released version 0.2.0. It contains some breaking changes however it should also fix some permission issues. Can you please update your project and check if this issue still persists?

**Comment by juliansteenbakker** [comment]
I have build a release version of the example and i could not reproduce this error.

**Comment by guibsonarc** [comment]
Hello @mrgulshanyadav, this happens in the flutter in release mode when a widget exceeds the limits of the screen. I implemented it this way and got the same error:
`Scaffold(
  body: Stack(
    children: <Widget>[
      Expanded(child: _buildQrView(context)),
    ],
  ),
);`

And in that way it worked perfectly:
`Scaffold(
  body: Stack(
    children: <Widget>[
      Container(
        width: MediaQuery.of(context).size.width,
        height: MediaQuery.of(context).size.height,
        child: _buildQrView(context),
      ),
    ],
  ),
);`

**Comment by mrgulshanyadav** [comment]
Hi @juliansteenbakker , actually I have found the issue, it was flutter related issue not for this library. Actually, as @guibsonarc is writing, it was a similar problem. I have solved this issue now. Anyway thanks for the answer @guibsonarc

**Comment by juliansteenbakker** [comment]
Thanks for the update.
