### ISSUE TITLE
Can't run project on Android devide

### ISSUE THREAD

**Issue by rizalkotlin** [juliuscanute/qr_code_scanner#19]
I have a problem during run or build apk in Class' QRView is not abstract and does not implement abstract member @UiThread public abstract fun onMethodCall (@NonNull p0: MethodCall, @NonNull p1 :Channel.Result Method): Unit defined in io. flutter.plugin.common.MethodChannel.MethodCallHandler

**Comment by c0h1b4** [comment]
Same issue here at version 0.0.10

**Comment by c0h1b4** [comment]
e: /Users/mauro/development/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.0.8/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt: (22, 1): Class 'QRView' is not abstract and does not implement abstract member @UiThread public abstract fun onMethodCall(@NonNull p0: MethodCall, @NonNull p1: MethodChannel.Result): Unit defined in io.flutter.plugin.common.MethodChannel.MethodCallHandler
e: /Users/mauro/development/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.0.8/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt: (139, 5): 'onMethodCall' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':qr_code_scanner:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by c0h1b4** [comment]
To fix it:

the code must be updated, it seems that the io.flutter.plugin.common.MethodCall interface has changed and the override must be updated:

Please, developer, change the line 118 at the QRView.kt to (remove the '?'):

...
override fun onMethodCall(call: MethodCall, result: MethodChannel.Result) {
...
This will fix it.

**Comment by shinayser** [comment]
@juliuscanute can you publish a new version with this fix, please?

**Comment by BalaDhruv** [comment]
please update the new one... I got the same issue...

**Comment by juliuscanute** [comment]
Fixed in #20 , Available from 0.0.11
