### ISSUE TITLE
QRView error when not given overlay

### ISSUE THREAD

**Issue by b5710546291** [juliuscanute/qr_code_scanner#193]
I don't know if the new version required overlay but i don't see it required in the constructor. 

https://github.com/juliuscanute/qr_code_scanner/blob/55bfacc44adc5ab9f85a47c822b8b93f41e3dc7f/lib/src/qr_code_scanner.dart#L163

Console error
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'cutOutSize' was called on null.
Receiver: null
Tried calling: cutOutSize
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _QRViewState._onPlatformViewCreated (package:qr_code_scanner/src/qr_code_scanner.dart:163:67)

**Comment by juliansteenbakker** [comment]
Thats my fault, i'm gonna fix it right away.

**Comment by juliansteenbakker** [comment]
I have released version 0.2.1 which fixes this issue by adding a null check to see if any overlay is set. The update should be available any minute now.
