### ISSUE TITLE
black screen after scan?

### ISSUE THREAD

**Issue by clragon** [juliuscanute/qr_code_scanner#194]
**Describe the bug**
When scanning a QR Code, the camera feed is stopped and the preview goes black.

Calling Pause and Resume will restore it. Hot reloading will also do so.
After restoring the preview once, scanning another QR code will not destroy it.

I am not sure wether this is intended behaviour. Is there a way to prevent the camera from closing after a scan?

**Flutter information**
```
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19041.685], locale de-DE)
    • Flutter version 1.22.5 at C:\Users\clragon\AppData\Local\flutter
    • Framework revision 7891006299 (12 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\clragon\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: D:\Program Files\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.
```

**Device (please complete the following information):**
 - Device: Pixel 3
 - OS: API 30

**Additional context**
I can only test this on android, so I do not know wether it is a problem on iOS.

**Comment by juliansteenbakker** [comment]
Which version of the plugin are you using?

**Comment by clragon** [comment]
from my pubspec.yaml:
`qr_code_scanner: ^0.2.1`

**Comment by clragon** [comment]
Here is a GIF showing the issue.

![4442196](https://user-images.githubusercontent.com/11785085/102889375-d4a10580-445a-11eb-9d7b-b8d3b167ce97.gif)

**Comment by juliansteenbakker** [comment]
I see you are using a simulated camera view rather than a real device camera. I just tried it on several real devices with camera and i cant really reproduce this behaviour. Maybe you can try it with a real camera view?

**Comment by juliansteenbakker** [comment]
Wait i think i know what it is. When you first scan the QR code a bar appears which forces the QRView to resize. I think thats causing a problem somewhere. I'm currently working on a new release which has improved size listeners. For now i would suggest not resizing the view.

**Comment by clragon** [comment]
Youre right, thats it. Gif:

![3720667](https://user-images.githubusercontent.com/11785085/102891040-d7512a00-445d-11eb-9de1-25683f658a64.gif)

**Comment by clragon** [comment]
_this issue also seems to occur when changing rotation. I'm not sure if there's a workaround for that._

**Comment by juliansteenbakker** [comment]
Did you wrap your `QRView` with a `SizeChangedLayoutNotifier` and a `NotificationListener` like described in the readme.md? 

As i said, this will change in the upcomming v0.3.0 as i am currently working on a improved version.

```
// To ensure the Scanner view is properly sizes after rotation
             // we need to listen for Flutter SizeChanged notification and update controller
            child: NotificationListener<SizeChangedLayoutNotification>(
              onNotification: (notification) {
                Future.microtask(() => controller?.updateDimensions(qrKey));
                return false;
              },
              child: SizeChangedLayoutNotifier(
                key: const Key('qr-size-notifier'),
                child: QRView(
                  key: qrKey,
                  onQRViewCreated: _onQRViewCreated,
                ),
              ),
            ),
```

**Comment by clragon** [comment]
I did try that, camera still breaks 🤔

**Comment by juliansteenbakker** [comment]
And do you get the same behaviour from the sample app provided in this repo?  I just can't seem to reproduce this..

**Comment by clragon** [comment]
my code:
https://hastebin.com/hehufuvonu.dart

**Comment by juliansteenbakker** [comment]
So with your code i managed to reproduce the error, but it only occurs 20% of the time on my device. This is something i am hoping to fix in the upcoming release so please stay tuned for that.

**Comment by clragon** [comment]
just another note here, it seems to successfully restore the camera feed on my physical device (Android API 28)
