### ISSUE TITLE
[FEATURE] refocus camera

### ISSUE THREAD

**Issue by clragon** [juliuscanute/qr_code_scanner#196]
**Is your feature request related to a problem? Please describe.**
Sometimes the camera unfocuses. it is hard to get it to refocus.

**Describe the solution you'd like**
It would be nice to be able to have a call on the controller to refocus the camera. (`controller.refocusCamera()`)
This way we could for example, wrap the QrView in a GestureDetector to call the refocus, making it similar to stock camera apps.

**Additional context**
I'm not sure if this is possible. I have looked at the code and it seems camera commands are sent over channels. I dont know if this exposes functionality to control the focus.

**Comment by juliansteenbakker** [comment]
Thank you for this request. There is another issue related to focus #96. I am checking the possibility to add tap to focus for the next release. For now i am closing this issue as duplicate and continuing discussion in #96.
