### ISSUE TITLE
[FEATURE] Make text inside of QRView UIAlertView dialog customizable

### ISSUE THREAD

**Issue by FogelAO** [juliuscanute/qr_code_scanner#198]
**By default if scanning is unavailable hardcoded value will be shown in dialog**
By default QRView will show UIAlertView with hardcoded text that scanning is un available (if it is). It will be strange if the app is localized
**I would like to make it customizable from Flutter side**
I think it will be nice if we could change this message from the Flutter when we initialize the widget

**Comment by juliansteenbakker** [comment]
duplicate of #103
