### ISSUE TITLE
[BUG]  Unusual size of QrView widget in ios

### ISSUE THREAD

**Issue by SoeWaiYan** [juliuscanute/qr_code_scanner#199]
**The bug**( hoping to get fixed asap)
When I tried to embed QrView widget into a  scaffold , it works well on android but  in ios it  shows unsual preview of camera size. btw, Thanks for your effort.

**Flutter information**
output of `flutter doctor -v`
-- [✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-MM)
    • Flutter version 1.22.5 at /Users/soewaiyanmyowin/Documents/GitHub/flutter
    • Framework revision 7891006299 (2 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/soewaiyanmyowin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/soewaiyanmyowin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

**Device (please complete the following information):**
 - Device: iPhone 7 Plus
 - OS: ios 14

**Screenshots**

![image](https://user-images.githubusercontent.com/38293630/103192205-3b646a00-4906-11eb-8cf7-e0ce07a648c2.png)

**Comment by imamabdulazis** [comment]
I've some issue on this, camera width is not expand to border width when open scanner

**Comment by m-schmailzl** [comment]
@SoeWaiYan Did you solve the problem?
I have the same problem.
iPhone 7, iOS 14.3

**Comment by FickleLife** [comment]
@soewaiyanmyowin also wondering if you solved it, I am seeing something similar https://github.com/juliuscanute/qr_code_scanner/issues/288

**Comment by soewaiyanmyowin** [comment]
I didn't do anything special ,I just upgraded the package version to latest.And it was ok.

**Comment by imamabdulazis** [comment]
Bug is gone with latest version.
