### ISSUE TITLE
Cannot run project on ios device

### ISSUE THREAD

**Issue by Vanethos** [juliuscanute/qr_code_scanner#2]
Tried to run example from this project, but couldn't run, so I tried to create a new project with swift support to replicate the problem:

Steps to reproduce:

`flutter create -i swift -a kotlin swift_qr_test`

Copy the code from https://github.com/juliuscanute/qr_code_scanner/blob/master/example/lib/main.dart into the project main

`flutter run` on ios device (iPhone 6, iPad air and iPhone 5s tested)

Result:

```
=== BUILD TARGET qr_code_scanner OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/goncalopalma/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.0.2/ios/Classes/FlutterQrPlugin.m:2:9:
    fatal error: 'qr_code_scanner-Swift.h' file not found
    #import "qr_code_scanner-Swift.h"
            ^~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by jiangyue2780** [comment]
+1
