### ISSUE TITLE
Reading as upcE barcode instead of QR code [BUG] 

### ISSUE THREAD

**Issue by somdipdey** [juliuscanute/qr_code_scanner#202]
**Describe the bug**
I am using the example provided in this repo. When i am trying to scan the QR code (screenshot below) it is  saying the following:

> Barcode Type: upcE Data: 13258283

Instead when I am using other QR code canning app such as QR code scanner & Barcode scanner (no ads) from Google Play Store (https://play.google.com/store/apps/details?id=com.camvision.qrcode.barcode.reader) it is giving me the correct output, which is as follows:

> 5GnnqzQwfYBFmjT0+QypP1Hgll3tQhUCac7eJaIMEg5DlbWA7lMo7C0QB15tKsFa
> EwnUnpFsxTi/xPz489Qwt62MmlQYZoSukTAAtc6dofp7yAdZtWiH77m1vCBjZaPz
> TUBNhyywRsvBfBXi5UzGbp3SHLyTEwnjS4c8f622DI5mF9O+Tqsx9fEQjkBiffir
> 0AKkYhjtxII5Kay33htmeDLFGK04fhi/q0+hvl1G8k2Ln2xlMpyw8MryVt6Jekxo
> NgCORnZvI5GDF5VOLuEN2NsqhOIZTD999RrtczLzn/rRCObCU3LDbqCO/K2y4a2/
> uo7eqvCswMPex8p4wzreET2mzW/vt+XjLuMYuon8WllLkHcOqi2ho7lA4SpKoNQF
> M4Nr9TeARMCm4II1jZnu+vnSRcQNqx1JY8xxfI+dE9Rep0p/T9oPwFVfZ7mrXZ+Q
> kcSwqD+kKWIKAO5xmPmm9Aah/LdmR5/ZZDBg5yjNTBvAI+UJ281H3Sr/ImCXrhiY
> VRtjCqIdWR8hVOE6F/OcwWIDmNfUYFvr4KYEc/efmO0rrSBeybIdS8M+daLLVRi3
> 1L1m1yEZHtG/EHy9qAoM87oW+2CDL0nx0ST1Ow/FJr2z6mPIlFqxET3gzfcu1LR+
> 6qW1NVK5G/lvZmoAoi8m8uZnGqk3W3ZjLhb9VRtezlw7boWaFKiboirSFq5isQml
> 7JM9bn+JLVd9AblpwwNSwnSLd6flpKVxnS6WRijG1BygPA3WJ37KxPWptC1F6Z3a
> Xb4VJ6l5FHSP1mhujcRtndXBbHGoQBsZ2JM8YAXfkgMJ0z/a1wSymQGN7K+ZGSH+
> LhEEoRqkkJ64GYVTy3JjK0BD6W7KUzNrgZJ8fJ9A4niOYREg2Xn99z+ME9cttBeC
> 1YVQlS1mxWtyRKfIpUDJRuAT2FF3//RUMR/GNFz++TB1YnQeQwHEvHpUNexmhgSW
> doGHpR0EUgszd33O1WTrck6zCzchIRzCq2D+KxW6KAowJsDR7uZ+p47KCToVgzy9
> CYQrfRV5GoC0t5ioVuh3fhNy8Ez5Wx1HdbnU4VKA/fjBAZsguN7XcSxU2KrAzpwX
> E5w+xLeHpCXtPfQoPk7EO2zPCdRLHGK0qDfgswFHDLFOszDBA3xm7hb2n8mmxYHa
> +K6TeWHhaJkKkJGeeI9J8+vSoXqbfqC7K3yai4Y7zZgAfYDf3A0myplIsOlkO4en
> dlJ8Imvr6SylguTclbkGvX7yILz5K2RE8x4hdbNRHE8JYwWQy4Zu74WRHvwENYMR
> gZoVo8LwTDGfMkEnJiVbX+DBkZ1B8Ij0mBK3oACL+pzVLf4eLJJHU551LYrLYP9G
> 3coC8zWRQqoROp8pNoQ7JoVDpDO2ye/2DIvti/XVwpwfSrq5lNNJS4EgwLNyLPdg
> yvg9f+iF/KIFwRSKOX+/KEI36bfx7Ho2g6hBt3/bWT5kgwgE+O7vUf5kRdAwlOmN
> 8fl06yuIeEESfsFdnTAxuu644I/t0p/Vhyp+oBWMVX0g2QN4RfUcIDRL2QbwsB6o
> iTR8jJb1ur5Xj8cnLkPC4Ft9TLk1TVkVRgWmWOFCyKM=
> 

**Can someone tell me why this example scanner reading it as upcE barcode and how to actually read the QR code properly and fetch the correct embedded value?**

**Flutter information**
[✓] Flutter (Channel unknown, v1.16.3, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.16.3 at /Users/somdipdey/Downloads/flutter
    • Framework revision be3a4b37b3 (9 months ago), 2020-03-26 18:08:05 -0700
    • Engine revision b2bdeb3f0f
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
    • Android SDK at /Users/somdipdey/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-30, build-tools 30.0.0-rc2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.52.1)
    • VS Code at /Users/somdipdey/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (1 available)
    • SM N960F • 2aabc8a0393f7ece • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

**Device (please complete the following information):**
 - Device: Samsung Note 9 (SM N960F)
 - OS: Android version 10

**Screenshots**
QR code that I am trying to scan:
![Screenshot_20201229-194033](https://user-images.githubusercontent.com/8515608/103310874-9edabe80-4a10-11eb-9102-84e9460df0b1.jpg)

**Comment by juliansteenbakker** [comment]
Thats weird. I have the same output as you on Android. iOS seems to be working fine. I think this is a problem in the underlaying qr framework for Android (ZXING). Ill see if i can do anything about it but since ZXING is maintenance only so it would be better to switch to another framework. This progress can be found at #176

**Comment by juliansteenbakker** [comment]
I am closing this for now because this can't be fixed with the current framework.
