### ISSUE TITLE
getting error while navigating to new page

### ISSUE THREAD

**Issue by suraj740** [juliuscanute/qr_code_scanner#203]
After scanning qrcode, i am trying to navigate to new page, but getting error `
E/flutter (11266): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3815 pos 12: '!_debugLocked': is not true.`

```
Widget build(BuildContext context) {
    // print('widget called');
    if (result != null) {
      Navigator.of(context).pushNamed('/route-name', arguments: result);
    }
 }
```
@juliuscanute Could you please help.
Thanks!!

**Comment by AbdOoSaed** [comment]
this fix my problem
```dart
void _onQRViewCreated(QRViewController controller) {
    this.controller = controller;
    controller.scannedDataStream.listen((Barcode scanData) {
      if (scanData.format == BarcodeFormat.qrcode && scanData.code != null) {
        controller.pauseCamera();
        Navigator.pop(context, scanData.code);
      }
    });
  }
```

**Comment by suraj740** [comment]
Thanks @AbdOoSaed . Its worked for me as well.✌️✌️
