### ISSUE TITLE
QRView should take QrScannerOverlayShape instead of ShapeBorder as argument

### ISSUE THREAD

**Issue by kazume** [juliuscanute/qr_code_scanner#204]
The QRView takes a ShapeBorder as argument but doesn't work when using one. I guess that might be because it gets type casted [here](https://github.com/juliuscanute/qr_code_scanner/blob/c6d42a7551e403ada29992f30648ddaf13bdc577/lib/src/qr_code_scanner.dart#L165)?

In my opinion, if the overlay needs to be of type QrScannerOverlayShape, it would be better to just declare it that way.

**Comment by juliansteenbakker** [comment]
You could create your own `ShapeBorder` class by extending `ShapeBorder`. You cant use it directly because its an abstract class.

**Comment by kazume** [comment]
Ye, that's what I did but doesn't work. In assume that this is due to the
fact that the shape gets casted to a QrScannerOverlayShape in
_onPlatformViewCreated.

**Comment by juliansteenbakker** [comment]
You are right. Isn't it possible to create your own shapeborder by extending QrScannerOverlayShape rather that the ShapeBorder? That way the cutOutSize is always provided.

**Comment by kazume** [comment]
Yeah, that's what I ended up doing and hence my proposal: changing QRView's argument from ShapeBorder to QrScannerOverlayShape would suggest exactly that.

**Comment by juliansteenbakker** [comment]
Ahh i get it. Lets get that fixed!

**Comment by Jojoooo1** [comment]
Is there any workaround to make an overlay rectangle ? So it can be adapted to scanning barcode ?

**Comment by kazume** [comment]
> Is there any workaround to make an overlay rectangle ? So it can be adapted to scanning barcode ?

That's exactly what we were trying to do :) So yes: subclass QrScannerOverlayShape and implement the paint() function as needed.

Not completely tweaked yet, but here's a [gist](https://gist.github.com/kazume/31617541e4e3b94e4add7112a0443dd1).

**Comment by Jojoooo1** [comment]
Works very ! Just needed to add the -cutOutBottomOffset in the cutOutRect calculation :)
