### ISSUE TITLE
[BUG] When "cut out bottom offset" is set, the actual scanning area remains unchanged

### ISSUE THREAD

**Issue by 2673542667** [juliuscanute/qr_code_scanner#205]
![image](https://user-images.githubusercontent.com/27001255/103600344-2741ed80-4f42-11eb-9b46-31e664c1b689.png)

![image](https://user-images.githubusercontent.com/27001255/103600500-869ffd80-4f42-11eb-9176-934c3322e8fe.png)

**Comment by juliansteenbakker** [comment]
Hello, have you managed to solve this issue?

**Comment by 2673542667** [comment]
> Hello, have you managed to solve this issue?

Hello, I changed the local source code, But it's temporary

**Comment by juliansteenbakker** [comment]
You can always try using the master branch instead of pub package. Im trying to release V0.3.0 today and that may fix your issue.

**Comment by 2673542667** [comment]
> You can always try using the master branch instead of pub package. Im trying to release V0.3.0 today and that may fix your issue.

OK, thank you
