### ISSUE TITLE
Disable auto-start from camera

### ISSUE THREAD

**Issue by smofe** [juliuscanute/qr_code_scanner#206]
I have currently the issue that I have the qr_code_scanner in the middle page of a PageView (Page 2 of 3). I want to animate from page 1 to page 3, which transitions over the qr_code_scanner page. However if I do this, the camera gets loaded very briefly during the transition, resulting in stutters and bad performance. 

Is there a way to load the controller in a paused state? Or configure it to always start paused first?

Possibly related to issue #138 

Thank you.

**Comment by juliansteenbakker** [comment]
Please see answer in #228
