### ISSUE TITLE
[FEATURE] Camera Settings

### ISSUE THREAD

**Issue by smofe** [juliuscanute/qr_code_scanner#207]
Add the ability to change various camera settings using the QRView or QRViewController Widgets. Particulary interesting would be the ability to change the preview-size to a lower resolution to enhance performance. Maybe also settings like preview-frame-rate or zoom value.

I'm not sure if this is possible with the used frameworks, but it would be very helpful.

**Comment by juliansteenbakker** [comment]
I have added some camera settings like request which camera to be used on startup. The zoom settings and resolution are handled by the framework so this can only be changed if we move to another framework. This progress is tracked at #176
