### ISSUE TITLE
IOS 14 Green dot still appear even after control.dispose() called [BUG] 

### ISSUE THREAD

**Issue by darkh** [juliuscanute/qr_code_scanner#208]
**Describe the bug**
in IOS 14 they add it feature where a green dot will appear while the camera is being used by the app.
the problem when I change the widget and the control.dispose() called still the green dot stay active even the app doesn't use the camera
is there a way to close the camera when the app doesn't use it?

**Edit**
seems the problem happens only when QrScannerOverlayShape add it 

**Flutter information**
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-JO)
    • Flutter version 1.22.5 at /Users/hasankhateb/development/flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0
**Device :**
 - Device: [iPhone11]
 - OS: [IOS 14]

**Comment by enricobenedos** [comment]
The bug seems to be reintroduced as explained on [my comment](https://github.com/juliuscanute/qr_code_scanner/issues/137#issuecomment-751286722)

**Comment by azakost** [comment]
I solved this problem by observing two conditions:
1. Added controller.pauseCamera() in widget dispose method
2. Used **only** Navigator.pushReplacement() for navigating **from**  QR-scanner widget. (Note that Navigator.pop() or Navigator.push() doesn't work)

Here is an example code:

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:qr_code_scanner/qr_code_scanner.dart';

void main() => runApp(MaterialApp(home: Home()));

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: FlatButton(
          onPressed: () {
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => Scanner()),
            );
          },
          child: Text("Run QR Scanner"),
        ),
      ),
    );
  }
}

class Scanner extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _ScannerState();
}

class _ScannerState extends State<Scanner> {
  Barcode result;
  QRViewController controller;
  final GlobalKey qrKey = GlobalKey(debugLabel: 'QR');

  void _onQRViewCreated(QRViewController controller) {
    this.controller = controller;
    controller.scannedDataStream.listen((scanData) {
      if (result == null) {
        result = scanData;
      } else {
        controller.pauseCamera();
        
        // Navigate to another widget using 'pushReplacement' only 
        Navigator.pushReplacement(
          context,
          MaterialPageRoute(builder: (context) => Result(result.code)),
        );
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          Column(
            children: [
              Expanded(
                child: QRView(
                  key: qrKey,
                  onQRViewCreated: _onQRViewCreated,
                  overlay: QrScannerOverlayShape(
                    borderColor: Colors.red,
                    borderRadius: 10,
                    borderLength: 30,
                    borderWidth: 10,
                    cutOutSize: 300,
                  ),
                ),
              ),
            ],
          ),
          Container(
            alignment: Alignment.topCenter,
            padding: EdgeInsets.only(top: 48),
            child: Text(
              'Scan QR-code',
              style: TextStyle(
                color: Colors.white,
              ),
            ),
          ),
          Container(
            alignment: Alignment.bottomCenter,
            padding: EdgeInsets.only(bottom: 48),
            child: IconButton(
              icon: Icon(CupertinoIcons.xmark, color: Colors.white),
              onPressed: () => {

                // Navigate to another widget using 'pushReplacement' only 
                Navigator.pushReplacement(
                  context,
                  MaterialPageRoute(builder: (context) => Home()),
                )
              },
            ),
          ),
        ],
      ),
    );
  }

  @override
  void dispose() {
    controller.pauseCamera(); // Very important part!
    controller.dispose();
    super.dispose();
  }
}

class Result extends StatelessWidget {
  final String data;
  Result(this.data);
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: Icon(CupertinoIcons.chevron_back),
          onPressed: () => {
            Navigator.pushReplacement(
              context,
              MaterialPageRoute(builder: (context) => Scanner()),
            )
          },
        ),
      ),
      body: Center(
        child: Text(data),
      ),
    );
  }
}
```

**Comment by darkh** [comment]
actually I solved by removing the QRview Overlay
I don't know why but this problem only happen when I set the QrScannerOverlayShape 

right now I did the follow 
` child: Stack(
        children: [
          QRView(
            key: qrKey,
            onQRViewCreated: _onQRViewCreated,
          ),
          Container(
            width: MediaQuery.of(context).size.width,
            height: MediaQuery.of(context).size.height,
            decoration: ShapeDecoration(
                shape: QrScannerOverlayShape(
              borderColor: widget.color,
              borderRadius: 10,
              borderLength: 30,
              borderWidth: 10,
              cutOutSize: 200,
              cutOutBottomOffset: offset,
            )),
          ),
        ],
      ),`

**Comment by juliansteenbakker** [comment]
@enricobenedos Do you still encounter this issue on v0.3.0?  Also, do you use an overlay? I can't reproduce this with the example app.

**Comment by xvrh** [comment]
@juliansteenbakker I can reproduce with v0.3.0.

Here is the example app slightly modified: https://gist.github.com/xvrh/6d982186f78bb98b47247641235b54e4
Press "Open", then "Back" in the AppBar and see that the green dot is still visible.

It goes away if I edit the `dispose` method with:
```dart
  @override
  void dispose() {
    controller?.pauseCamera();
    controller?.dispose();
    super.dispose();
  }
```

**Comment by enricobenedos** [comment]
> @enricobenedos Do you still encounter this issue on v0.3.0? Also, do you use an overlay? I can't reproduce this with the example app.

On `0.3.0` it is newly solved! 😃 

**Only for info:** On `dispose()` method I "simply" call `dispose()` method. I'm also using `QrScannerOverlayShape`.

**Comment by cantomris** [comment]
On iOS, I've got the same problem while using the latest version.
Sacrificing `QrScannerOverlayShape` solved my problem.
There is no issue on Android though.
