### ISSUE TITLE
[BUG] [iOS] Scanner works very slow

### ISSUE THREAD

**Issue by JortdeBokx** [juliuscanute/qr_code_scanner#209]
**Describe the bug**
When opening the scanner on iOS, the camera loads and the image is displayed to the user. However the scanning of various barcodes (data-matrix, code-128, qr) takes a very long time (>1 minute) When printing the result of the stream, after this waiting time all the results are printed simultaneously. 

**Flutter information**

 [✓] Flutter (Channel stable, 1.22.4, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.4 at /Users/<user>/flutter
    • Framework revision 1aafb3a8b9 (8 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

**Device:**
 - Device: iPad Mini 2
 - OS: iOS14.2

**Additional context**
Using version 0.2.1 of this plugin

**Comment by steve3d** [comment]
the scan process on ios seems have random delay with `onQRViewCreated`, sometimes it's fast, sometime it won't work.

**Comment by gibahjoe** [comment]
I have experienced same issue. for some reason, scanning is slow on ios

**Comment by steve3d** [comment]
might be the problem of MTBBarcodeScanner?

it's no longer maintained.

**Comment by JortdeBokx** [comment]
Maybe using AVCaptureSession instead of MTBBarcodeScanner would help, 
as used in my current alternative [flutter_barcode_scanner](https://github.com/AmolGangadhare/flutter_barcode_scanner/blob/master/ios/Classes/SwiftFlutterBarcodeScannerPlugin.swift)

**Comment by juliansteenbakker** [comment]
I am investigating if we should use another framework like MLKit in favor of MTBBarcodeScanner however right now i don't have the time to implement this. The progress of this can be tracked at #176.

I have an iPad mini 2 and i can't reproduce this behaviour using the latest v0.3.0. Can you please try with this version, or otherwise check with flutter channel dev?
