### ISSUE TITLE
[android] on "app exit" : java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar

### ISSUE THREAD

**Issue by TransFormes** [juliuscanute/qr_code_scanner#210]
E/AndroidRuntime(11344): java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
E/AndroidRuntime(11344):        at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:616)
E/AndroidRuntime(11344):        at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)
E/AndroidRuntime(11344):        at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
E/AndroidRuntime(11344):        at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
E/AndroidRuntime(11344):        at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:173)
E/AndroidRuntime(11344):        at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:87)
E/AndroidRuntime(11344):        at com.journeyapps.barcodescanner.Decoder.decode(Decoder.java:75)
E/AndroidRuntime(11344):        at com.journeyapps.barcodescanner.Decoder.decode(Decoder.java:49)
E/AndroidRuntime(11344):        at com.journeyapps.barcodescanner.DecoderThread.decode(DecoderThread.java:146)
E/AndroidRuntime(11344):        at com.journeyapps.barcodescanner.DecoderThread.access$000(DecoderThread.java:22)
E/AndroidRuntime(11344):        at com.journeyapps.barcodescanner.DecoderThread$1.handleMessage(DecoderThread.java:38)
E/AndroidRuntime(11344):        at android.os.Handler.dispatchMessage(Handler.java:98)
E/AndroidRuntime(11344):        at android.os.Looper.loop(Looper.java:179)
E/AndroidRuntime(11344):        at android.os.HandlerThread.run(HandlerThread.java:61)
D/CameraPreview(11344): pause()
D/CameraInstance(11344): Closing camera

**Comment by juliansteenbakker** [comment]
What phone are you using? Can you please try again with version 0.3.0.
