### ISSUE TITLE
Can not run on iOS

### ISSUE THREAD

**Issue by hu70258tao** [juliuscanute/qr_code_scanner#215]
/Volumes/HuTao/WorkStation/FlutterSDK/.pub-cache/hosted/pub.flutter-io.cn/qr_code_scanner-0.2.1/ios/Classes/FlutterQrPlugin.m:2:9: 'qr_code_scanner/qr_code_scanner-Swift.h' file not found

**Comment by juliansteenbakker** [comment]
Try the following:

```

1. Remove example/ios/Flutter/Flutter.podspec: rm example/ios/Flutter/Flutter.podspec
2. flutter clean
3. Run your app again.

```

source https://github.com/flutter/flutter/issues/70895#issuecomment-744734693
