### ISSUE TITLE
IOS no message permisson (0.3.0) [BUG] 

### ISSUE THREAD

**Issue by lacoste-sochi** [juliuscanute/qr_code_scanner#219]
**Describe the bug**
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: PlatformException(cameraPermission, Permission denied to access the camera, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>

**Flutter information**

permission added 
<key>io.flutter.embedded_views_preview</key>
<true/>
<key>NSCameraUsageDescription</key>
<string>This app needs camera access to scan QR codes</string>

flutter clean
emulator clean
build clean in XCode 12
flutter channel master

**Device (please complete the following information):**
 - Device:  Iphone 12
 - OS: 14.3 and 12.0

**Additional context**
Android good ...Please fix problem

![image](https://user-images.githubusercontent.com/42961050/104367582-168a0c80-552c-11eb-90d2-dd9f4e1b9bc8.png)

`[✓] Flutter (Channel master, 1.26.0-2.0.pre.301, on Mac OS X 10.15.6 19G2021 darwin-x64, locale ru-RU)
    • Flutter version 1.26.0-2.0.pre.301 at /Users/admin/Desktop/flutter
    • Framework revision f70ad37ec9 (50 minutes ago), 2021-01-12 11:59:03 -0800
    • Engine revision 10cee6abcb
    • Dart version 2.12.0 (build 2.12.0-214.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /usr/local/share/android-sdk
    ✗ Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0.beta.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • iPhone 8 Plus (mobile) • 917968FC-6739-417D-BB3C-A29D2FDB41F3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-12-0`

**Comment by juliansteenbakker** [comment]
It seems like you have rejected the camera permission. Can you see and check if the permission is denied from the settings page of iOS?

**Comment by lacoste-sochi** [comment]
> It seems like you have rejected the camera permission. Can you see and check if the permission is denied from the settings page of iOS?

On all emulators =(

![image](https://user-images.githubusercontent.com/42961050/104372763-222c0200-5531-11eb-92a7-7f46b66f132a.png)

**Comment by enricobenedos** [comment]
Hey @lacoste-sochi, on real devices permissions are asked with no problems. As far as I know iOS simulators [does not support camera access](https://help.apple.com/simulator/mac/current/#/devb0244142d) and this cause the exception below:

![image](https://user-images.githubusercontent.com/12233746/104374938-e722d200-5522-11eb-964a-7e86a7c24386.png)

 I think the exception is normal (a little bit misleading with "denied" keyword) and you need a real device to test it.

**Comment by lacoste-sochi** [comment]
> Hey @lacoste-sochi, on real devices permissions are asked with no problems. As far as I know iOS simulators [does not support camera access](https://help.apple.com/simulator/mac/current/#/devb0244142d) and this cause the exception below:
> 
> ![image](https://user-images.githubusercontent.com/12233746/104374938-e722d200-5522-11eb-964a-7e86a7c24386.png)
> 
> I think the exception is normal (a little bit misleading with "denied" keyword) and you need a real device to test it.

Thanks for the answer!




I will try through testflight, please do not close the question, within 24 hours I will unsubscribe about the results in this branch,answer, and close =)

**Comment by juliansteenbakker** [comment]
Thank you @enricobenedos for testing. I didn't have an iOS device available right now to test it on. Tomorrow I'll see if i can check whether the device is a simulator and catch that exception.

**Comment by lacoste-sochi** [comment]
> Thank you @enricobenedos for testing. I didn't have an iOS device available right now to test it on. Tomorrow I'll see if i can check whether the device is a simulator and catch that exception.

Yes, indeed, everything works, checked through test flight. Just mac through a virtual machine running on Windows, no possible immediately on a real device =) you can close the topic! P.S. Question for dessert, why immediately front camera on iOS? =)

**Comment by lacoste-sochi** [comment]
The camera faces the default example from the front...thank you for your fruits to all!
