### ISSUE TITLE
[FEATURE] Support black QR Code background

### ISSUE THREAD

**Issue by enricobenedos** [juliuscanute/qr_code_scanner#220]
**Is your feature request related to a problem? Please describe.**
I'm facing a very annoying problem with a QR Code with black background. Scan works on iOS but not on Android.

**Describe the solution you'd like**
It will be beautiful to understand if it is an Android API limits or a bug in the package.

**Additional context**
These are the two test QR Code

![image](https://user-images.githubusercontent.com/12233746/104375570-dcb50800-5523-11eb-831e-e037bc5b3c73.png)

![image](https://user-images.githubusercontent.com/12233746/104375580-e0488f00-5523-11eb-903e-55bc3e1fe3e3.png)

**Comment by juliansteenbakker** [comment]
I'm almost certain this has to do with the way the ZXING framework on Android handles the qrcode reading and in order to fix that we would have to change to another framework. (#176)

**Comment by edwallk** [comment]
There's an update to barscanner that provides that functionality, https://github.com/dm77/barcodescanner/pull/265

**Comment by tar-xvf** [comment]
@juliansteenbakker
It's possible to have both an inverted and mixed (both inverted and normal) recognizer now using zxing (embedded). I tried fixing this flutter lib by adding the following to initBarcodeView in QRView.kt:

```
            barcodeView?.cameraSettings?.setScanInverted(true)
            barcodeView?.setDecoderFactory(DefaultDecoderFactory(null, null, null, 2))

```
The number 2 is the mixed recognizer.

You also need `import com.journeyapps.barcodescanner.DefaultDecoderFactory`

**Comment by juliansteenbakker** [comment]
I have released the first MLKit supported version, and it recognizes the QR code instantly. It's still an alpha release however i would suggest migrating to MLKit as soon as it reaches beta status.
