### ISSUE TITLE
Creating a custom QrScannerOverlayShape

### ISSUE THREAD

**Issue by Toolenaar** [juliuscanute/qr_code_scanner#224]
Hi I am trying to change the QRScannerOverlayShape so I just copied the base code to create my own custom shape. But when I use this custom shape, without any code changes just a simple copy to another file. It stops working and the entire view is no longer transparent. See screenshot.

This is on iOS

![IMG_0650](https://user-images.githubusercontent.com/5195563/104806458-06965500-57d8-11eb-83dd-73f0fe8651ea.PNG)

**Comment by juliansteenbakker** [comment]
Hello, can you show the code you are using to define a custom shape? I tried some values myself but couldn't reproduce this behaviour.
