### ISSUE TITLE
[BUG] result not showing in Text widget 

### ISSUE THREAD

**Issue by hiiumeshpatil** [juliuscanute/qr_code_scanner#225]
in console print message like code scanned in 8s
please help me how can i print result on Text widget
thanks

**Comment by ZahidTekbas** [comment]
Same here. It scans the barcode but does not show the result.

**Comment by ZahidTekbas** [comment]
I have tried the same exact functions which I used yesterday, and it worked today. Probably flutter clean and flutter pub get should be done before using the package.

**Comment by enricobenedos** [comment]
Hey @hiiumeshpatil,

I think is not a `qr_code_scanner` package issue. Can you please download the [example ](https://github.com/juliuscanute/qr_code_scanner/tree/master/example) attached to this repository and tell us if it works?
