### ISSUE TITLE
[FEATURE] disable key requirement

### ISSUE THREAD

**Issue by clragon** [juliuscanute/qr_code_scanner#226]
**Is your feature request related to a problem? Please describe.**
the `QRView` widget has a required key parameter. 
I do not use that key, therefore I would like to omit it.

**Describe the solution you'd like**
Remove the requirement for the key.

**Additional context**
Maybe use a default key in case none is given?

**Comment by juliansteenbakker** [comment]
Hello, the key is necessary for iOS in order to get the render context. We also can't provide a default global key from the plugin itself since it would be out of context, and we can only provide const values and `GlobalKey()` isn't constant.

**Comment by RaulUrtecho** [comment]
> Hello, the key is necessary for iOS in order to get the render context. We also can't provide a default global key from the plugin itself since it would be out of context, and we can only provide const values and `GlobalKey()` isn't constant.

I think this reason must be in your main example as a comment in the GlobalKey declaration.
