### ISSUE TITLE
[FEATURE] controller parameter

### ISSUE THREAD

**Issue by clragon** [juliuscanute/qr_code_scanner#228]
**Is your feature request related to a problem? Please describe.**
I am using this widget in a page view. when swiping into the page with the QR view inside, the page will update as soon as the camera preview is available (almost instantly) which will cancel the swipe and throw the user back to the page theyre on. this will repeat until a swipe is done twice in quick succession, because in that time the camera view is not deconstructed.

**Describe the solution you'd like**
It would be nice to instead of having a callback that passes the controller, the QrView could have a parameter that can be passed a controller.
This way, a global controller could be created and passed to the QrView everytime one is built. 
The controller could also be paused while the page isnt active, then resumed.
This could also lead to initializing the controller without showing the QrView, maybe showing a loading screen instead.
In general, this would allow more control over the view.

**Additional context**
One way of solving this issue is by making the scanner page be a keep alive page, but this leads to the camera and scanner being constantly active which is quite wasteful and will also lead to scans being done in the background. 

I do not actually know if pausing the controller and resuming it immediately when the page is loaded would solve the swipe cancel issue, as its kinda hard to test that and I do not know which part of the QrView is causing the page swipe cancel. however, having a global controller could enable only resuming the camera scanner when the page is fully swiped. 

If you happen to know a different solution to the swiping problem, I would greatly appreciate it, though regardless of the swiping problem, it would be quite nice to have a controller parameter.

**Comment by clragon** [comment]
I've just seen #206 and I guess this issue is kind of a duplicate of it.

**Comment by juliansteenbakker** [comment]
I can make it possible to declare and pass a global controller. However, due to the way that QRView embeds the camera view in a flutter application i think the only way to speed up the page swipe/slide is to delay the QRView from being loaded so it doesn't open the camera immediately. This can be done using a button or `Future.delayed()`.
