### ISSUE TITLE
[BUG] Scanned data stream buffer 

### ISSUE THREAD

**Issue by enricobenedos** [juliuscanute/qr_code_scanner#231]
**Describe the bug**
When you start listening to `scannedDataStream`, if in the transition between controller initialisation and `scannedDataStream` listening/subscribing the camera catch some qr codes/bar codes you will retrieve them at the subscription because they are buffered.

An example to be more clear:
```dart
void _onQRViewCreated(QRViewController controller) async {
    _controller = controller;
    
   //Here I'm waiting to the user to click 'OK'
    await _showMyDialog();

    _controller.scannedDataStream.listen(
      (scanData) async {
        print('QR scan result: ${scanData.code} (format: ${scanData.format})');
      },
    );
  }
```
If during the wait for the user to accept the dialog, the camera will find some qr codes, they will be buffered on the stream. This cause that the first scanned qr data returned by the listener is not the actual one but one of the oldest buffered during dialog wait.
 
I'm not sure this can be considered a bug but it is a very problematic behaviour in my opinion. Because it can happen that the user scanned QR Code is not the real one that it is scanning but an oldest one scanned during the transition.

A good idea can be to give to developers something like `await _controller.clearStream()` to execute before listening or something better like `await _controller.startScan()`. With `startScan()` we can be sure that `qr_code_scanner` library will start the scanning task when the developers are ready to start it. With this implementation we can subscribe to `scanData` but we will decide when start the real scanning task.

Hope I was clear,

Thanks

**Comment by enricobenedos** [comment]
Just to be more clear, I say that there is the `pauseCamera()` method that allows to pause bar code scanning, but it also stops the camera. In my minds the implementation of `startScan()`/`stopScan()` methods also provide a way to maintain camera active.

Anyway it seems that also this workaround does not works:
```dart
await _controller.pauseCamera();
await _showFirstStartQRDialog();
await _controller.resumeCamera();
```
`pauseCamera()` is ignored if then I show a popup dialog.

**Comment by juliansteenbakker** [comment]
I have investigated the feature of pausing the scanning but continuing the camera view. While this is possible in Android, i did not find a similar feature for iOS. The only thing that the framework allows me to do is freezing the capture, which is pausing the scanner and the cameraview.
