### ISSUE TITLE
[FEATURE]  Add a callback when a QR code is recognized

### ISSUE THREAD

**Issue by andosteinmetz** [juliuscanute/qr_code_scanner#232]
I'm trying to write a callback that executes as soon as a QR code is recognized. In React this might be handled by hooks, or in Vue by a watched property or a listener. This seems like it would be a common use case for a QR Code reader.  I'm new to Flutter and Dart, so perhaps there exists a construct for doing this already and I'm just not finding it in the documentation.

If such a mechanism exists, it might be helpful to include in the examples how this could be accomplished. If such a mechanism doesn't exist, I might consider an optional callback parameter that takes code to be executed when a QR code is recognized.

I tried to solve it by using `WidgetsBinding.instance.addPostFrameCallback((_)` in the build method like so:

```
  @override
  build(context){

    WidgetsBinding.instance.addPostFrameCallback((_) {
      if(result != null){
        controller.dispose(); // otherwise the following will run continuously
        Navigator.of(context).pushNamed(FPRoutes.confirm_scan);
      }
    });
...
```
but the problem I had was that if I didn't call `controller.dispose()` the function would be called continuously, and once I do call `dispose()`, the QR reader no longer works if I `pop()` back to the screen. Instead I need to `popUntil()` the preceding screen and `push()` the route containing the QR reader again to re-initialize the controller. 

Thanks in advance!

**Comment by clragon** [comment]
I think I might be misunderstanding your problem,
but just to make sure, have you looked at the example for this project?

it shows that you can subscribe to the QR scan stream with the controller:

`controller.scannedDataStream.listen(myCallback);`

**Comment by andosteinmetz** [comment]
Yes, the first thing I tried was something like: 

```
void _onQRViewCreated(QRViewController controller) {
    setState(() {
      this.controller = controller;
    });
    controller.scannedDataStream.listen((scanData) {
      if(scanData != null && scanData != result){
        setState(() {
          result = scanData;
        });
        Navigator.of(context).pushNamed(FPRoutes.confirm_scan);
      }
    });
  }
```

The problem was the same here: the callback was being called continuously before `result` was updated by `setState`, and thus pushing the `confirm_scan` route numerous times. 

I've also tried calling `controller.pauseCamera()` as soon as the `if` condition is met here but then it's not clear how to resume the camera when I `pop()` back to the this screen.

ex.
```
controller.scannedDataStream.listen((scanData) {
      if(scanData != null && scanData != result){
        controller.pauseCamera();
         ...
```
I still feel like I'm missing something obvious though.

**Comment by clragon** [comment]
I think I also ran into this problem;
You are comparing `scanData` and `result`, however, these are not the same object, which is why they do not return true with `==`, 
even if their contents might be the same. 

The way I solved this in my code is simply:

`scanData.code != result.value`

**Comment by andosteinmetz** [comment]
Thanks. That is helpful to know, but the problem I'm having isn't that the condition isn't being met, but that it's being met repeatedly, and pushing numerous (hundreds of) copies of the same route onto the `Navigator`'s stack.

**Comment by clragon** [comment]
that is odd, my code is very similar and this does not happen.
the condition stops right after the first call. I do not do this with a setstate but rather I am using a value notifier. 
maybe this fixes the race condition?

regardless of that, you could try deduping the calls, with a `Timer` of a couple hundred miliseconds or so?

```dart
Timer dedupe;

if(scanData != null && scanData != result) {
  if (dedupe != null) {
      dedupe.cancel();
  }
  dedupe = Timer(Duration(milliseconds: 100), () {
      setState(() {
        result = scanData;
      });
      Navigator.of(context).pushNamed(FPRoutes.confirm_scan);
  })
}
```

**Comment by andosteinmetz** [comment]
`ValueNotifier` was exactly what I was looking for.
And yes, you're totally right about the `code` property comparison rather than testing for object identity. I'd gotten my head a bit turned around.

I think additional confusion was being caused by testing with a sheet that had a number of QR codes close together, and that was causing the reader to switch between them.

Thanks!

**Comment by mnomanmemon** [comment]
Hi @andosteinmetz and @clragon, Can you please share the code you have come up with which resolves your issue. 
I am stuck at that how this condition is met first time. For me, it is always gives me false and didn't return true first time.
My code is:

```
Barcode result;
QRViewController controller;

void _onQRViewCreated(QRViewController controller) {
    this.controller = controller;
    controller.scannedDataStream.listen((scanData) {
        if(scanData.code != result.code) { 
        // never comes here
        }
    });
}
```

**Comment by clragon** [comment]
HI @mnomanmemon,
does your code even run without exceptions?

from what I can see, `result` is never initialized, 
so trying to access it's `.code` property should lead to an exception.

the fix for that would be to use a null-aware operator `result?.code`

**Comment by mnomanmemon** [comment]
> HI @mnomanmemon,
> does your code even run without exceptions?
> 
> from what I can see, `result` is never initialized,
> so trying to access it's `.code` property should lead to an exception.
> 
> the fix for that would be to use a null-aware operator `result?.code`

Nop. I am not getting any exception but I am rather not able to get into the condition because of that uninitialized result. What can I do then?
