### ISSUE TITLE
[BUG] Scan area doesn't update when cutOutBottomOffset is set

### ISSUE THREAD

**Issue by mekery** [juliuscanute/qr_code_scanner#235]
**Describe the bug**
When cutOutBottomOffset is set, the effective scan area is still stay in the center instead of update with the offset.
Reproduced in the official example.

**Flutter information**
Flutter 1.22.5

**Device (please complete the following information):**
 - Device: Huawei Mate 10 pro, Huawei Mate 30 pro

**Comment by robpal** [comment]
same issue on iOS devices.

**Comment by mekery** [comment]
Still doesn't work in 0.4.0, reproduced in the official example.

**Comment by GyuriMajercsik** [comment]
Same here. The scan area is still centered when the cutOutBottomOffset is provided.
