### ISSUE TITLE
[BUG] cameraFacing doesn't work on Android

### ISSUE THREAD

**Issue by c0c4i** [juliuscanute/qr_code_scanner#237]
I updated to 0.3.0 and I'm using cameraFacing.

On iOS it works great but on android is still facing back.

For now I'm using
```dart
if (Platform.isAndroid) controller.flipCamera();
```

**Comment by enricobenedos** [comment]
Hey @c0c4i,
can you please try to await the `flipCamera()` and tell us if your application stuck on this instruction or simply not really execute it?

Can you please also provide a sample project and print a `flutter doctor -v` including the current simulator API version?

**Comment by juliansteenbakker** [comment]
This is fixed on master and will be released in V0.3.1
