### ISSUE TITLE
How can I set the the screen area for scanning barcodes 

### ISSUE THREAD

**Issue by 0FengQiang0** [juliuscanute/qr_code_scanner#249]
I set the cutOutSize 200 and cutOutBottomOffset 100,but the section of the screen that barcodes can be scanned in has not changed .

here is my code:

    return QRView(
      key: qrKey,
      cameraFacing: CameraFacing.back,
      onQRViewCreated: _onQRViewCreated,
      formatsAllowed: [BarcodeFormat.qrcode],
      overlay: QrScannerOverlayShape(
          borderColor: Color(0xFF279DF1),
          borderRadius: 0,
          borderLength: 30,
          borderWidth: 6,
          cutOutSize: 200,
          cutOutBottomOffset: 100,
      ),
    );

I have found some useful information in MTBBarcodeScanner:

To limit the section of the screen that barcodes can be scanned in, set the scanRect property on MTBBarcodeScanner inside the didStartScanning callback block. See MTBAdvancedExampleViewController for a working example of this.
__weak MTBAdvancedExampleViewController *weakSelf = self;
self.scanner.didStartScanningBlock = ^{
    weakSelf.scanner.scanRect = weakSelf.viewOfInterest.frame;
};

**Comment by 0FengQiang0** [comment]
Here is my code in   build fuction
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: PreferredSize(
        child: AppBar(
          title: Text(
              'qr scan',
              style: TextStyle(fontWeight: FontWeight.w400)
          ),
          backgroundColor: Color(0xFF319FEE),
          leading: Center(child: IconButton(icon: Image.asset('images/icon_appbar_back.png',fit: BoxFit.cover,), onPressed: (){Navigator.of(context).pop();}),),
          automaticallyImplyLeading: false,
        ),
        preferredSize: Size.fromHeight(44),
      ),
      body: _buildQrView(context),
    );
  }

  Widget _buildQrView(BuildContext context) {

    return QRView(
      key: qrKey,
      cameraFacing: CameraFacing.back,
      onQRViewCreated: _onQRViewCreated,
      formatsAllowed: [BarcodeFormat.qrcode],
      overlay: QrScannerOverlayShape(
          borderColor: Color(0xFF279DF1),
          borderRadius: 0,
          borderLength: 30,
          borderWidth: 6,
          cutOutSize: 200,
          cutOutBottomOffset: 100,
      ),
    );
  }

**Comment by juliansteenbakker** [comment]
Hello, i just tested this with version 0.3.2 and i'm only able to scan the code within the qrscanneroverlayshape. Anything outside wont scan. Which device, OS version and qr_code_scanner version are you using?

**Comment by 0FengQiang0** [comment]
It may be related to the AppBar I set up .Here is the code:
`@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: PreferredSize(
        child: AppBar(
          title: Text(
              'BarCode scan',
              style: TextStyle(fontWeight: FontWeight.w400)
          ),
          backgroundColor: Color(0xFF319FEE),
          leading: Center(child: IconButton(icon: Image.asset('images/icon_appbar_back.png',fit: BoxFit.cover,), onPressed: (){Navigator.of(context).pop();}),),
          automaticallyImplyLeading: false,
        ),
        preferredSize: Size.fromHeight(44),
      ),
      body: _buildQrView(context),
    );
  }`

**Comment by 0FengQiang0** [comment]
It may be related to the AppBar I set up .

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: PreferredSize(
        child: AppBar(
          title: Text(
              'BarCode scan',
              style: TextStyle(fontWeight: FontWeight.w400)
          ),
          backgroundColor: Color(0xFF319FEE),
          leading: Center(child: IconButton(icon: Image.asset('images/icon_appbar_back.png',fit: BoxFit.cover,), onPressed: (){Navigator.of(context).pop();}),),
          automaticallyImplyLeading: false,
        ),
        preferredSize: Size.fromHeight(44),
      ),
      body: _buildQrView(context),
    );
  }

**Comment by 0FengQiang0** [comment]
I am using version 0.3.1 ,my device is iPhone 12

**Comment by 0FengQiang0** [comment]
I am using version 0.3.1 ,my device is iPhone 12
