### ISSUE TITLE
[BUG] 0.3.2 cannot access camera on first run (0.3.0 still works)

### ISSUE THREAD

**Issue by tiloc** [juliuscanute/qr_code_scanner#251]
**Describe the bug**
When I am newly installing my app which is using qr_code_scanner 0.3.2 I am first getting an exception in the native code about missing camera permission. At that time a dialog pops up, asking for permission to use the camera. I grant the permission. I am presented with a screen with no preview, camera is "front", even though I initialized with "back". When I force stop the app and run again it works as expected.

When I downgrade to qr_code_scanner 0.3.0 everything works as it used to.

**Flutter information**
Always provide the output of `flutter doctor -v` as it is needed in order to know on which Flutter versions the bug exists in.
flutter doctor -v
[✓] Flutter (Channel beta, 1.26.0-17.3.pre, on Mac OS X 10.13.6 17G14042 darwin-x64, locale en-US)
    • Flutter version 1.26.0-17.3.pre at /Users/tilo/Tools/flutter
    • Framework revision 4b50ca7f7f (35 hours ago), 2021-02-04 19:44:27 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tilo/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /Users/tilo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Xcode 10.1.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • Pixel 5 (mobile) • 08081FDD4002T6 • android-arm64  • Android 11 (API 30)
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 88.0.4324.146

! Doctor found issues in 2 categories.

**Device (please complete the following information):**
 - Device: Google Pixel 5
 - OS: Android 11

**Screenshots**

**Additional context**
Stack trace:
W/CameraBase(25490): An error occurred while connecting to camera 1: Status(-8, EX_SERVICE_SPECIFIC): '1: validateClientPermissionsLocked:1165: Caller "com.legentix.flutter_healthcare" (PID 10465, UID 25490) cannot open camera "1" without camera permission'
E/CameraInstance(25490): Failed to open camera
E/CameraInstance(25490): java.lang.RuntimeException: Fail to connect to camera service
E/CameraInstance(25490): 	at android.hardware.Camera.<init>(Camera.java:557)
E/CameraInstance(25490): 	at android.hardware.Camera.open(Camera.java:402)
E/CameraInstance(25490): 	at com.google.zxing.client.android.camera.open.OpenCameraInterface.open(OpenCameraInterface.java:83)
E/CameraInstance(25490): 	at com.journeyapps.barcodescanner.camera.CameraManager.open(CameraManager.java:142)
E/CameraInstance(25490): 	at com.journeyapps.barcodescanner.camera.CameraInstance$1.run(CameraInstance.java:200)
E/CameraInstance(25490): 	at android.os.Handler.handleCallback(Handler.java:938)
E/CameraInstance(25490): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/CameraInstance(25490): 	at android.os.Looper.loop(Looper.java:223)
E/CameraInstance(25490): 	at android.os.HandlerThread.run(HandlerThread.java:67)
D/CameraPreview(25490): pause()
D/CameraInstance(25490): Closing camera
W/FragmentActivity(25490): **Activity result delivered for unknown Fragment.**
D/CameraPreview(25490): resume()
D/CameraInstance(25490): Opening camera
D/CameraInstance(25490): Configuring camera

**Comment by tiloc** [comment]
FWIW: Since I am using local_auth plugin, my MainActivity is a FlutterFragmentActivity, not a FlutterActivity.

**Comment by juliansteenbakker** [comment]
I have updated the iOS code in the following branch: camera-facing-not-correct-ios. Can you please try that branch and check if it resolves this issue? I have tested it with an iPad Air 2 running iOS 14.4 and an iPhone 5S running iOS 12.5.1 and i couldn't reproduce this bug anymore.

**Comment by tiloc** [comment]
So just that I understand correctly: You are assuming that your fix for iOS is fixing my bug on Android?

**Comment by juliansteenbakker** [comment]
My bad, i linked the wrong issue!

**Comment by juliansteenbakker** [comment]
I was only able to reproduce this behaviour by removing `android.enableDexingArtifactTransform=false` from the android gradle.properties file. Are you sure you've added it?

**Comment by tiloc** [comment]
I had not, because the README only advises to add it in case of a very particular exception, which I was experiencing. I added it now and rebuilt. Unfortunately, the result is the same. So unfortunately I will have to downgrade to 0.3.0 again.

**Comment by juliansteenbakker** [comment]
Thanks for reporting. Since there are other problems reported with 0.3.2 as well i indeed suggest to use 0.3.0 for now. I will compare the two tomorrow and figure out how we can solve all problems
