### ISSUE TITLE
[BUG] Passing in BarcodeFormat.upcA as an allowed format causes the iOS app to crash.

### ISSUE THREAD

**Issue by danielgubler** [juliuscanute/qr_code_scanner#260]
**Describe the bug**
Passing in BarcodeFormat.upcA as an allowed format causes the iOS app to crash.
When looking into it, it's because upcA isn't listed as a barcode format here:
https://github.com/juliuscanute/qr_code_scanner/blob/master/ios/Classes/QRView.swift#L18-L30
And the unsafe unwrapping is throwing an exception here: https://github.com/juliuscanute/qr_code_scanner/blob/master/ios/Classes/QRView.swift#L119

And according to Apple's documentation, it looks like we should be using ean13 instead: https://developer.apple.com/documentation/avfoundation/avmetadataobject/objecttype/1618807-ean13

After implementing the library, we spent a while trying to figure out what the crash was, so hopefully this helps anyone else who comes across this problem.

**Flutter information**
```
Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E266 darwin-x64, locale en-US)
    • Flutter version 1.22.5 at /Users/danielgubler/tools/flutter
    • Framework revision 7891006299 (9 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/danielgubler/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/danielgubler/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • iPhone 6s (mobile) • B1B48E74-CCC0-4773-BDC6-655D9BE27BDB • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

! Doctor found issues in 2 categories.
```

**Device (please complete the following information):**
 - Device: iPhone 6s, 7 and 12 pro (at least, but I assume all iPhones)
 - OS: iOS 12.0 and 14.4 (at least, but I assume more than that as well)

**Comment by juliansteenbakker** [comment]
Just released v0.3.5
