### ISSUE TITLE
[BUG] Wrong barcode value scanned

### ISSUE THREAD

**Issue by nambv** [juliuscanute/qr_code_scanner#264]
**Describe the bug**
The lib giving me wrong scanData for some barcodes

**Flutter information**
flutter doctor -v                                                                 ✔
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en)
    • Flutter version 1.22.6 at /Users/nambuivu/flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nambuivu/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/nambuivu/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Live (mobile) • AHB00098571 • android-arm64 • Android 10 (API **29)**

**Device (please complete the following information):**
 - Device: [Android Live]
 - OS: [Android 9]

**Screenshots**
<img width="431" alt="Screen Shot 2021-02-15 at 14 41 55" src="https://user-images.githubusercontent.com/13296355/107918282-f4a4ff00-6f9b-11eb-81c4-25e089d97d30.png">

**Additional context**
The scanData.code is ```3667185059475```, not correct

**Comment by luanssd** [comment]
Barcode images encoding is not standard.
![Screen Shot 2021-02-15 at 21 54 00](https://user-images.githubusercontent.com/5753204/107961341-597e4a80-6fd8-11eb-8816-299576dec781.png)

**Comment by nambv** [comment]
@juliuscanute  @luanssd but this app still scan the barcode correctly:

https://play.google.com/store/apps/details?id=com.arara.q

**Comment by srikanth-burra** [comment]
Any updates on this. I am also facing mis-read issues.

**Comment by juliansteenbakker** [comment]
This has to do with encoding support on current framework. This will improve with MLKit which is currently under development. Please see #176 for more info.
