### ISSUE TITLE
[BUG] Unable to scan other color qr code

### ISSUE THREAD

**Issue by ttb-inc** [juliuscanute/qr_code_scanner#270]
**Describe the bug**
I have a problem on Android. No problem on iPhone.

**Flutter information**
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale ko-KR)
    • Flutter version 1.22.6 at /Users/master/Desktop/work/flutter_sdk/flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/master/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/master/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.43.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (2 available)
    • SM G611K (mobile)                              • android-arm • Android 9 (API 28)

**Device (please complete the following information):**
 - Device: Samsung Galaxy
 - OS: Android 9

**Screenshots**
![sample_qr_code](https://user-images.githubusercontent.com/59724931/109109119-16f70380-7778-11eb-9924-865adfc1260f.png)

**Additional context**

**Comment by enricobenedos** [comment]
Duplicated of #220
