### ISSUE TITLE
[BUG]  error when i want to run app

### ISSUE THREAD

**Issue by bestheroforever** [juliuscanute/qr_code_scanner#274]
java.lang.RuntimeException: Duplicate class com.google.zxing.BarcodeFormat found in modules core-3.3.0.jar (com.google.zxing:core:3.3.0) and core_3.0.1.jar (com.github.leyan95:android-zxingLibrary:0.1.2-PRE)

**Comment by manhlh** [comment]
you can try it, work for me:
Android/app/build.gradle
`configurations {
compile.exclude group: 'com.google.zxing'
}`
