### ISSUE TITLE
Failed to build iOS app

### ISSUE THREAD

**Issue by ridwan-aswan** [juliuscanute/qr_code_scanner#275]
**I have an error like this? how to solve it.**

Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           44.3s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    mkdir -p /Volumes/Ridwan's MacBook Pro/Apps Project/Flutter/Stock Kelapa/stock_kelapa/build/ios/Debug-iphonesimulator/Runner.app/Frameworks
    rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Volumes/Ridwan's MacBook Pro/Apps Project/Flutter/Stock Kelapa/stock_kelapa/build/ios/Debug-iphonesimulator/MTBBarcodeScanner/MTBBarcodeScanner.framework" "/Volumes/Ridwan's MacBook Pro/Apps Project/Flutter/Stock Kelapa/stock_kelapa/build/ios/Debug-iphonesimulator/Runner.app/Frameworks"
    building file list ... done
    MTBBarcodeScanner.framework/
    MTBBarcodeScanner.framework/Info.plist
    MTBBarcodeScanner.framework/MTBBarcodeScanner
    MTBBarcodeScanner.framework/_CodeSignature/
    MTBBarcodeScanner.framework/_CodeSignature/CodeResources

    sent 123718 bytes  received 98 bytes  247632.00 bytes/sec
    total size is 123339  speedup is 1.00
    Code Signing /Volumes/Ridwan's MacBook Pro/Apps Project/Flutter/Stock Kelapa/stock_kelapa/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/MTBBarcodeScanner.framework with Identity -
    /usr/bin/codesign --force --sign -  --preserve-metadata=identifier,entitlements '/Volumes/Ridwan's MacBook Pro/Apps Project/Flutter/Stock Kelapa/stock_kelapa/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/MTBBarcodeScanner.framework'
    /Volumes/Ridwan's MacBook Pro/Apps Project/Flutter/Stock Kelapa/stock_kelapa/ios/Pods/Target Support Files/Pods-Runner/Pods-Runner-frameworks.sh: eval: line 173: unexpected EOF while looking for matching `''
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.

**Comment by juliansteenbakker** [comment]
The simulator is not supported. Can you try using a real device?
