### ISSUE TITLE
file not found  #import "qr_code_scnner/ar_code_scanner-Swift.h"[BUG] 

### ISSUE THREAD

**Issue by HelmsManLi** [juliuscanute/qr_code_scanner#276]

**Comment by juliansteenbakker** [comment]
Maybe a typo, but your title states: `qr_code_scnner/ar_code_scanner-Swift.h` which should be `qr_code_scnner/qr_code_scanner-Swift.h`

**Comment by HelmsManLi** [comment]
yes,i was wrong,but I mean missing this file plus

**Comment by juliansteenbakker** [comment]
Try the following:

1. Remove example/ios/Flutter/Flutter.podspec: rm example/ios/Flutter/Flutter.podspec
2. flutter clean
3. Run your app again.

source flutter/flutter#70895 (comment)
