### ISSUE TITLE
Migration to null-safety

### ISSUE THREAD

**Issue by blazern** [juliuscanute/qr_code_scanner#278]
Hi!

Your cool project hasn't migrated to null safety yet: https://dart.dev/null-safety/migration-guide
That makes it a little bit more complicated to use :)

I downloaded the source code and ran the migration tool to see how much of work has to be done - it doesn't seem like too much, but there are a few subtle places which I think should be resolved by the main maintainer.

**Comment by juliansteenbakker** [comment]
I created the following pull-request #290. Can someone please check my code as verification?

**Comment by juliansteenbakker** [comment]
Released 0.4.0
