### ISSUE TITLE
How to input a specific barcode type before a scan?

### ISSUE THREAD

**Issue by trungdn0401** [juliuscanute/qr_code_scanner#279]
Hi,

Is there any way to scan a specific barcode type only? I want to scan only one barcode if I have a multi-barcode image at the same time!?

Many thank!

**Comment by sondo65** [comment]
![Screen Shot 2021-03-11 at 10 23 42](https://user-images.githubusercontent.com/27793997/110730986-0fddf400-8254-11eb-88e0-190cfdc015f6.png)

Let use "formatsAllowed" in QRView widget
