### ISSUE TITLE
[BUG] It has black screen while scan qr code

### ISSUE THREAD

**Issue by aleeyang2015** [juliuscanute/qr_code_scanner#281]
![157864752_179795603909980_4857878165554842274_n](https://user-images.githubusercontent.com/68886893/110757119-9a871900-827d-11eb-91b9-245f8cde4dbb.jpg)

**Comment by Sword-Smith** [comment]
I also have this problem.

**Comment by juliansteenbakker** [comment]
I think this is a duplicate of #277
