### ISSUE TITLE
[BUG] iOS crash when navigating away from scanner page before screen fully built

### ISSUE THREAD

**Issue by mdsherwood** [juliuscanute/qr_code_scanner#283]
**Describe the bug**
When I navigate quickly away from the screen displaying the scanner, before it's fully loaded then in iOS, the app crashes with error as seen in Xcode:

'NSInternalInconsistencyException', reason: 'Scan rect cannot be set when not (yet) scanning. You may want to set it within didStartScanningBlock.'

This does not happen in Android.

**Flutter information**
qr_code_scanner version 0.3.5

**Device (please complete the following information):**
 - Device: iPhone6
 - OS: iOS 12.5.1

**Additional context**
I am using a BottomNavigationBar and loading the page as part of a BottomNavigationBarItem. If you click a BottomNavigationBarItem to go to the scanner page and then quickly click another BottomNavigationBarItem a crash occurs. If the scanner page is given time to build before navigating away then there is no issue.

**Comment by mdsherwood** [comment]
Just a further note. I simplified the scanner page code quite a bit so there's less to build and the problem still seems to happen where the app freezes but then after pushing the buttons in the BottomNavigationBar a few times it seems to unfreeze and carry on

Thanks for this useful plugin

**Comment by seth35us** [comment]
I have attached an example project to replicate the bug, based on the GitHub example from this project. The first bottomNavigationBar item is the scanning page, and the others are just a container with a text widget. It only takes a few times clicking between the scanning page and the other widgets for the example to freeze. 

[example.zip](https://github.com/juliuscanute/qr_code_scanner/files/6604617/example.zip)

**Comment by juliansteenbakker** [comment]
Can you please try again with the MLKit scanner. I think this will solve the problem.

**Comment by seth35us** [comment]
The MLKit Scanner seemed to solve the problem. Looking forward to checking it out when complete! Thanks for your work on this.

**Comment by kodyds** [comment]
MLKit Scanner somehow doesn't match my demand. I would stick with this library. Can anyone suggest a way to actually avoid this issue?

**Comment by shang1219178163** [comment]
same
