### ISSUE TITLE
not reading ean-code when phone(camera) is not align with the barcode 

### ISSUE THREAD

**Issue by neo-xy** [juliuscanute/qr_code_scanner#284]
**When phone (camera) is not at the same angle as the barcode, scanner is not able to read code. (guessing something wrong with orientaion)
os: Android,
version: 0.4.0-nullsafety.0

is it know issue?
 **

**Comment by juliansteenbakker** [comment]
Hello, this issue is known and has to do with the framework being used. I am still working on a version which doesn't have this issue. It will be updated here: #176
