### ISSUE TITLE
How to scan single code?[FEATURE] 

### ISSUE THREAD

**Issue by A-Jawad** [juliuscanute/qr_code_scanner#287]
I did not find the Q&A section.
How to scan single code, (not a stream)?

**Comment by smofe** [comment]
You can deactivate the Scanner after receiving the first scan.
`controller.pauseCamera();`

I don't think there is a specific "single scan" option.

**Comment by juliansteenbakker** [comment]
Please see https://github.com/juliuscanute/qr_code_scanner/issues/11#issuecomment-747321010
