### ISSUE TITLE
[BUG] Camera preview randomly "breaks" out of its bounding container

### ISSUE THREAD

**Issue by FickleLife** [juliuscanute/qr_code_scanner#288]
Firstly, thank you for the GREAT plugin. Now on to the issue :)

**Describe the bug**
In my app, when I flick between bottom nav items between screens which don't have a QRView and one screen which does, the camera video feed will "break" out of its container (see screenshots and the video below). This appears to happen randomly, I haven't been able to get a solid reproduction so I am posting here in the hope someone else has come across this and has a clue to a solution. 

In the video you can see I can switch between "Lists" and "Speedy scan" 100 items before seeing it. 

**Additional context**
- I've seen this on iOS only so far, I have not seen it on Android. 
- It seems to occur on any iOS version, old and latest.
- I have noticed this happening more on initial load of the camera when the user is asked for permission - when they click yes it appears to "break" out more often than not. Some sort of initialisation error here? 
- When the preview has "broken" out of it's bounds, it cannot scan anything.
- It occurred on older versions of Flutter (I was on 1.22 but just upgraded to 2.0.2). 

**Screenshots**
Normal - as it should be:

<img src="https://user-images.githubusercontent.com/844005/111405177-2688bd00-8724-11eb-80d4-d0aaa45f6264.PNG" width="414" height="896">

Random bug: Image zooms and breaks out of the Container area

<img src="https://user-images.githubusercontent.com/844005/111405258-44eeb880-8724-11eb-9f9a-ddbe6ad65477.PNG" width="414" height="896">

Video (bug happens at 36 second mark)
https://user-images.githubusercontent.com/844005/111407108-7b7a0280-8727-11eb-8bf0-53ba6fc225bc.mp4

**Flutter information**
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-GB)
    • Flutter version 2.0.2 at /Applications/flutter
    • Framework revision 8962f6dc68 (5 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/alexblack/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio 4.2 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Pixel 2 (mobile) • FA7B51A02445              • android-arm64  • Android 11 (API 30)
    • Alex (mobile)    • 00008020-000615061144002E • ios            • iOS 14.4.1
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 89.0.4389.82

**Device (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 14.4.1

**Comment by FickleLife** [comment]
It has something to do with `overlay` param. Remove the overlay, and it doesn't break out of its bounding box.

**Comment by FickleLife** [comment]
I have had look into the QR scanner code and can see in the following method

```
/// Updates the view dimensions for iOS.
  static Future<void> updateDimensions(GlobalKey key, MethodChannel channel,
      {QrScannerOverlayShape overlay}) async {
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      // Add small delay to ensure the renderbox is loaded
      await Future.delayed(Duration(milliseconds: 100));
      final RenderBox renderBox = key.currentContext.findRenderObject();
      try {
        await channel.invokeMethod('setDimensions', {
          'width': renderBox.size.width,
          'height': renderBox.size.height,
          'scanArea': overlay?.cutOutSize ?? 0,
          'scanAreaOffset': overlay?.cutOutBottomOffset ?? 0
        });
      } on PlatformException catch (e) {
        throw CameraException(e.code, e.message);
      }
    }
  }
```

The `renderbox.size.width` and `renderbox.size.height` has the correct values in it, but on occasion the video view "pops" out of the window as illustrated above... about to dig into into the methodChannel call and see what's happening there (the channel name is 'net.touchcapture.qr.flutterqr/qrview_41')

**Comment by FickleLife** [comment]
Looks like it's something to do with `MTBBarcodeScanner` as the code in Dart and Swift is exactly the same when the `MTBBarcodeScanner` library is called, whether the issue presents itself or not. Flutter recognises touches to items underneath the preview window, so Flutter doesn't seem to be aware of the video overlay extended over the UI. Since `MTBBarcodeScanner` is not maintained anymore, and there's doesn't appear to be another scanning library for flutter that supports preview windows (non full screen), iOS and Android that does not use `MTBBarcodeScanner`. 

While I'd like to stick to `qr_code_scanner`, I'm stuck. Can anyone suggest a different library that I may not have been able to find?

**Comment by juliansteenbakker** [comment]
Thank you very much for your extended debugging. If it is indeed due to `MTBBarcodeScanner` then we need to wait till #176  is done and released. I am still working on this however it seems like it's very difficult to integrate this new way of scanning in this current library. I am still figuring out what the best options are and i will try to post another update on this in that ticket.

**Comment by FickleLife** [comment]
Thanks @juliansteenbakker for the update, sounds great.

**Comment by juliansteenbakker** [comment]
I have released the first alpha version with MLKit support. Please keep in mind that the class names can change until it reaches beta status.
