### ISSUE TITLE
[BUG]  cannot build ios because The Swift pod `qr_code_scanner` depends upon `MTBBarcodeScanner`

### ISSUE THREAD

**Issue by Nabouste** [juliuscanute/qr_code_scanner#291]
**Describe the bug**
i run this apps using emulator,
and showing 
`The Swift pod `qr_code_scanner` depends upon `MTBBarcodeScanner`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.`

![image](https://user-images.githubusercontent.com/29367624/112254938-f5fcd200-8c93-11eb-867a-4973d549c217.png)

**Comment by 5115191** [comment]
same issue

**Comment by martesabt** [comment]
I got same problem with version 4.0.0 and after adding this lines on ios/Podfile:

```
target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  use_modular_headers! # new line
  use_frameworks! # new line
end
```
