### ISSUE TITLE
[BUG] Handling permission denied to access the camera

### ISSUE THREAD

**Issue by wahyu-handayani** [juliuscanute/qr_code_scanner#295]
I am using the version of qr_code_scanner: ^0.3.5 and doing test in simulator, so when I start to hit the button to scan the qr code, I always get
```
Exception has occurred.
CameraException (CameraException(cameraPermission, Permission denied to access the camera))
```
I have added this in info.plist:
```
<key>NSCameraUsageDescription</key>
<string>This app requires read and write permission from user</string>
```
I had been trying to use a package that relate for using camera permission (image picker), so when I use image picker package, starting by clicking the button to start camera then pop up dialog shows to ask permission to access camera and when I press to allow access, another pop up shows that say camera not available cause I am using simulator. So, instead of getting error exception for Permission denied to access the camera, is there a way to get pop up to ask permission access for camera or pop up information that camera is not available? I also have checked the status permission to access camera and it says permission is granted

**Comment by juliansteenbakker** [comment]
Hello, please note that this package does not support the simulator because the camera is not supported by the iOS simulator. Can you please check again on a real device and see if it has the same behaviour?

**Comment by wahyu-handayani** [comment]
@juliansteenbakker thank you for the response, I don't have ios device for now. Today or tomorrow I will try to check it and let you know the result

**Comment by wahyu-handayani** [comment]
@juliansteenbakker I have tried in ios device and it runs well, thank you very much for the quick response
