### ISSUE TITLE
[BUG] Infinite Re-Render Camera View

### ISSUE THREAD

**Issue by edsulaiman** [juliuscanute/qr_code_scanner#297]
**Describe the bug**
Changing Flutter hook value on onQRViewCreated will make qr_code_scanner infinite render

<details>
<summary>See Code</summary>
<br>

``` dart
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:qr_code_scanner/qr_code_scanner.dart';

class QrScannerPage extends HookWidget {
  const QrScannerPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final GlobalKey qrKey = GlobalKey(debugLabel: 'QR');
    final render = useState(0);

    return Material(
      child: Column(
        children: [
          Expanded(
            flex: 5,
            child: QRView(
              key: qrKey,
              overlay: QrScannerOverlayShape(
                borderRadius: 8,
                borderWidth: 4,
              ),
              onQRViewCreated: (QRViewController ctrl) {
                render.value++;
              },
            ),
          ),
          Expanded(
            child: Center(
              child: Text('${render.value}'),
            ),
          ),
        ],
      ),
    );
  }
}
```
</details>

**  Flutter information **
<details>
<summary>See Flutter information</summary>
<br>
Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.906], locale en-ID)
    • Flutter version 2.0.3 at C:\flutter
    • Framework revision 4d7946a68d (13 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\...
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\...
    • Java binary at: C:\...
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\...
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.54.3)
    • VS Code at C:\...
    • Flutter extension version 3.20.0

[√] Connected device (1 available)
    • RMX1821 (mobile) • EEAMIZJRLNVCNREI • android-arm64 • Android 10 (API 29)

• No issues found!
**Device (please complete the following information):**
 - Device: Realme 3
 - OS: Android 10
</details>

**Screenshots**
![bug](https://user-images.githubusercontent.com/52323183/113153826-a9039780-9261-11eb-8752-ea8219bb2fd9.gif)
Number at bottom shows the current render count

**Comment by clragon** [comment]
have you tried putting the qr view into its own state-ful/less widget?

**Comment by edsulaiman** [comment]
> have you tried putting the qr view into its own state-ful/less widget?

yes i did, i found this problem occurs if on onQrViewCreated i change the value of ValueNotifier(flutter_hooks) or StateController(hooks_riverpod)
