### ISSUE TITLE
[BUG] How to scan QR code with special contents.

### ISSUE THREAD

**Issue by nicodumdum** [juliuscanute/qr_code_scanner#298]
**Describe the bug**
When I try to scan a special QR code using my Xiaomi Mi A1, it seems it has problems deciphering some of the contents.
```txt
Scanned QR code data { format: BarcodeFormat.qrcode, code: ZX8OUo��� }
```
When I scanned using my Samsung Galaxy S20 FE built-in scan QR code feature within the default camera app it resulted with:
```txt
ZX8OUoڿӀ
```
When I scanned using Google Lens for both devices it resulted with:
```text
 ZX8OUoÚÿ“
```
I'm not sure how to properly scan the special QR code. Although my Samsung is giving me results without the question marks, I'm not sure if that's accurate too.

I hope you can help. Thanks.

**Flutter information**
```txt
PS C:\Users\Nico> flutter doctor -v
[✓] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.867], locale en-PH)
    • Flutter version 1.22.6 at C:\src\flutter
    • Framework revision 9b2d32b605 (10 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Nico\sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\Nico\sdk
    • Java binary at: C:\Users\Nico\AppData\Local\Android\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Nico\AppData\Local\Android\android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.55.0)
    • VS Code at C:\Users\Nico\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Device (please complete the following information):**
 - qr_code_scanner: ^0.4.0
 - Device: Xiaomi Mi A3
 - OS: Android 11

**Screenshots**

QR code scan result with my flutter app using qr_code_scanner.
![Screenshot_20210401-191855](https://user-images.githubusercontent.com/1650987/113287793-a320bb80-9320-11eb-8036-850cfca39cac.png)

QR code scan result using my Samsung Galaxy S20 FE built-in scan QR code feature within the default camera app.
![Screenshot_20210401-192051_Camera](https://user-images.githubusercontent.com/1650987/113287803-a6b44280-9320-11eb-977d-f2c802f4cac9.jpg)

QR code scan result using Google Lens
![Screenshot_20210401-200314](https://user-images.githubusercontent.com/1650987/113291331-73c07d80-9325-11eb-9a5d-b9a5855a6459.png)

**Additional context**

Special QR code
![ZX8OU](https://user-images.githubusercontent.com/1650987/113288016-f2ff8280-9320-11eb-80d7-6c7d4db6c32a.png)

**Comment by juliansteenbakker** [comment]
This is due to the underlying framework and can't be fixed with this package. Please see #491
