### ISSUE TITLE
[BUG] Camera viewfinder is black on Samsung Xcover5

### ISSUE THREAD

**Issue by tar-xvf** [juliuscanute/qr_code_scanner#308]
**Describe the bug**
The camera viewfinder in the example app is black on Samsung XCover 5.

(Have tested on a Google Pixel 3a with Android 11, and it works fine there.)

Running the zxing-android-embedded sample app works fine. It's just when using it through this Flutter plugin there is an issue with a black/non-working viewfinder.

**Flutter information**
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-SE)
    • Flutter version 2.0.3 at /Users/mlq/opt/flutter
    • Framework revision 4d7946a68d (5 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
    • Android SDK at /usr/local/android-sdk-mac_86-r05
    • Platform android-S, build-tools 31.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • SM G525F (mobile) • XXXXXXXXXX • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 90.0.4430.85

• No issues found!

**Device (please complete the following information):**
 - Device: Samsung XCover 5 Enterprise (SM G525F)
 - OS: Android 11 (API 30)

**Screenshots**

**Additional context**

**Comment by tar-xvf** [comment]
I finally found the issue. In QRView.kt BarcodeView is instantiated with default attributes.
This means that the BarCodeview will set textureView to true. This causes the Xcover5 camera preview to fail to stream to screen.

The zxing-android-embedded example app uses an AttributeSet to instantiate via DecoratedBarcodeView and is not using textureView mode.

Adding barcodeView?.setUseTextureView(false) in initBarCodeView in QTView.kt fixes the issue.

**Comment by fede1295** [comment]
@tar-xvf  with your fix i have this error:
.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.5.1/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt: (206, 56): Unresolved reference: CenterCropStrategy

**Comment by tar-xvf** [comment]
@fede1295 I'm sorry, I forgot to include the import. Add:

`import com.journeyapps.barcodescanner.camera.CenterCropStrategy`

at the top
