### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by tagirahmad** [juliuscanute/qr_code_scanner#309]
**Describe the bug**

My app scans qr code, then navigates to new screen with parsed data. 
But, it doesn't navigate properly: camera is still scanning the code. 
I've tried to implement something like this, but I think it's not so good idea
Plus to all, WillPopScope doesn't allow to navigate back with swipe on ios

**1st screen**

```
void onQRViewCreated(
      QRViewController controller,
    ) {
      this.controller.controller = controller;
      controller.scannedDataStream.listen((scanData) {
        this.controller.result = scanData;
        controller.pauseCamera();
        showDialog(
            context: _scaffoldKey.currentContext,
            builder: (context) {
              Future.delayed(Duration(seconds: 1), () {
                Navigator.of(context).pop();
              });
              return AlertDialog(
                title: Center(
                  child: Text(
                    Strings.processing,
                    style: Theme.of(context)
                        .textTheme
                        .subtitle1
                        .copyWith(fontWeight: FontWeight.w400),
                  ),
                ),
                content: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    CircularProgressIndicator(),
                  ],
                ),
              );
            }).then((value) {
          Get.toNamed(Routes.SCANNED_DATA, arguments: scanData);
        });
      });
    }
```

**2nd screen**

```
Widget build(BuildContext context) {
    return WillPopScope(
      // ignore: missing_return
      onWillPop: () async {
        // Get.back();
        QrcodePageController.to.controller.resumeCamera();
        return true;
      },
      child: Scaffold(
        appBar: AppBar(
            elevation: 0,
            backgroundColor: Colors.white,
            leading: IconButton(
              icon: Icon(Icons.arrow_back),
              color: Colors.black,
              tooltip: Strings.back,
              onPressed: () {
                QrcodePageController.to.controller.resumeCamera();
                Get.back();
              },
            )),
        body: SafeArea()
        )
       );
```

**Flutter information**
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.0.1 at /Users/tagirahmadeev/development/flutter
    • Framework revision c5a4b4029c (8 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tagirahmadeev/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.1.4
    • Dart plugin version 203.7759

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114

• No issues found!

**Device (please complete the following information):**
 - Device: Poco x3 nfc, iphone 8 simulator
 - OS: android 10, ios 14

**Comment by rocboronat** [comment]
It would be great that you update the title of the issue.

**Comment by juliansteenbakker** [comment]
Please try stopCamera() or use the new MLKit scanner.
