### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by LobaAndrade** [juliuscanute/qr_code_scanner#310]
In run debug mode with android, camera crash after a single scan with my device attached (in this case Huawei P30 Pro). I'm totally new in programming, so please be patient. 

[✓] Flutter (Channel stable, 2.0.5, on macOS 11.3 20E232 darwin-x64, locale it-IT)
    • Flutter version 2.0.5 at /Users/cocobuk/Downloads/flutter
    • Framework revision adc687823a (2 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/cocobuk/Library/Android/sdk
    • Platform android-S, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • VOG L29 (mobile)           • 22X7N19319007056                     • android-arm64  • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • 99F8157D-6757-4304-9E5F-49F04D11304E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 90.0.4430.93
**Screenshots**

This is the console verbose log: 

D/DecoderThread( 3957): Found barcode in 22 ms
I/DecorView[]( 3957):  old windowMode:1 new windoMode:1
W/libEGL  ( 3957): EGLNativeWindowType 0x78557c5010 disconnect failed
D/mali_winsys( 3957): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/CameraPreview( 3957): resume()
W/CameraPreview( 3957): initCamera called twice
D/SensorManager( 3957): 0x7831ff5760 addFd fd=153
D/CameraPreview( 3957): resume()
W/CameraPreview( 3957): initCamera called twice
D/SensorManager( 3957): 0x7831ff5760 addFd fd=151
D/CameraPreview( 3957): resume()
W/CameraPreview( 3957): initCamera called twice
D/SensorManager( 3957): 0x7831ff5760 addFd fd=151
I/DecorView[]( 3957):  old windowMode:0 new windoMode:1
D/InputEventReceiver( 3957): dispatchInputInterval 1000000
I/ViewRootImpl( 3957): dispatchDetachedFromWindow in doDie
W/libEGL  ( 3957): EGLNativeWindowType 0x7855dd1290 disconnect failed

**Comment by rocboronat** [comment]
It would be great that you update the title of the issue.

**Comment by juliansteenbakker** [comment]
There is a bug in Flutter framework causing this issue on Huawei and Xiaomi devices.
> It seems as this is an issue with Huawei or Xiaomi devices and Flutter native view. I can find multiple issues on Flutter Github page regarding this error. I think that you wont have this issue when using MLKit, which is currently under development. Please see #176 for more info. I'm closing this for now since the bug is related to Flutter framework.
