### ISSUE TITLE
Problem with EAN13 format on ios environment

### ISSUE THREAD

**Issue by srikanth-burra** [juliuscanute/qr_code_scanner#312]
**Describe the bug**
in IOS environment, specially for the format BarcodeFromat.eam13, an additional 0 is being appended at the beginning for code which is retrieved. I haven't tested it for other formats. It works fine on android environment.

**Comment by rocboronat** [comment]
It would be great that you update the title of the issue.

**Comment by juliansteenbakker** [comment]
I have tried several EAN13 codes and only the one beginning with a 0 show a 0. 

I have tried the following:
![image](https://user-images.githubusercontent.com/20091319/120505864-acccab00-c3c5-11eb-9ccd-379e962c821c.png)
