### ISSUE TITLE
[BUG][Ios] CameraException permission Denied

### ISSUE THREAD

**Issue by huberrom** [juliuscanute/qr_code_scanner#314]
**Describe the bug**
I'm using the latest version of qr_code_scanner, and it works perfectly on Android.
But when I try to deny the permission on ios, instead of calling my method `onPermissionSet: _onPermissionSet,`, nothing append and I have the following log :  
`CameraException(cameraPermission, Permission denied to access the camera)`

I'm using a physical device, so I don't know why it's not working, any help can is useful 🙏 

**Flutter information**
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale
  fr-FR)
  • Flutter version 2.0.6 at ****
  • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
  • Engine revision 05e680e202
  • Dart version 2.12.3

**Device (please complete the following information):**
 [✓] Connected device (1 available)
  • iPhone Xs Max (mobile) • ios • iOS 14.4

**Comment by huberrom** [comment]
If it helps, I have this error to be exact :
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: CameraException(cameraPermission, Permission denied to access the camera)
#0   QRViewController._startScan (package:qr_code_scanner/src/qr_code_scanner.dart:229:7)
<asynchronous suspension>

**Comment by FantaMagier** [comment]
There is a new Version merged about this problem. https://github.com/juliuscanute/qr_code_scanner/pull/307 Try this.

**Comment by huberrom** [comment]
Thank you @FantaMagier, it works 🙏

**Comment by huberrom** [comment]
Quick question, do you know if there will be a new tag soon including this merged branch ?
I currently use : 
```
qr_code_scanner:
    git:
      url: git://github.com/juliuscanute/qr_code_scanner
      ref: master

```
but Android is not happy with this
