### ISSUE TITLE
not working any more. 

### ISSUE THREAD

**Issue by matiazar** [juliuscanute/qr_code_scanner#318]
I have created a new project. copied the main example.
changed minSdkVersion to 20

and i have this error

Launching lib\main.dart on sdk gphone x86 arm in debug mode...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:54746/Ll_mx4dQaJ8=/ws
W/Gralloc4(27568): allocator 3.x is not supported
E/ample.qr_reade(27568): [SurfaceTexture-0-27568-0] attachToContext: invalid current EGLDisplay
E/flutter (27568): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(49)] java.lang.RuntimeException: Error during attachToGLContext (see logcat for details)
E/flutter (27568): 	at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:295)
E/flutter (27568): 	at io.flutter.embedding.engine.renderer.SurfaceTextureWrapper.attachToGLContext(SurfaceTextureWrapper.java:55)
E/flutter (27568):
F/flutter (27568): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1242)] Check failed: CheckException(env).
F/libc    (27568): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 27598 (1.raster), pid 27568 (ample.qr_reader)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86_arm/generic_x86_arm:11/RSR1.201013.001/6903271:userdebug/dev-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2021-05-28 13:16:14-0300
pid: 27568, tid: 27598, name: 1.raster  >>> com.example.qr_reader <<<
uid: 10157
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1242)] Check failed: CheckException(env).
'
    eax 00000000  ebx 00006bb0  ecx 00006bce  edx 00000006
    edi e965481e  esi bc011490
    ebp ed3ddb90  esp bc011438  eip ed3ddb99
backtrace:
      #00 pc 00000b99  [vdso] (__kernel_vsyscall+9)
      #01 pc 0005ad68  /apex/com.android.runtime/lib/bionic/libc.so (syscall+40) (BuildId: 6e3a0180fa6637b68c0d181c343e6806)
      #02 pc 00076511  /apex/com.android.runtime/lib/bionic/libc.so (abort+209) (BuildId: 6e3a0180fa6637b68c0d181c343e6806)
      #03 pc 01207eda  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #04 pc 01235225  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #05 pc 01213fc3  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #06 pc 01206838  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #07 pc 0120661f  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #08 pc 0122c789  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #09 pc 01229506  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #10 pc 0122cb57  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #11 pc 01229506  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #12 pc 0122b768  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #13 pc 01229506  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #14 pc 0122cb57  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #15 pc 01229506  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #16 pc 0122cb57  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #17 pc 01229506  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #18 pc 0122cb57  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #19 pc 01229506  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #20 pc 012294b5  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #21 pc 0122a380  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #22 pc 01226e3b  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #23 pc 0127d9b3  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #24 pc 0127e59f  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #25 pc 0127f436  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #26 pc 0122e50b  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #27 pc 0127de9e  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #28 pc 0127dc1a  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #29 pc 0128d260  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #30 pc 0123341b  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #31 pc 01236213  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #32 pc 01236124  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #33 pc 0123c8fa  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #34 pc 0123c928  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #35 pc 00019337  /system/lib/libutils.so (android::SimpleLooperCallback::handleEvent(int, int, void*)+39) (BuildId: ab4be013cda31e8c45d48aa23a89d0f8)
      #36 pc 0001a367  /system/lib/libutils.so (android::Looper::pollInner(int)+1127) (BuildId: ab4be013cda31e8c45d48aa23a89d0f8)
      #37 pc 00019e96  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+118) (BuildId: ab4be013cda31e8c45d48aa23a89d0f8)
      #38 pc 000133f5  /system/lib/libandroid.so (ALooper_pollOnce+101) (BuildId: f98006d4d736575082b552ff24b66f6c)
      #39 pc 0123c83d  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #40 pc 012360d2  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #41 pc 01235c02  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #42 pc 01239cdf  /data/app/~~9O9jOjKrNyTZqFj9_u9SWA==/com.example.qr_reader-lgtIjIYmatfDfbE33pipNA==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #43 pc 000e6974  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+100) (BuildId: 6e3a0180fa6637b68c0d181c343e6806)
      #44 pc 00078567  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+71) (BuildId: 6e3a0180fa6637b68c0d181c343e6806)
Lost connection to device.
Exited (sigterm)

**Comment by matiazar** [comment]
fixed. it was because the vscode runs the app with 
--enable-software-rendering

removing that returns my app to life!

**Comment by mbsim08** [comment]
how do you remove it?
