### ISSUE TITLE
Can't recognized QR Codes in different colours

### ISSUE THREAD

**Issue by glaand** [juliuscanute/qr_code_scanner#32]

**Comment by silveira-alfredo** [comment]
This issue has been solved? I need this update for my project, phone camera can read qr but de plugin don't.

**Comment by dspicher** [comment]
Just tested this, the example app recognizes most colored QR codes fine. In any case, the package uses `zxing` for Android and `MTBBarcodeScanner` for iOS more or less directly, please post the issue there if you keep running into issues.
