### ISSUE TITLE
Error when building the Android app

### ISSUE THREAD

**Issue by rocboronat** [juliuscanute/qr_code_scanner#325]
I just passed from master (referencing to `git: url: git://github.com/juliuscanute/qr_code_scanner.git`) to version 0.5.1. Then, I tried 0.5.0, 0.4.0... with the same result.

Now, when I try to build the app, it crashes. I'm building it for Android, by the way.

```
Launching lib\main.dart on Moto G 4 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Development\SDKs\Flutter\.pub-cache\hosted\pub.dartlang.org\qr_code_scanner-0.5.1\android\build.gradle' line: 38

* What went wrong:
A problem occurred evaluating project ':qr_code_scanner'.
> Could not find method buildFeatures() for arguments [build_bfauykicst2jfm3m5pc7t2mbx$_run_closure2$_closure7@57d6db4b] on object of type com.android.build.gradle.LibraryExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Flutter information**
```
G:\Projects\docplanner-phone-flutter>flutter doctor -v
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.2.1 at C:\Development\SDKs\Flutter
    • Framework revision 02c026b03c (5 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Development\SDKs\Android
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Development\SDKs\Android
    • ANDROID_SDK_ROOT = C:\Development\SDKs\Android
    • Java binary at: C:\Development\IDEs\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Development\IDEs\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Development\IDEs\IntelliJ IDEA\IntelliJ IDEA Community Edition 2020.3.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 203.8173

[√] Connected device (4 available)
    • Moto G 4 (mobile)           • ZY223LWH82    • android-arm    • Android 7.0 (API 24)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 91.0.864.37

• No issues found!
```

Thanks a lot! :·)

**Comment by FantaMagier** [comment]
Same problem. I deleted the pub-cache and the complete .gradle folder but it doen't helpd

**Comment by dankawka** [comment]
@rocboronat @FantaMagier 
You have to upgrade Gradle, Kotlin and Kotlin Gradle Plugin:

1. In `android/build.gradle` bump `ext.kotlin_version = '1.3.50'` to `ext.kotlin_version = '1.5.10'`
2. In `android/build.gradle` bump `classpath 'com.android.tools.build:gradle:3.5.0'` to `classpath 'com.android.tools.build:gradle:4.2.0'`
3. In `android/gradle/wrapper/gradle-wrapper.properties` bump `distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip` to `distributionUrl=https\://services.gradle.org/distributions/gradle-6.9-all.zip`

**Comment by rocboronat** [comment]
Oh! I'll try! Thanks 😊

**Comment by DeepakRattan** [comment]
> @rocboronat @FantaMagier You have to upgrade Gradle, Kotlin and Kotlin Gradle Plugin:
> 
> 1. In `android/build.gradle` bump `ext.kotlin_version = '1.3.50'` to `ext.kotlin_version = '1.5.10'`
> 2. In `android/build.gradle` bump `classpath 'com.android.tools.build:gradle:3.5.0'` to `classpath 'com.android.tools.build:gradle:4.2.0'`
> 3. In `android/gradle/wrapper/gradle-wrapper.properties` bump `distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip` to `distributionUrl=https\://services.gradle.org/distributions/gradle-6.9-all.zip`

Thanks a lot . Worked like a charm ...

**Comment by harryandroiddev** [comment]
run flutter downgrade

**Comment by AbdurRehman-coder** [comment]
> @rocboronat @FantaMagier You have to upgrade Gradle, Kotlin and Kotlin Gradle Plugin:
> 
> 1. In `android/build.gradle` bump `ext.kotlin_version = '1.3.50'` to `ext.kotlin_version = '1.5.10'`
> 2. In `android/build.gradle` bump `classpath 'com.android.tools.build:gradle:3.5.0'` to `classpath 'com.android.tools.build:gradle:4.2.0'`
> 3. In `android/gradle/wrapper/gradle-wrapper.properties` bump `distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip` to `distributionUrl=https\://services.gradle.org/distributions/gradle-6.9-all.zip`

Thanks it solved my issue
