### ISSUE TITLE
Barcode Misread

### ISSUE THREAD

**Issue by srikanth-burra** [juliuscanute/qr_code_scanner#328]
In both iOS and android platform, when we are scanning a particular barcode, in every 20 out of 100 instances, there is a barcode misread. This will be auto-corrected by the scanner, if allow the stream to flow in continuously. In such cases mis-read appears for a split second. But then, this issue is serious because, we never know which barcode can be skipped.

**Comment by juliansteenbakker** [comment]
Possible duplicate of #264. Please see https://github.com/juliuscanute/qr_code_scanner/issues/264#issuecomment-853102298
