### ISSUE TITLE
[BUG] V0.5.1 Does not build.

### ISSUE THREAD

**Issue by surister** [juliuscanute/qr_code_scanner#329]
**Describe the bug**
V0.5.1 Doesn't compile.

**Flutter information**
I was using V0.4.0 and was working fine, I did `pub upgrade` to V.0.5.1 and it does not build anymore.

Relevant error message:
![image](https://user-images.githubusercontent.com/37985796/120677372-4a43df80-c497-11eb-9d34-ae02c53aee13.png)
Whole error trace: https://pastebin.com/dH16N10R

The stack trace mentions two cache folders.
`flutter/.pub-cache`
`.gradle/caches`

I have tried removing both of those caches, same result.
I have tried doing `flutter clean`
and combined both.

`flutter doctor`
```
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
[✓] Connected device (2 available)
• No issues found!
```

Version V.0.4.0 Works fine though If i specify it in the pubspec.yml.

**Comment by seel-channel** [comment]
I have the same bug

**Comment by edwallk** [comment]
Try changing the kotlin version in Android/build.gradle to 1.4.32, e.g. set it to `ext.kotlin_version = '1.4.32'` and do a `flutter clean` which fixed the problem for me.

**Comment by juliansteenbakker** [comment]
I've updated both gradle and kotlin to the latest version so make sure you update your project too. I think thats the problem most people are encountering right now.

**Comment by edwallk** [comment]
Would it be worthwhile to upgrade `com.google.zxing` to the latest version as well?

**Comment by surister** [comment]
This indeed fixed my Issue, thanks!

**Comment by hypnotox** [comment]
In my case it didn't work with `ext.kotlin_version = '1.4.32'`. 

So i bumped it to `ext.kotlin_version = '1.5.10'`, the same as scanner is using, and `classpath 'com.android.tools.build:gradle:4.0.0'`, which fixed the issue.

**Comment by orosznyet** [comment]
I've added this new version to a fresh project so this will come up for other people too.
Adding this thread to the readme as a known issue would help others for sure.
