### ISSUE TITLE
Example seems outdated

### ISSUE THREAD

**Issue by bagintz** [juliuscanute/qr_code_scanner#33]
The example has public access to the channel and controller, but it appears those were removed last month:

```
QRViewController updated

- MethodChannel is now handled inside the controller
- Removed controller init, pass globalKey as required parameter
- Controller now returns a stream of data
- Updated README.md + example```

Is this true, can you update the example?

**Comment by MrBhatt** [comment]
The code in example is out of sync with library as pointed by @bagintz above

**Comment by Zyzto** [comment]
@bagintz  can you write simple example, I am new to dart.

**Comment by dspicher** [comment]
Hi @bagintz .
Both the example/main.dart and the one from the README.md should run fine on current master. Can you confirm?

**Comment by dspicher** [comment]
Closing for now, please reopen if you keep running into this issue.
