### ISSUE TITLE
[FEATURE] Update Readme file for Gradle upgrade

### ISSUE THREAD

**Issue by FantaMagier** [juliuscanute/qr_code_scanner#332]
**Is your feature request related to a problem? Please describe.**
A lot of people struggle with the gradle upgrade after upgrading to version 0.5.1. This is the solution:  https://github.com/juliuscanute/qr_code_scanner/issues/325 I think it is good idea to update the readme file that the user has to update Gradle, Kotlin  and the Kotlin Gradle Plugin.

**Comment by FantaMagier** [comment]
I opened a PR: https://github.com/juliuscanute/qr_code_scanner/pull/333

**Comment by juliansteenbakker** [comment]
Merged, thanks for your contribution.
