### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by TaranenkoDenis** [juliuscanute/qr_code_scanner#337]
**Describe the bug**
Cannot build project (only Android, with iOS everything fine) with this library due to exception:

```
Build file '/Users/denis/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.5.1/android/build.gradle' line: 27

A problem occurred evaluating project ':qr_code_scanner'.
> No signature of method: build_37km4q34l5488kird20w3ez11.android() is applicable for argument types: (build_37km4q34l5488kird20w3ez11$_run_closure2) values: [build_37km4q34l5488kird20w3ez11$_run_closure2@5bc8a7f1]
```

**Flutter information**
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (2 available)

P.S. I tried to run flutter doctor --android-licenses, but got exception.

**Comment by juliansteenbakker** [comment]
Can you please check and see if you've updated the kotlin plugins for your android project:

> Android Integration
> In order to use this plugin, please update the Gradle, Kotlin and Kotlin Gradle Plugin:
> 
> In android/build.gradle change ext.kotlin_version = '1.3.50' to ext.kotlin_version = '1.5.10'
> 
> In android/build.gradle change classpath 'com.android.tools.build:gradle:3.5.0' to classpath 'com.android.tools.build:gradle:4.2.0'
> 
> In android/gradle/wrapper/gradle-wrapper.properties change distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip to distributionUrl=https\://services.gradle.org/distributions/gradle-6.9-all.zip

**Comment by TaranenkoDenis** [comment]
Sorry, my mistake.
