### ISSUE TITLE
[BUG] Error occurs when getting qr data / can't build it in sync

### ISSUE THREAD

**Issue by nneemmrr** [juliuscanute/qr_code_scanner#339]
**Describe the bug**
can't obtain QR data
this is the error which appears:
D/DecoderThread(28128): Found barcode in 48 ms
I/flutter (28128): Instance of 'Barcode'
E/flutter (28128): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: RangeError: Value not in range: 5
E/flutter (28128): #0      _StringBase.substring (dart:core-patch/string_patch.dart:399:7)
E/flutter (28128): #1      _ScanQRState._onQRViewCreated.<anonymous closure> (package:unigate_app/screens/ScanScreen/scan_screen.dart:128:35)
E/flutter (28128): #2      _ScanQRState._onQRViewCreated.<anonymous closure> (package:unigate_app/screens/ScanScreen/scan_screen.dart:125:41)
E/flutter (28128): #3      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (28128): #4      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (28128): #5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (28128): #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (28128): #7      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (28128): #8      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
E/flutter (28128): #9      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
E/flutter (28128): #10     _rootRun (dart:async/zone.dart:1346:47)
E/flutter (28128): #11     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (28128): #12     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (28128): #13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (28128): #14     _rootRun (dart:async/zone.dart:1354:13)
E/flutter (28128): #15     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (28128): #16     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (28128): #17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (28128): #18     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (28128): #19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

**Flutter information**
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-arm, locale
    en-EG)
    • Flutter version 2.2.1 at /Users/omarelnemr/flutter
    • Framework revision 02c026b03c (2 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/omarelnemr/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

**Device (please complete the following information):**
 - Device: Iphone 7
 - OS: [iOS 14.5]
- Device: Samsung Galaxy note 8
- OS: [Android 9 Pie]

**Additional context**
this is my code:
```
`
class ScanQR extends StatefulWidget {
  @override
  _ScanQRState createState() => _ScanQRState();
}



class _ScanQRState extends State<ScanQR> {
  //vars

  final GlobalKey qrKey = GlobalKey(debugLabel: 'QR');
  String text = 'Scan';
  QRViewController? _controller;
  // Barcode? result;



  @override
  void initState() {
    checkConnectivity(context);

    super.initState();
  }


  // hot restart
  void reassemble() {
    super.reassemble();

    if (Platform.isAndroid) {
      _controller!.pauseCamera();
    }
    _controller!.resumeCamera();
  }





  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(
          backgroundColor: darkBlueColor,
          title: Text(
            'Scan',
            style: TextStyle(color: whiteColor, fontSize: 24),
          ),
        ),


        body: Center(
          child: Column(
            children: [
              Expanded(flex: 5, child: buildQrView(context, qrKey)),
              Expanded(
                flex: 1,
                child: Center(
                  child: Text(
                    text,
                    style: TextStyle(
                      color: Colors.blue,
                      fontWeight: FontWeight.w700,
                      fontSize: 32,
                    ),
                  ),
                ),
              )
            ],
          ),
        ),

      );









  Widget buildQrView(BuildContext context, Key qrKey) {
    // For this example we check how width or tall the device is and change the scanArea and overlay accordingly.
    var scanArea = (MediaQuery
        .of(context)
        .size
        .width < 400 ||
        MediaQuery
            .of(context)
            .size
            .height < 400)
        ? 300.0
        : 300.0;
    // To ensure the Scanner view is properly sizes after rotation
    // we need to listen for Flutter SizeChanged notification and update controller
    return QRView(
      key: qrKey,
      onQRViewCreated: _onQRViewCreated,
      overlay: QrScannerOverlayShape(
          borderColor: Color(0xFFFFA502),
          borderRadius: 5,
          borderLength: 20,
          borderWidth: 20,
          cutOutSize: scanArea),
    );
  }


  void _onQRViewCreated(QRViewController controller) async {
    String value = '';


    this._controller = controller;
    //listening to scanned data as a stream and printing error on error
    controller.scannedDataStream.listen((scanData) async {
      print(scanData);

      String getter=scanData.code.substring(0, 5);
      value = await get('uuid');
      if (scanData.code == value) {
        setState(() {
          text = 'Success';
        });

        saveAttendance(value, context);

      } else if (scanData.code == ''|| scanData.code!=value)

       setState(() {
         text = "Scan Again";
       });

    }, cancelOnError: true);
  }




  @override
  void dispose() {
    _controller?.dispose();

    super.dispose();
  }

}
`
```

**Comment by nneemmrr** [comment]
The problem that _onQRViewCreated can't be async function

**Comment by juliansteenbakker** [comment]
The error states that you are trying to get the first 5 characters of a string, but that string isn't 5 characters long

`String getter=scanData.code.substring(0, 5);`

`E/flutter (28128): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: RangeError: Value not in range: 5`

You should first check if the code is equal or longer than 5 characters and only then get the substring like this:
```dart
var getter = '';
if (scanData.code.length >= 5) {
    getter=scanData.code.substring(0, 5);
  }
```
