### ISSUE TITLE
iOS wrong dimension after orientation change

### ISSUE THREAD

**Issue by aabegg** [juliuscanute/qr_code_scanner#34]
I used the example of the plugin for testing purposes.

https://github.com/juliuscanute/qr_code_scanner/blob/master/example/lib/main.dart

I have modified the main.dart file as follows:

```
...
children: <Widget>[
          Expanded(
            child: Center(
              child: SizedBox(
                width: 300.0,
                height: 200.0,
                child: QRView(
                  key: qrKey,
                  onQRViewCreated: _onQRViewCreated,
                ),
              ),
            ),
            flex: 4,
          ),
          Expanded(
...
```

After that I noticed that the camera preview is centered as desired with a width of 300.0 and a height of 200.0 when starting the app. If I rotate the device (iPad mini) from portrait to landscape or vice versa the camera preview becomes twice as big and overflows the SizedBox.

If in the file qr_code_scanner.dart on line 56 the width fix is set to 300.0 and the height fix is set to 200.0 everything works as desired!

**Comment by jjjachyty** [comment]
+1 iOS first open camera

**Comment by alexshikov** [comment]
Having the same issue. @aabegg have you found a workaround?
