### ISSUE TITLE
[BUG]   compilation error

### ISSUE THREAD

**Issue by prabhunath111** [juliuscanute/qr_code_scanner#352]
Launching lib\main.dart on Mi A1 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\prabhunt\Downloads\flutter_windows_2.0.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\qr_code_scanner-0.5.1\android\build.gradle' line: 38

* What went wrong:
A problem occurred evaluating project ':qr_code_scanner'.
> Could not find method buildFeatures() for arguments [build_ecf862dyf8kswht2u375ys8fj$_run_closure2$_closure7@288b22e] on object of type com.android.build.gradle.LibraryExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by juliansteenbakker** [comment]
Please see #329

**Comment by prabhunath111** [comment]
Thanks 😊
