### ISSUE TITLE
Can't build appbundle release - version 0.5.1 [BUG] 

### ISSUE THREAD

**Issue by ThanhPhungTien** [juliuscanute/qr_code_scanner#354]
**Describe the bug**

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Build file '/Users/apple/work/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.5.1/android/build.gradle' line: 27
                                                                        
* What went wrong:                                                      
A problem occurred evaluating project ':qr_code_scanner'.               
> No signature of method: build_3kg386owkzr2wqtqyp0h4erpj.android() is applicable for argument types: (build_3kg386owkzr2wqtqyp0h4erpj$_run_closure2) values: [build_3kg386owkzr2wqtqyp0h4erpj$_run_closure2@38a5d673]
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 1s         

**Flutter information**

Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (3 weeks ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
[✓] VS Code (version 1.57.1)
[✓] Connected device (2 available)

**Device :**
 - OS: Android

**Comment by zlshames** [comment]
I am also receiving this bug on Flutter v2.2.1:
```
Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Build file '/home/zach/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.5.1/android/build.gradle' line: 29
                                                                        
* What went wrong:                                                      
A problem occurred evaluating project ':qr_code_scanner'.               
> Could not get unknown property 'buildFeatures' for object of type com.android.build.gradle.LibraryExtension.
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 1s                                                      
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                    2,368ms
Gradle task assembleRelease failed with exit code 1

**Comment by juliansteenbakker** [comment]
Please update gradle.
In android/build.gradle bump ext.kotlin_version = '1.3.50' to ext.kotlin_version = '1.5.10'

In android/build.gradle bump classpath 'com.android.tools.build:gradle:3.5.0' to classpath 'com.android.tools.build:gradle:4.2.0'

In android/gradle/wrapper/gradle-wrapper.properties bump distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip to distributionUrl=https\://services.gradle.org/distributions/gradle-6.9-all.zip

**Comment by zlshames** [comment]
Already ahead of you :) I had to set the kotlin version to `1.5.10` as well as set the gradle dependency version to `4.2.1`. Lastly, I had  to edit my `gradle-wrapper.properties` and update my `distributionUrl` to use `gradle-6.7.1`

**Comment by ThanhPhungTien** [comment]
Thanks everyone.  <3
