### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by yoyo89757001** [juliuscanute/qr_code_scanner#358]
Android crash![image](https://user-images.githubusercontent.com/31086765/124415065-9d56ce00-dd86-11eb-9a37-a940dea97e43.png)

**Comment by yoyo89757001** [comment]
Debugging with Flutter will not report an error. They pack up and they crash

**Comment by yoyo89757001** [comment]
![image](https://user-images.githubusercontent.com/31086765/124415296-279f3200-dd87-11eb-93eb-7a634b2a1f1b.png)

**Comment by juliansteenbakker** [comment]
It looks like the code is minified. Are you running the app in production mode?

**Comment by yoyo89757001** [comment]
> It looks like the code is minified. Are you running the app in production mode?

Debug mode does not run error, but after packaging error

**Comment by juliansteenbakker** [comment]
Can you please try this: https://github.com/juliuscanute/qr_code_scanner/issues/330#issuecomment-854403607

**Comment by juliansteenbakker** [comment]
Closed due to no reaction.
