### ISSUE TITLE
[BUG] Unable to run on Android device with version 0.5.0 but working fine with 0.4.0

### ISSUE THREAD

**Issue by muhammadmateen027** [juliuscanute/qr_code_scanner#362]
**Describe the bug**
Unable to compile the app for android while using `version 0.5.0` but its app successfully compiles with version 0.4.0.

**Flutter information**
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/24449076/125434779-7c1ed000-3953-4138-b7eb-a4a81b6cc554.png">

**Device (please complete the following information):**
 - Device: Huawei Nova 5t(Android version 10, EMUI version 11.0.0)
 - OS: iOS macOS Big Sur (version 11.0.1)

**Screenshots**
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/24449076/125435033-042e5f73-62ff-4b95-b0b0-9a789cddc1ad.png">

**Additional context**
None.

**Comment by juliansteenbakker** [comment]
Please follow these instructions: https://github.com/juliuscanute/qr_code_scanner/issues/354#issuecomment-872542642
