### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Nik653** [juliuscanute/qr_code_scanner#363]
I/art     ( 6165): Rejecting re-init on previously-failed class java.lang.Class<com.journeyapps.barcodescanner.DecoderResultPointCallback>
I/art     ( 6165): Rejecting re-init on previously-failed class java.lang.Class<com.journeyapps.barcodescanner.DecoderResultPointCallback>
I/art     ( 6165): Rejecting re-init on previously-failed class java.lang.Class<com.journeyapps.barcodescanner.Decoder>
I/art     ( 6165): Rejecting re-init on previously-failed class java.lang.Class<com.journeyapps.barcodescanner.Decoder>
I/art     ( 6165): Rejecting re-init on previously-failed class java.lang.Class<com.journeyapps.barcodescanner.Decoder>
I/art     ( 6165): Rejecting re-init on previously-failed class java.lang.Class<com.journeyapps.barcodescanner.Decoder>
I/art     ( 6165): Rejecting re-init on previously-failed class java.lang.Class<com.journeyapps.barcodescanner.Decoder>
D/PhoneWindow( 6165): DEBUG_SYSTEMUI:origin statusbar style
D/PhoneWindow( 6165): DEBUG_SYSTEMUI:windowDrawsFlag set
D/PhoneWindow( 6165): DEBUG_SYSTEMUI:IconColor=1
D/PhoneWindow( 6165): DEBUG_SYSTEMUI:StatusBarColor final set ff000000
D/CameraPreview( 6165): resume()
D/CameraInstance( 6165): Opening camera
D/SensorManager( 6165): open file /sys/networktype/networktype error
D/SensorManager( 6165): sensorCTSV isCtsVerifier false
D/SensorManager( 6165): sensorCTSV isCtsVerifier false
D/SensorManager( 6165): sensorCTSV isCtsVerifier false
D/SensorManager( 6165): isMicroMsg: package is = com.session.doctor
V/Camera  ( 6165): sendOpenCameraBroadCast()
V/Camera  ( 6165): isNormalCamera packageName = com.session.doctor
V/Camera  ( 6165): sendOpenCameraBroadCast isNormalCamera = true
D/Camera  ( 6165): closeFlashlightService package name com.session.doctor
D/CameraInstance( 6165): Configuring camera
I/CameraManager( 6165): Camera Display Orientation: 90
I/CameraManager( 6165): Initial camera parameters: ae-bracket-hdr=Off;ae-bracket-hdr-values=Off,AE-Bracket;af-bracket=af-bracket-off;af-bracket-values=af-bracket-off,af-bracket-on;antibanding=auto;antibanding-values=off,60hz,50hz,auto;auto-exposure=frame-average;auto-exposure-lock=false;auto-exposure-lock-supported=true;auto-exposure-values=frame-average,center-weighted,spot-metering,center-weighted,spot-metering-adv,center-weighted-adv;auto-hdr-supported=true;auto-whitebalance-lock=false;auto-whitebalance-lock-supported=true;avtimer=disable;brightness-step=1;cache-video-buffers=disable;camera-mode=0;cds-mode-values=off,on,auto;chroma-flash=chroma-flash-off;chroma-flash-values=chroma-flash-off,chroma-flash-on;contrast=5;contrast-step=1;denoise=denoise-on;denoise-values=denoise-off,denoise-on;dis=disable;dis-values=enable,disable;effect=none;effect-values=none,mono,negative,solarize,sepia,posterize,whiteboard,blackboard,aqua,emboss,sketch,neon;exposure-compensation=0;exposure-compensation-step=0.1;face-detection=off;face-detection-values=off,on;flash-mode=off;flash-mode-values=off,auto,on,torch;flip-mode-values=off,flip-v,flip-h,flip-vh;focal-length=2.94;focus-areas=(0, 0, 0, 0, 0);focus-distances=Infinity,Infinity,Infinity;focus-mode=auto;focus-mode-values=auto,infinity,fixed,macro,continuous-video,continuous-picture,manual;hdr-mode=hdr-mode-multiframe;hdr-mode-values=hdr-mode-multiframe;hdr-need-1x=false;hdr-need-1x-values=false,true;hfr-size-values=720x480;histogram=disable;histogram-values=enable,disable;horizontal-view-angle=62.7;instant-aec-values=;instant-capture-values=;internal-restart=true;iso=auto;iso-values=auto,ISO_HJR,ISO100,ISO200,ISO400,ISO800,ISO1600,ISO3200;jpeg-quality=85;jpeg-thumbnail-height=154;jpeg-thumbnail-quality=85;jpeg-thumbnail-size-values=256x154,240x160,320x320,320x240,256x144,240x144,176x144,240x320,144x176,0x0;jpeg-thumbnail-width=256;lensshade=enable;lensshade-values=enable,disable;long-shot=off;longshot-supported=true;luma-adaptation=3;manual-exposure-modes=off,exp-time-priority,iso-priority,user-setting;manual-focus-modes=off,scale-mode,diopter-mode;manual-wb-modes=off,color-temperature,rbgb-gains;max-brightness=6;max-contrast=10;max-exposure-compensation=40;max-exposure-time=1000.000000;max-focus-pos-dac=1023;max-focus-pos-diopter=10;max-focus-pos-index=1023;max-focus-pos-ratio=100;max-iso=1600;max-num-detected-faces-hw=10;max-num-detected-faces-sw=10;max-num-focus-areas=1;max-num-metering-areas=10;max-saturation=10;max-sce-factor=100;max-sharpness=36;max-wb-cct=8000;max-wb-gain=4;max-zoom=90;mce=enable;mce-values=enable,disable;metering-areas=(0, 0, 0, 0, 0);min-brightness=0;min-contrast=0;min-exposure-compensation=-40;min-exposure-time=0.013355;min-focus-pos-dac=0;min-focus-pos-diopter=0;min-focus-pos-index=0;min-focus-pos-ratio=0;min-iso=100;min-saturation=0;min-sce-factor=-100;min-sharpness=0;min-wb-cct=2000;min-wb-gain=1;noise-reduction-mode=off;noise-reduction-mode-values=off,fast,high-quality;num-retro-burst-per-shutter=0;num-snaps-per-shutter=1;opti-zoom=opti-zoom-off;opti-zoom-values=opti-zoom-off,opti-zoom-on;picture-format=jpeg;picture-format-values=jpeg,bayer-mipi-10grbg;picture-size=320x240;picture-size-values=3264x2448,3264x1836,3200x2400,2592x1944,2304x1728,2304x1296,2048x1536,1920x1080,1440x1080,1600x1200,1280x960,1280x720,1024x768,800x600,800x480,720x480,640x480,640x360,320x240;preferred-preview-size-for-video=960x540;preview-flip=off;preview-format=yuv420sp;preview-format-values=yuv420sp,yuv420p,nv12-venus;preview-fps-range=7000,30000;preview-fps-range-values=(15000,15000),(20000,20000),(24000,24000),(7000,30000),(30000,30000);preview-frame-rate=30;preview-frame-rate-values=7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30;preview-size=960x540;preview-size-values=960x540,800x480,720x540,768x432,720x480,640x480,640x360,576x432,540x540,480x480,384x288,352x288,320x240,176x144;qc-max-num-requested-faces=10;raw-size=3264x2448;rdi-mode=disable;rdi-mode-values=enable,disable;re-focus=re-focus-off;re-focus-values=re-focus-off,re-focus-on;redeye-
I/CameraConfiguration( 6165): Requesting focus mode value from among: [auto]
I/CameraConfiguration( 6165): Supported focus mode values: [auto, infinity, fixed, macro, continuous-video, continuous-picture, manual]
I/CameraConfiguration( 6165): Can set focus mode to: auto
I/CameraConfiguration( 6165): Focus mode already set to auto
I/CameraConfiguration( 6165): Requesting flash mode value from among: [off]
I/CameraConfiguration( 6165): Supported flash mode values: [off, auto, on, torch]
I/CameraConfiguration( 6165): Can set flash mode to: off
I/CameraConfiguration( 6165): Flash mode already set to off
I/PreviewScalingStrategy( 6165): Viewfinder size: 628x510
I/PreviewScalingStrategy( 6165): Preview in order of preference: [720x540, 640x480, 576x432, 720x480, 540x540, 800x480, 960x540, 480x480, 768x432, 352x288, 384x288, 640x360, 320x240, 176x144]
I/CameraManager( 6165): Final camera parameters: ae-bracket-hdr=Off;ae-bracket-hdr-values=Off,AE-Bracket;af-bracket=af-bracket-off;af-bracket-values=af-bracket-off,af-bracket-on;antibanding=auto;antibanding-values=off,60hz,50hz,auto;auto-exposure=frame-average;auto-exposure-lock=false;auto-exposure-lock-supported=true;auto-exposure-values=frame-average,center-weighted,spot-metering,center-weighted,spot-metering-adv,center-weighted-adv;auto-hdr-supported=true;auto-whitebalance-lock=false;auto-whitebalance-lock-supported=true;avtimer=disable;brightness-step=1;cache-video-buffers=disable;camera-mode=0;cds-mode-values=off,on,auto;chroma-flash=chroma-flash-off;chroma-flash-values=chroma-flash-off,chroma-flash-on;contrast=5;contrast-step=1;denoise=denoise-on;denoise-values=denoise-off,denoise-on;dis=disable;dis-values=enable,disable;effect=none;effect-values=none,mono,negative,solarize,sepia,posterize,whiteboard,blackboard,aqua,emboss,sketch,neon;exposure-compensation=0;exposure-compensation-step=0.1;face-detection=off;face-detection-values=off,on;flash-mode=off;flash-mode-values=off,auto,on,torch;flip-mode-values=off,flip-v,flip-h,flip-vh;focal-length=2.94;focus-areas=(0, 0, 0, 0, 0);focus-distances=Infinity,Infinity,Infinity;focus-mode=auto;focus-mode-values=auto,infinity,fixed,macro,continuous-video,continuous-picture,manual;hdr-mode=hdr-mode-multiframe;hdr-mode-values=hdr-mode-multiframe;hdr-need-1x=false;hdr-need-1x-values=false,true;hfr-size-values=720x480;histogram=disable;histogram-values=enable,disable;horizontal-view-angle=62.7;instant-aec-values=;instant-capture-values=;internal-restart=true;iso=auto;iso-values=auto,ISO_HJR,ISO100,ISO200,ISO400,ISO800,ISO1600,ISO3200;jpeg-quality=85;jpeg-thumbnail-height=154;jpeg-thumbnail-quality=85;jpeg-thumbnail-size-values=256x154,240x160,320x320,320x240,256x144,240x144,176x144,240x320,144x176,0x0;jpeg-thumbnail-width=256;lensshade=enable;lensshade-values=enable,disable;long-shot=off;longshot-supported=true;luma-adaptation=3;manual-exposure-modes=off,exp-time-priority,iso-priority,user-setting;manual-focus-modes=off,scale-mode,diopter-mode;manual-wb-modes=off,color-temperature,rbgb-gains;max-brightness=6;max-contrast=10;max-exposure-compensation=40;max-exposure-time=1000.000000;max-focus-pos-dac=1023;max-focus-pos-diopter=10;max-focus-pos-index=1023;max-focus-pos-ratio=100;max-iso=1600;max-num-detected-faces-hw=10;max-num-detected-faces-sw=10;max-num-focus-areas=1;max-num-metering-areas=10;max-saturation=10;max-sce-factor=100;max-sharpness=36;max-wb-cct=8000;max-wb-gain=4;max-zoom=90;mce=enable;mce-values=enable,disable;metering-areas=(0, 0, 0, 0, 0);min-brightness=0;min-contrast=0;min-exposure-compensation=-40;min-exposure-time=0.013355;min-focus-pos-dac=0;min-focus-pos-diopter=0;min-focus-pos-index=0;min-focus-pos-ratio=0;min-iso=100;min-saturation=0;min-sce-factor=-100;min-sharpness=0;min-wb-cct=2000;min-wb-gain=1;noise-reduction-mode=off;noise-reduction-mode-values=off,fast,high-quality;num-retro-burst-per-shutter=0;num-snaps-per-shutter=1;opti-zoom=opti-zoom-off;opti-zoom-values=opti-zoom-off,opti-zoom-on;picture-format=jpeg;picture-format-values=jpeg,bayer-mipi-10grbg;picture-size=320x240;picture-size-values=3264x2448,3264x1836,3200x2400,2592x1944,2304x1728,2304x1296,2048x1536,1920x1080,1440x1080,1600x1200,1280x960,1280x720,1024x768,800x600,800x480,720x480,640x480,640x360,320x240;preferred-preview-size-for-video=960x540;preview-flip=off;preview-format=yuv420sp;preview-format-values=yuv420sp,yuv420p,nv12-venus;preview-fps-range=7000,30000;preview-fps-range-values=(15000,15000),(20000,20000),(24000,24000),(7000,30000),(30000,30000);preview-frame-rate=30;preview-frame-rate-values=7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30;preview-size-values=960x540,800x480,720x540,768x432,720x480,640x480,640x360,576x432,540x540,480x480,384x288,352x288,320x240,176x144;qc-max-num-requested-faces=10;raw-size=3264x2448;rdi-mode=disable;rdi-mode-values=enable,disable;re-focus=re-focus-off;re-focus-values=re-focus-off,re-focus-on;redeye-reduction=disable;redey
I/CenterCropStrategy( 6165): Preview: 540x720; Scaled: 510x680; Want: 510x628
I/CameraPreview( 6165): Starting preview
D/CameraInstance( 6165): Starting preview
I/art     ( 6165): Rejecting re-init on previously-failed class java.lang.Class<com.journeyapps.barcodescanner.Decoder>
I/art     ( 6165): Rejecting re-init on previously-failed class java.lang.Class<com.journeyapps.barcodescanner.Decoder>
V/Camera  ( 6165): sendStartPreviewBroadCast
I/art     ( 6165): Rejecting re-init on previously-failed class java.lang.Class<com.journeyapps.barcodescanner.Decoder>
I/art     ( 6165): Rejecting re-init on previously-failed class java.lang.Class<com.journeyapps.barcodescanner.Decoder>
I/art     ( 6165): Rejecting re-init on previously-failed class java.lang.Class<com.journeyapps.barcodescanner.Decoder>
I/art     ( 6165): Rejecting re-init on previously-failed class java.lang.Class<com.journeyapps.barcodescanner.Decoder>
I/art     ( 6165): Rejecting re-init on previously-failed class java.lang.Class<com.journeyapps.barcodescanner.Decoder>
I/art     ( 6165): Rejecting re-init on previously-failed class java.lang.Class<com.journeyapps.barcodescanner.Decoder>
I/art     ( 6165): Rejecting re-init on previously-failed class java.lang.Class<com.journeyapps.barcodescanner.Decoder>
I/art     ( 6165): Rejecting re-init on previously-failed class java.lang.Class<com.journeyapps.barcodescanner.Decoder>
I/art     ( 6165): Rejecting re-init on previously-failed class java.lang.Class<com.journeyapps.barcodescanner.Decoder>
I/art     ( 6165): Rejecting re-init on previously-failed class java.lang.Class<com.journeyapps.barcodescanner.DecoderResultPointCallback>
D/AndroidRuntime( 6165): Shutting down VM
E/AndroidRuntime( 6165): FATAL EXCEPTION: main
E/AndroidRuntime( 6165): Process: com.session.doctor, PID: 6165
E/AndroidRuntime( 6165): java.lang.NoClassDefFoundError: com.journeyapps.barcodescanner.DecoderResultPointCallback
E/AndroidRuntime( 6165): 	at com.journeyapps.barcodescanner.BarcodeView.createDecoder(BarcodeView.java:116)
E/AndroidRuntime( 6165): 	at com.journeyapps.barcodescanner.BarcodeView.startDecoderThread(BarcodeView.java:178)
E/AndroidRuntime( 6165): 	at com.journeyapps.barcodescanner.BarcodeView.previewStarted(BarcodeView.java:188)
E/AndroidRuntime( 6165): 	at com.journeyapps.barcodescanner.CameraPreview.startCameraPreview(CameraPreview.java:787)
E/AndroidRuntime( 6165): 	at com.journeyapps.barcodescanner.CameraPreview.startPreviewIfReady(CameraPreview.java:530)
E/AndroidRuntime( 6165): 	at com.journeyapps.barcodescanner.CameraPreview.previewSized(CameraPreview.java:474)
E/AndroidRuntime( 6165): 	at com.journeyapps.barcodescanner.CameraPreview.access$300(CameraPreview.java:60)
E/AndroidRuntime( 6165): 	at com.journeyapps.barcodescanner.CameraPreview$3.handleMessage(CameraPreview.java:202)
E/AndroidRuntime( 6165): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/AndroidRuntime( 6165): 	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime( 6165): 	at android.app.ActivityThread.main(ActivityThread.java:5619)
E/AndroidRuntime( 6165): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6165): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
E/AndroidRuntime( 6165): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
I/Process ( 6165): Sending signal. PID: 6165 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by juliansteenbakker** [comment]
Which version of the app are you using? And which device and which android version?

**Comment by juliansteenbakker** [comment]
Closed due to no reaction.
