### ISSUE TITLE
[FEATURE] Know exact type/format[url/Contact/Phone/SMS/Text] of data provided by QR

### ISSUE THREAD

**Issue by Priyank-Sharma-89** [juliuscanute/qr_code_scanner#366]
**Is your feature request related to a problem? Please describe.**
I created a practice app to implement QR scan feature. On the website from where I am generating QR, I see lot of tabs for different and specific types of data, like URL, text, Contact, SMS, Phone. However, when I tried with every type data, QR scan only returns "string" type data. I faced difficulties, specifically to identify if its a Contact or email. Also, if its a string just with digits/numbers (in case of phone) or normal text.

Even barcode.format.formatName is returning QR_CODE for all type of data.

**Describe the solution you'd like**
Can we have something like barcode.code.format.url or barcode.code.format.VCARD or some sort of property or check, through which we can know exactly what type of data is in QR.

**Additional context**

**Comment by juliansteenbakker** [comment]
Please see #491 for a package that supports this.
