### ISSUE TITLE
[BUG] qr code not scanning in dark mode

### ISSUE THREAD

**Issue by akshayyadav76** [juliuscanute/qr_code_scanner#367]
**Describe the bug**
Qr code not scanning in dark mode
that same Qr code scanning without dark mode

**Screenshots**
![UPI qr code](https://user-images.githubusercontent.com/46517854/125629540-bfaab71b-8bdb-451e-9be3-76432116c298.jpg)

**Comment by hnrq** [comment]
I also have this issue. color inverted QR codes aren't being detected.

**Comment by akshayyadav76** [comment]
do you find any solution? my project stuck because of that

**Comment by juliansteenbakker** [comment]
This is because of the underlying framework. I have made an update to the framework which you can already try because it is in the main repository. Maybe that will resolve the issue, i don't really know. I will release it later with some other changes.

**Comment by akshayyadav76** [comment]
I try your zxing-update branch with updated dependency but it is not working either. same issue

**Comment by juliansteenbakker** [comment]
I have updated the framework yet again. Please check with v0.5.2, otherwise if it still doesn't work i suggest waiting for the MLKit release. I do think the MLKit version will detect this QRCode.

**Comment by akshayyadav76** [comment]
It is still not working but now I created my own library with 'me.dm7.barcodescanner:zxing:1.9.13' dependency and it's working out of the box as I want.

**Comment by juliansteenbakker** [comment]
Good to hear that works out for you. Found out that ZXING never had good support for white QR codes and since it's in maintenance only mode it will probably never be fixed. See https://github.com/zxing/zxing/issues/194

I'm gonna close this now because i am able to scan this code with the new MLKit version.

**Comment by akshayyadav76** [comment]
sure and I am waiting for MLKit version

**Comment by akkalbhor** [comment]
Hello @juliansteenbakker I am also facing the same issue in my case background is in red and qr code is black. till when can we expect MLKit version

**Comment by EmreSURK** [comment]
Hi, same problem here. Any news?
