### ISSUE TITLE
[iOS] App crushes without any Exit codes.

### ISSUE THREAD

**Issue by softmarshmallow** [juliuscanute/qr_code_scanner#38]
Works fine on android, But on ios, when the screen gets pushed, it will request camera permission (rather it is already granted) and app just crushes without any exit code when running via flutter.

when running via xcode, it will give error code 
```
2019-09-14 04:38:44.027931+0900 Runner[1427:183336] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2019-09-14 04:38:44.030422+0900 Runner[1427:183336] [MC] Reading from public effective user settings.
(lldb) 
```
`Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)`

which is not very helpful..

Problem is It wont work with google maps.
The example app works, but when pushing that screen from google maps contained screen, app will crash

**Comment by randhika** [comment]
any update @juliuscanute for this issue? I got the same issue when I run the app in iPhone x emulator, QR page ask for camera permission (rather it is already granted). Can you help us?

**Comment by jlubeck** [comment]
My app is crashing on a physical device as well

**Comment by ayushmehre** [comment]
Any solution??

**Comment by juliansteenbakker** [comment]
I'm gonna need some more information here. What iOS version is being used? Which version of qr_code_scanner is being used? Please try it with the latest version (0.0.14) and an updated flutter build. It would also be nice if you can post the output of `flutter doctor -v`.
