### ISSUE TITLE
[BUG] onPermissionSet is called multiple times

### ISSUE THREAD

**Issue by nickwri** [juliuscanute/qr_code_scanner#380]
When entering a QR code reading page for the first time, the app correctly requests camera permission. 
If I deny permission my callback function defined in onPermissionSet is correctly called (and all is good).
If I re-enter the page, and again deny permission, my callback function defined in onPermissionSet is now called twice. 
Repeat and it gets called three times...and so on.

Occurs on versions 0.5.1 and 0.5.2.

**Flutter information**
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.1110], locale en-GB)
    • Flutter version 2.2.2 at C:\src\flutter
    • Framework revision d79295af24 (6 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Nick\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\Nick\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 92.0.902.55

**Comment by jawa0919** [comment]
yeas, there have multiple MethodChannel cell 

![debu1](https://raw.githubusercontent.com/jawa0919/qr_code_scanner/called-multiple-times/.resources/called-multiple-times-debug01.png)
![debu2](https://raw.githubusercontent.com/jawa0919/qr_code_scanner/called-multiple-times/.resources/called-multiple-times-debug02.png)

**Comment by jawa0919** [comment]
fix   https://github.com/jawa0919/qr_code_scanner/tree/called-multiple-times

**Comment by juliansteenbakker** [comment]
Thanks for your fix @jawa0919. I will release the fix later today or tomorrow.
