### ISSUE TITLE
[BUG] No clean way to catch the CameraException if the user refuses the camera permission

### ISSUE THREAD

**Issue by mregnauld** [juliuscanute/qr_code_scanner#388]
**Describe the bug**
In my Flutter app, I implemented qr_code_scanner.
When I launch my app on an iPhone 11, I get asked for the camera permission.
When I refuse the permission, I got a `CameraException`, and there is now way I can catch it.

Is there any way to catch the `CameraException` in the `_startScan()` function, so I can properly handle the case where the user refuses the permission on iOS?

**Flutter information**
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.3.1 20E241 darwin-arm, locale fr-FR)
    • Flutter version 2.2.2 at /Users/mregnauld/FlutterSDK/flutter
    • Framework revision d79295af24 (8 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/mregnauld/AndroidSDK
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/mregnauld/AndroidSDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.0

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • SM M515F (mobile)           • RF8NC0PSMMV               • android-arm64 • Android 11 (API 30)
    • iPhone de Matthieu (mobile) • 00008030-001C085222DA802E • ios           • iOS 14.7.1

! Doctor found issues in 1 category.

**Device (please complete the following information):**
 - Device: iPhone11
 - OS: iOS 14.7.1

**Comment by kmrosiek** [comment]
How you found any workout for it?

**Comment by mregnauld** [comment]
@kmrosiek it's been a while but as far as I remember, I chose to ask for permission by myself natively (on both Android and iOS), and then use qr_code_scanner only when I get the permission.

**Comment by gemunet** [comment]
Still no solution for this error? it's very ugly
