### ISSUE TITLE
Roadmap to v1.0.0: help wanted with development

### ISSUE THREAD

**Issue by juliansteenbakker** [juliuscanute/qr_code_scanner#394]
The current package is not yet in optimal form. There are a few things we need to fix in order to release a first stable release. I unfortunately don't have that much time to work on it since I maintain multiple packages and also have a full-time job. Thats why it would be great if other people want to collaborate and make this package stable and easy to use.

Here is a list of things we need to fix for the first (1.0.0) release:
* Create a default list of API methods that doesn't depend on the underlying framework
This is neccessary because for example WEB and iOS/Android don't use the same framework however you still want to use the same QRCode widget. This is a difficult item that i definitely need some help with. For example, what would be a good method of choosing/overriding a default framework for a given platform. Also, how do we account for framework specific settings.
* Migrate to federated structure for easy maintainability of other platforms
* Add more options to MLKit like flash support.
* Analyze other platforms like macOS, Windows, Linux. (This largely depends on camera support which i don't think is existing yet).

If you have any other suggestions that i can add to this list or just have some feedback, i'm happy to hear about it. Right now for me the first priority is to merge some existing open PR's, as well as looking at some critical outstanding bugs. You can discuss both here in this issue or on Discord.

**Comment by juliansteenbakker** [comment]
It's been awhile since i posted an update because i had some other plugin's to manage with higher priority. Right now i'm working on fixing most outstanding bugs regarding the ZXING library on android. I am delaying a migration to MLKit because MLKit will also affect on which devices this plugin can run (only 64bit ios devices). I am planning on releasing a stable v1.0.0 which uses the already existing frameworks, and migrating to a new framework will be something for v2.0.0.

**Comment by BanlyMBD** [comment]
I'm currently building PWA with Flutter, I would love to see more support on the web.

**Comment by paj-co** [comment]
I'm looking for package to scan QR codes, that can be embedded in Flutter view. It seems that qr_code_scanner is under active development, that's great!

However, it looks like you depend on `Zxing` which is in maintenance mode and `MTBBarcodeScanner` which is archived.

If I understand correctly, switch to MLKit, will be both for Android and iOS?

**Comment by juliansteenbakker** [comment]
Since this packaged is based on old packages, i have created a new plugin called [mobile_scanner](https://pub.dev/packages/mobile_scanner) which uses MLKit and adds features like switching camera and flash. This project is now in maintenance only mode.
