### ISSUE TITLE
[ Too many scans/second ]

### ISSUE THREAD

**Issue by Gobmichet** [juliuscanute/qr_code_scanner#399]
Hi,
First of all, Thanks for the work :)

Here comes the issue/question :
> I implemented your solution in my App and it seems to work well, but !
> I tried to add a SnackBar & a sound on a QR code scan to warn the user that  has to scan several ones in a row...

The problem is that the scanner reads too many times the same QR when hovering it...
Therefore, i got too many snackbars that stack for each QRcode and that's just ugly.

Is there a way to configure the reading frequency or something ?

Thanks in advance.

**Comment by cyluxx** [comment]
I solved this issue temporarily by setting a class variable manually in my parent Stateful Widget. Only if the scanData returns _something new_ it will execute the function, e.g. show a snackbar.

The beginning of my _onQRViewCreated function looks like this:

```
void _onQRViewCreated(QRViewController controller) {
    this.controller = controller;
    controller.scannedDataStream.listen((scanData) async {
          if (scannedCode == scanData.code) {
            return;
          }
          scannedCode = scanData.code;

          // do stuff
```

**Comment by ozc** [comment]
@cyluxx this will lead to same code not processed second time when needed. eg. reading barcodes for products on checkout.

Better option is to use scannedCode as nullable.

```
void _onQRViewCreated(QRViewController? controller) {
    this.controller = controller;
    controller?.scannedDataStream.listen((scanData) {
      this._onQRCodeRead(scanData);
    });
  }


void _onQRCodeRead(Barcode scanData) async {
{
     if (this.scannedCode != null) {
      return;
    }
    this.controller?.pauseCamera();
    this.scannedCode = scanData;

    ....
    this.scannedCode=null;
    this.controller?.resumeCamera();
    return;
}
```

**Comment by jaxnz** [comment]
> @cyluxx this will lead to same code not processed second time when needed. eg. reading barcodes for products on checkout.
> 
> Better option is to use scannedCode as nullable.
> 
> ```
> void _onQRViewCreated(QRViewController? controller) {
>     this.controller = controller;
>     controller?.scannedDataStream.listen((scanData) {
>       this._onQRCodeRead(scanData);
>     });
>   }
> 
> 
> void _onQRCodeRead(Barcode scanData) async {
> {
>      if (this.scannedCode != null) {
>       return;
>     }
>     this.controller?.pauseCamera();
>     this.scannedCode = scanData;
> 
>     ....
>     this.scannedCode=null;
>     this.controller?.resumeCamera();
>     return;
> }
> ```

Where are you getting `this.scannedCode` from?
