### ISSUE TITLE
The position of overlay

### ISSUE THREAD

**Issue by Nirvana-cn** [juliuscanute/qr_code_scanner#40]
I used the library and it worked great.

But it seems that the overlay is always in the center of screen.

How can I adjust the position of overlay?

**Comment by Nirvana-cn** [comment]
The code is below. The overlay is in the center of QRView.
```
import 'package:flutter/material.dart';
import 'package:qr_code_scanner/qr_code_scanner.dart';
import 'package:qr_code_scanner/qr_scanner_overlay_shape.dart';

class QRViewExample extends StatefulWidget {
  const QRViewExample({
    Key key,
  }) : super(key: key);

  @override
  State<StatefulWidget> createState() => _QRViewExampleState();
}

class _QRViewExampleState extends State<QRViewExample> {
  var qrText = "";
  QRViewController controller;
  final GlobalKey qrKey = GlobalKey(debugLabel: 'QR');

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("QR Code"),
      ),
      body: Column(
        children: <Widget>[
          Expanded(
            child: QRView(
              key: qrKey,
              onQRViewCreated: _onQRViewCreated,
              overlay: QrScannerOverlayShape(
                borderColor: Colors.red,
                borderRadius: 0,
                borderLength: 30,
                borderWidth: 10,
                cutOutSize: 300,
              ),
            ),
            flex: 1,
          ),
        ],
      ),
    );
  }

  void _onQRViewCreated(QRViewController controller) {
    this.controller = controller;
    controller.scannedDataStream.listen((scanData) {
      controller.pauseCamera();
      setState(() {
        qrText = scanData;
      });
    });
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }
}
```

![](https://user-images.githubusercontent.com/26457604/67286207-908b3b80-f50b-11e9-9d3b-652600eb8d05.png)

It is very good. But I want to move the position of overlay.  As the following picture shows:

![s2](https://user-images.githubusercontent.com/26457604/67657341-6a452000-f991-11e9-961f-2ada163a332f.png)

**Comment by Nirvana-cn** [comment]
Is there a good way to implement it?

**Comment by Mecil9** [comment]
> Is there a good way to implement it?

Did you solve?
I have a same need.

**Comment by Nirvana-cn** [comment]
No. I still not sort it out.

**Comment by deshario** [comment]
@Nirvana-cn @Mecil9 Did u guyz solve it ?
### It's not centering .. my QrView is inside custom layout with fixed height
![qrviewInsideCustomLayout](https://user-images.githubusercontent.com/11426727/73871612-bb15c000-4880-11ea-8162-3b8efd75194e.png)

**Comment by rgb1380** [comment]
This is due to incorrect calculation of cutOurRect in qr_scanner_overlay_shape.dart

    final cutOutRect = Rect.fromLTWH(
      width / 2 - _cutOutSize / 2 + borderOffset,
      height / 2 - _cutOutSize / 2 + borderOffset,
      _cutOutSize - borderOffset * 2,
      _cutOutSize - borderOffset * 2,
    );
which can be easily fixed as follows:

    final cutOutRect = Rect.fromLTWH(
      rect.left + width / 2 - _cutOutSize / 2 + borderOffset,
      rect.top + height / 2 - _cutOutSize / 2 + borderOffset,
      _cutOutSize - borderOffset * 2,
      _cutOutSize - borderOffset * 2,
    );

**Comment by deshario** [comment]
@rgb1380 ok Thankx

**Comment by dspicher** [comment]
This should be fixed.
