### ISSUE TITLE
[BUG]  ios pod install failed

### ISSUE THREAD

**Issue by jahnli** [juliuscanute/qr_code_scanner#400]
**Describe the bug**

**Flutter information**
Always provide the output of `flutter doctor -v` as it is needed in order to know on which Flutter versions the bug exists in.

**Device (please complete the following information):**
ios9.0
**Screenshots**

[!] CocoaPods could not find compatible versions for pod
    "GoogleMLKit/BarcodeScanning":
      In Podfile:
        qr_code_scanner (from `.symlinks/plugins/qr_code_scanner/ios`) was
        resolved to 0.2.0, which depends on
          GoogleMLKit/BarcodeScanning

    Specs satisfying the `GoogleMLKit/BarcodeScanning` dependency were found,
    but they required a higher minimum deployment target.

**Additional context**

**Comment by jahnli** [comment]
![image](https://user-images.githubusercontent.com/20943608/130022923-80df7c63-db8f-4830-823b-72e6746673fe.png)

**Comment by CharlesMangwa** [comment]
Try updating your Podfile to support iOS 10 (min version accepted by the library I believe) instead of 9. It should read:
```
platform :ios, '10.0'
```

**Comment by juliansteenbakker** [comment]
Please see [mobile_scanner](https://pub.dev/packages/mobile_scanner) for a new scanner with higher accuracy.
