### ISSUE TITLE
[BUG] can't use it with TextField.

### ISSUE THREAD

**Issue by kvii** [juliuscanute/qr_code_scanner#401]
**Describe the bug**
I use example code, change code as below.
And I can't open camera preview.

Here is bug description.
> Unhandled Exception: PlatformException(error, InputChannel is not initialized., null, java.lang.RuntimeException: InputChannel is not initialized.

``` dart
class MyHome extends StatelessWidget {
  const MyHome({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    var btn = ElevatedButton(
      onPressed: () {
        Navigator.of(context).push(MaterialPageRoute(
          builder: (context) => QRViewExample(),
        ));
      },
      child: Text('qrView'),
    );

    return Scaffold(
      appBar: AppBar(title: Text('Flutter Demo Home Page')),
      body: Center(
        child: TextField(decoration: InputDecoration(suffixIcon: btn)),
      ),
    );
  }
}
```

**Flutter information**

> [✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.22000.132], locale zh-CN)
> • Flutter version 2.2.3 at C:\Softwares\flutter
> • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
> • Engine revision 241c87ad80
> • Dart version 2.13.4
> • Pub download mirror https://pub.flutter-io.cn
> • Flutter download mirror https://storage.flutter-io.cn
>
> [!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at C:\Softwares\Android\Sdk
>     • Platform android-30, build-tools 30.0.2
>     • ANDROID_HOME = C:\Softwares\Android\Sdk
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
>     ✗ Android license status unknown.
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
>       See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
>
> [✓] Chrome - develop for the web
>     • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
>
> [✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
>     • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
>     • Visual Studio Community 2019 version 16.9.31205.134
>     • Windows 10 SDK version 10.0.19041.0
>
> [✓] Android Studio (version 4.1.0)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
>
> [✓] IntelliJ IDEA Community Edition (version 2020.3)
>     • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.4
>     • Flutter plugin version 56.0.4
>     • Dart plugin version 203.8173
>
> [✓] IntelliJ IDEA Community Edition (version 2021.1)
>     • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.3
>     • Flutter plugin version 59.0.4
>     • Dart plugin version 212.4746.57
>
> [✓] IntelliJ IDEA Community Edition (version 2021.2)
>     • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2
>     • Flutter plugin version 59.0.4
>     • Dart plugin version 212.4746.57
>
> [✓] VS Code, 64-bit edition (version 1.59.0)
>     • VS Code at C:\Program Files\Microsoft VS Code
>     • Flutter extension version 3.25.0
>
> [✓] Proxy Configuration
>     • HTTP_PROXY is set
>     • NO_PROXY is localhost,127.0.0.1
>     • NO_PROXY contains 127.0.0.1
>     • NO_PROXY contains localhost
>
> [✓] Connected device (4 available)
>     • G0515D (mobile)   • 5de5edb8f40d • android-arm64  • Android 10 (API 29)
>     • Windows (desktop) • windows      • windows-x64    • Microsoft Windows [Version 10.0.22000.132]
>     • Chrome (web)      • chrome       • web-javascript • Google Chrome 92.0.4515.159
>     • Edge (web)        • edge         • web-javascript • Microsoft Edge 92.0.902.73

**Screenshots**
![screen-20210819-172516](https://user-images.githubusercontent.com/56432636/130045098-03022bfb-a5ec-41ca-8b8e-43064348113f.gif)

**Comment by juliansteenbakker** [comment]
You are passing a button to a suffix icon, i don't think thats the right way to do. It would be better to wrap the button and the input field in a Row()
