### ISSUE TITLE
[FEATURE] Scan image in gallery?

### ISSUE THREAD

**Issue by fzyzcjy** [juliuscanute/qr_code_scanner#402]
**Is your feature request related to a problem? Please describe.**
I want to scan image photo in gallery, but currently only allow scan from camera

**Describe the solution you'd like**
scan photo in gallery

**Additional context**
thanks!

**Comment by Mike-3** [comment]
i need this also.

**Comment by armaan98** [comment]
When can we expect this enhancement?Or is there any other good package we can use for this for time being?

**Comment by simonesestito** [comment]
I would need this too, so I'm following this thread

**Comment by sylvestrevgen** [comment]
I need this too.)

**Comment by phankietit** [comment]
+1

**Comment by juliansteenbakker** [comment]
This is possible with v0.2.0 of [mobile_scanner](https://pub.dev/packages/mobile_scanner)

**Comment by huangsir0** [comment]
+1

**Comment by gaoguanqi** [comment]
+1
