### ISSUE TITLE
Failed run project in iOS

### ISSUE THREAD

**Issue by randhika** [juliuscanute/qr_code_scanner#41]
Hi, this on result error from my side

The Swift pod `qr_code_scanner` depends upon `MTBBarcodeScanner`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
No matching processes belonging to you were found
[   +5 ms] Warning: CocoaPods not installed. Skipping pod install.
             CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
             Without CocoaPods, plugins will not work on iOS or macOS.
             For more info, see https://flutter.dev/platform-plugins
           To install:
             brew install cocoapods
             pod setup

Encountered error while building for device.

Have any fixed issue before @juliuscanute ?

**Comment by TheWalkingDead1024** [comment]
I have got this issue too. Could sb. help to resolve it?

**Comment by juliuscanute** [comment]
duplicate #16
