### ISSUE TITLE
java.lang.AssertionError: impossible[BUG] 

### ISSUE THREAD

**Issue by AKA-LinCoder** [juliuscanute/qr_code_scanner#411]
**Describe the bug**
when i run as debufg it look nice,but when run as release ,there will be crash when i open QRView

**Flutter information**
[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.7 19H1030 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.0 at /Users/hc-101/Applications/flutter
    • Framework revision b22742018b (4 months ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/hc-101/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.1)
    • IntelliJ at /Applications/ /IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

**Device (please complete the following information):**
 - Device: [Redmi Note 5]
 - OS: [Android 9]

**Screenshots**
![791D22A2207DBFAD5CDCEC6624A86591](https://user-images.githubusercontent.com/35401579/132005253-afd65105-9b4d-4be7-86d5-e2948f9818e9.png)
![601789A243D58B6C4B50242CDFCCC6A1](https://user-images.githubusercontent.com/35401579/132005635-0300224f-d8cd-4e68-a47f-1a9958e5590e.png)

**Additional context**

**Comment by juliansteenbakker** [comment]
Can you please try again with version 0.7.0 and report if still not working.
