### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Abdalqader27** [juliuscanute/qr_code_scanner#416]
**Describe the bug**
 '/home/abdalqader/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-1.0.0-alpha.1/android/build.gradle' line: 27

* What went wrong:
A problem occurred evaluating project ':qr_code_scanner'.
> No signature of method: build_ez44vccrryl9hzgav613sxnle.android() is applicable for argument types: (build_ez44vccrryl9hzgav613sxnle$_run_closure2) values: [build_ez44vccrryl9hzgav613sxnle$_run_closure2@5583b30d]

**Flutter information**
Always provide the output of `flutter doctor -v` as it is needed in order to know on which Flutter versions the bug exists in.

**Device (please complete the following information):**

**Screenshots**

**Additional context**

**Comment by cuong292** [comment]
same prob

**Comment by juliansteenbakker** [comment]
Please see this answer: https://github.com/juliuscanute/qr_code_scanner/issues/187#issuecomment-751280619
Comment if the issue still exists after this.

**Comment by iovasquez** [comment]
I have this issue and I have applied the change in the answer #187 

Here is what I have in `build.gradle`
`ext.kotlin_version = '1.6.21'` and `classpath 'com.android.tools.build:gradle:7.2.1'`
