### ISSUE TITLE
Abstract method error in PlatformView

### ISSUE THREAD

**Issue by kuhnroyal** [juliuscanute/qr_code_scanner#42]
I am running into this issue: https://github.com/flutter/flutter/issues/40126
The default/abstract methods need to be implemented in `QRView.java`.

```
    @Override
    public void onInputConnectionLocked() {

    }

    @Override
    public void onInputConnectionUnlocked() {

    }
```

**Comment by yunzhouhua** [comment]
after I add these fun in QRView.java, I get a new problem.
Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: net.touchcapture.qr.flutterqr/qrview

**Comment by juliansteenbakker** [comment]
The issue linked reveals that it has actually to do with some gradle version. I didn't encounter the problem so i am closing this issue for now. If you still encounter this issue, please feel free to comment and i'll reopen this issue.
