### ISSUE TITLE
[BUG] Color out on scanning area

### ISSUE THREAD

**Issue by BanlyMBD** [juliuscanute/qr_code_scanner#453]
**Describe the bug**
The scan area colored out same as the border color of the overlay.
It works fine on local development but I get the issue on the production hosted on firebase

**Flutter information**
<img width="459" alt="Capture" src="https://user-images.githubusercontent.com/75768718/140290186-12e33d0e-8d06-4775-9429-a1c0f6a95863.PNG">

**Device (please complete the following information):**
- Chrome (Web)

**Screenshots**

![Screenshot_20211104-161602](https://user-images.githubusercontent.com/75768718/140290901-9ac182d1-d258-4312-955a-ff7008f74286.png)

**Additional context**

**Comment by TheLonelyNull** [comment]
Same problem here. The scanner works on desktop chrome but gets coloured out on mobile chrome

**Comment by TheLonelyNull** [comment]
This is related to issues with BlendMode using the skia renderer (https://github.com/flutter/flutter/issues/69849).  A workaround for flutter web is to use for the time being `--web-renderer=canvaskit`

**Comment by BanlyMBD** [comment]
@TheLonelyNull Yes, I had tried that before, I will try it again. I had tried many ways, one way that also works is to get rid of AppBar and render QRView in full screen, but that margin down of camera preview still appears in some devices.
