### ISSUE TITLE
[BUG] Crash on release APK Android OS 11

### ISSUE THREAD

**Issue by urvashikharecha** [juliuscanute/qr_code_scanner#455]
While opening qr code scanner in release apk , it is crashing have tested in android OS 11

java.lang.RuntimeException: java.lang.NoSuchMethodException: c.e.c.e.values []

![image](https://user-images.githubusercontent.com/20655150/141228653-0d26af8b-d8fd-4c33-ac83-a23c3f51ef72.png)

**Comment by juliansteenbakker** [comment]
I can't do anything with this logfile because it's a release version. You need to deobfuscate your log files https://stackoverflow.com/questions/56006933/how-to-deobfuscate-an-android-stacktrace-using-mapping-file

**Comment by Sprechen** [comment]
solution here: https://github.com/juliuscanute/qr_code_scanner/issues/420#issuecomment-950672362
