### ISSUE TITLE
[BUG] Camera Freezes when adding Google Ads Widget to screen

### ISSUE THREAD

**Issue by matiazar** [juliuscanute/qr_code_scanner#461]
**Describe the bug**
I have implemented this QR Code Scanner without problems. 

Now I wanna add an AD to the screen for the trial version of the app. When I add the add (google_mobile_ads: ^1.0.0)
camera shows freezed or black screen.
when i click on flash button for example, it turns on and freeze again. and sometimes all the app freezes too.

**Flutter information**
Flutter 2.6

**Device (please complete the following information):**
 - Device: TLC 10+
 - OS: Android 10

**Comment by omerdotdev** [comment]
facing kinda same error on hot reload with latest version (0.6.1)

```
 @override
  void reassemble() {
    super.reassemble();
    if (Platform.isAndroid) {
      controller.pauseCamera();
    } else if (Platform.isIOS) {
      controller.resumeCamera();
    }
  }
```
Had this from example code from pub.dev . Doesn't seems to help. 

Package Version: 0.6.1
Flutter: Channel stable, 2.5.3
Dart version: 2.14.4 
Android SDK: Android SDK version 30.0.3

**Comment by juliansteenbakker** [comment]
This is probably because of the nativeView that this plugin uses. Please read #491 about the status and successor of this package.
