### ISSUE TITLE
[BUG] Barcode scanner incorrect result. 

### ISSUE THREAD

**Issue by r-oman-G** [juliuscanute/qr_code_scanner#468]
**Describe the bug**
When we set the camera to a different position, the scanner starts to display an incorrect result. The video shows that when we set the camera to a different position, the scanner starts to display an incorrect result.

The first video shown what the camera see the second video shown console output (from the camera barcode stream)

**Flutter information**
[✓] Flutter (Channel master, 2.6.0-12.0.pre.657, on macOS 12.0.1 21A559 darwin-x64, locale ru)
    • Flutter version 2.6.0-12.0.pre.657 at /Users/rgrunin/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a61c57add6 (4 weeks ago), 2021-11-08 21:37:48 -0800
    • Engine revision 162d8508f8
    • Dart version 2.15.0 (build 2.15.0-285.0.dev)

**Device (please complete the following information):**
<img width="848" alt="IntelliJ IDEA 12 08 16-14-05" src="https://user-images.githubusercontent.com/38914451/145214447-1cd416f8-3391-4e73-b115-d5a0959149d1.png">

**Screenshots**

**Additional context**

https://user-images.githubusercontent.com/38914451/145214467-e6b07bb8-bf7a-43fc-8484-33924bca9dfd.mp4

https://user-images.githubusercontent.com/38914451/145214487-fc0d6828-4827-4848-a181-ac03c9583872.mp4

**Comment by juliansteenbakker** [comment]
This is because of the underlying framework not supporting these characters. Please see https://github.com/juliuscanute/qr_code_scanner/issues/491
