### ISSUE TITLE
Set zoom level on camera used for qr scanning

### ISSUE THREAD

**Issue by Y07yoyo** [juliuscanute/qr_code_scanner#473]
Hi,

I need to be able to set the zoom level on the camera that is being used to scan the QR codes. Is this possible?

Kind Regards,

Yusuf

**Comment by juliansteenbakker** [comment]
This won't be implemented in this package. If you want this feature, please submit a request to it in [mobile_scanner](https://pub.dev/packages/mobile_scanner).
