### ISSUE TITLE
[BUG] Stretched screen

### ISSUE THREAD

**Issue by rok5ek** [juliuscanute/qr_code_scanner#477]
**Describe the bug**
The QR view is stretched vertically.

**Flutter information**
Always provide the output of `flutter doctor -v` as it is needed in order to know on which Flutter versions the bug exists in.

`[✓] Flutter (Channel stable, 2.8.1, on macOS 11.4 20F71 darwin-x64, locale en-SI)
    • Flutter version 2.8.1 at /Users/rok.petek/workspace/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/rok.petek/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/rok.petek/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
`

**Device (please complete the following information):**
 - Device: Google Pixel 2
 - OS: Android 11

**Screenshots**
<img width="339" alt="Screenshot 2022-01-05 at 11 34 14" src="https://user-images.githubusercontent.com/4641831/148206934-80fa7fd6-befe-4792-a805-cd6bd6709928.png">

**Additional context**
QR view should not be stretched, but proportionally displayed.

**Comment by juliansteenbakker** [comment]
Can you please try again with version 1.0.0
