### ISSUE TITLE
Error: Expected an identifier, but got '`'.

### ISSUE THREAD

**Issue by devnoaman** [juliuscanute/qr_code_scanner#480]
**Describe the bug**
after i added qr_code_scanner i get this exception

`../../.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.6.1/lib/src/qr_code_scanne
r.dart:242:11: Error: Expected an identifier, but got '`'.
[        ] Try inserting an identifier before '`'.
[  +41 ms]     try {`` 
`

**Comment by juliansteenbakker** [comment]
For some reason a space was added in the file name. Please try 0.7.0, or consider migrating to [mobile_scanner](https://pub.dev/packages/mobile_scanner)
