### ISSUE TITLE
widget binding warning

### ISSUE THREAD

**Issue by Henk-Keijzer** [juliuscanute/qr_code_scanner#487]
Hi, I get this warning message when I assemble my app in Android Studio for Android:

../flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.6.1/lib/src/qr_code_scanner.dart:68:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(_observer);

The app runs fune, it is just this warning...

**Comment by juliansteenbakker** [comment]
This happens only if your on a pre release version of Flutter, not on stable. Once this has been merged to stable, i will update the package with a change to fix it.
