### ISSUE TITLE
[BUG]  Different coloured QR scanning not working.

### ISSUE THREAD

**Issue by AbhijeetDash** [juliuscanute/qr_code_scanner#488]
**Describe the bug**
Cannot scan inverted or different colour QR Codes generated with qr_flutter 4.0.0. On changing QR colour to white and background colour to Grey (in my case) there were no results. On changing the background colour to white and QR Code to black (like it usually is) the scan returned appropriate results. 

**Flutter information**
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.2 21D49 darwin-x64, locale en-GB)
    • Flutter version 2.10.0 at /Users/abhijeetdash/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (12 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/abhijeetdash/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • ONEPLUS A5010 (mobile) • 2f25ca00 • android-arm64  • Android 10 (API 29)
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Device (please complete the following information):**
 - Device: OnePlus 5T
 - OS: Android Version 10

**Screenshots**
Here try scanning this QR code.. it was generated with qr_flutter : 4.0.0.
![GoaGroupQR](https://user-images.githubusercontent.com/43144055/153823563-2cc9dca7-9bd9-4a6d-9ec5-cb1b34f5529a.jpeg)

Should give : JOINGROUP_group_X3XovT6evfK5afFf
Returns no errors or result either.

**Additional context**
I tried to keep the QR colour relevant to my apps theme. I used several other scanners and the results was successfully retrieved. On changing QR colour to black and background to white the scanning was successful.

**Comment by alexandrim0** [comment]
@AbhijeetDash 
I faced the same problem.
Will it be better to use mobile_scanner package?
Thank you!

**Comment by alexandrim0** [comment]
@AbhijeetDash, hello!
Sorry if i`m too late with my answer, but i was sick.
So I used mobile_scanner and it works just fine!
It can read inverted colors, works faster and have more convenient interface.

**Comment by juliansteenbakker** [comment]
Can you please try again with version 1.0.0. That version uses a different decoder.
