### ISSUE TITLE
Not able to compare qrText with a String

### ISSUE THREAD

**Issue by HannHank** [juliuscanute/qr_code_scanner#50]
Hello, I am very new to Flutter and I just wanted to compare the qrtext value with a String.

`if(text == "-LrJtIuHApgNQmIIg9Xd")`

But for some reason it doesn't work. If I print the value, I can see that it have to be the same, but the value is somehow set later. 

thanks in advanced

**Comment by luis901101** [comment]
According to the latest available version in this moment v0.0.12 the code should be something like this...

`void _onQRViewCreated(QRViewController controller) {
    this.controller = controller;
    controller.scannedDataStream.listen((scanData) {
      setState(() {
        qrText = scanData;
        print(qrText == "-LrJtIuHApgNQmIIg9Xd");
        print(scanData == "-LrJtIuHApgNQmIIg9Xd");
      });
    });
  }`

Each print line must be true... just be sure the code you are scanning is really the String you are comparing to

**Comment by dspicher** [comment]
Closing as this seems unrelated to the QR scanner package. If you keep running into issues, please post a complete example.
