### ISSUE TITLE
qr_code_scanner:compileDebugKotlin still a thing after update

### ISSUE THREAD

**Issue by SwiftyFlow** [juliuscanute/qr_code_scanner#503]
How unclear is the following way to fix? And the readme doesn't solve anything either.

To fix it:

the code must be updated, it seems that the io.flutter.plugin.common.MethodCall interface has changed and the override must be updated:

Please, developer, change the line 118 at the QRView.kt to (remove the '?'):

...
override fun onMethodCall(call: MethodCall, result: MethodChannel.Result) {
...
This will make the code run on Android with no issues!

_Originally posted by @c0h1b4 in https://github.com/juliuscanute/qr_code_scanner/issues/19#issuecomment-505458678_

**Comment by SwiftyFlow** [comment]
FAILURE: Build failed with an exception.

e: [/Users/flowpottevin/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt](): (23, 1): Class 'QRView' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
e: [/Users/flowpottevin/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt](): (216, 26): Null can not be a value of a non-null type String
e: [/Users/flowpottevin/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt](): (247, 26): Null can not be a value of a non-null type String
e: [/Users/flowpottevin/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt](): (310, 5): 'onRequestPermissionsResult' overrides nothing

e: [/Users/flowpottevin/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRViewFactory.kt](): (10, 1): Class 'QRViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory


* What went wrong:
Execution failed for task ':qr_code_scanner:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by dugganl1** [comment]
I'm having the same issue - exact same error. Do we have a solution for this? On search - looks like something similar happened in 2019 version: https://github.com/juliuscanute/qr_code_scanner/issues/19...

**Comment by dugganl1** [comment]
@SwiftyFlow have you forked and fixed it that way? Is that the solution you mention above?

**Comment by dugganl1** [comment]
@SwiftyFlow @juliansteenbakker looking at it in more detail - doesn't seem to be the exact same issue as 2019? Do you have any ideas on how to fix this bug? My app won't run with it & wondering if many more are having similar issues

**Comment by juliansteenbakker** [comment]
Sorry for the late response. Can you please provide the output of `flutter doctor -v` together with which device and android version you are using. I'm testing this on an Android 8 tablet and i don't get the errors you are describing.

**Comment by FlorentPottevin** [comment]
I think it did but I altered what was mentioned to alter in the source code (no fork)

**Comment by juliansteenbakker** [comment]
Also, are you using the latest version 0.7.0? I can build an appbundle without any errors.

**Comment by dugganl1** [comment]
Hi Julian - thanks for your response - appreciate the help. I started from scratch and having the same error. 

Yes - **using latest version 0.7.0**. Testing on **Android 12.0 Pixel 4 API 31**

**Below is error message**
e: [C:\Users\dugga\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\qr_code_scanner-0.7.0\android\src\main\kotlin\net\touchcapture\qr\flutterqr\QRView.kt](): (216, 26): Null can not be a value of a non-null type String
e: [C:\Users\dugga\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\qr_code_scanner-0.7.0\android\src\main\kotlin\net\touchcapture\qr\flutterqr\QRView.kt](): (247, 26): Null can not be a value of a non-null type String
e: [C:\Users\dugga\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\qr_code_scanner-0.7.0\android\src\main\kotlin\net\touchcapture\qr\flutterqr\QRView.kt](): (310, 5): 'onRequestPermissionsResult' overrides nothing

e: [C:\Users\dugga\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\qr_code_scanner-0.7.0\android\src\main\kotlin\net\touchcapture\qr\flutterqr\QRViewFactory.kt](): (13, 5): 'create' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':qr_code_scanner:compileDebugKotlin'.

**And flutter doctor output**
[√] Flutter (Channel master, 2.11.0-0.0.pre.858, on Microsoft Windows [Version 10.0.19043.1526], locale en-IE)
    • Flutter version 2.11.0-0.0.pre.858 at C:\Users\dugga\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0dfb656e28 (16 hours ago), 2022-03-10 12:40:23 -0500
    • Engine revision 6b1a24b1a1
    • Dart version 2.17.0 (build 2.17.0-182.0.dev)
    • DevTools version 2.11.1

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\dugga\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.65.2)
    • VS Code at C:\Users\dugga\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1526]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 99.0.4844.51
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 98.0.1108.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by juliansteenbakker** [comment]
@dugganl1 you are using flutter on the master channel, which is very unstable and shouldn't be used for developing. I suggest switching to beta or stable and to try it again.

**Comment by dugganl1** [comment]
Ah - that seems to have done it. Thanks Julian - have moved to stable channel. Flutter rookie mistake!

**Comment by SwiftyFlow** [comment]
Still stuck:

Launching lib[/main.dart]() on sdk gphone64 x86 64 in debug mode...
lib/main.dart:1
e: [/Users/flowpottevin/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt](): (23, 1): Class 'QRView' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
e: [/Users/flowpottevin/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt](): (216, 26): Null can not be a value of a non-null type String
e: [/Users/flowpottevin/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt](): (247, 26): Null can not be a value of a non-null type String
e: [/Users/flowpottevin/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt](): (310, 5): 'onRequestPermissionsResult' overrides nothing

e: [/Users/flowpottevin/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRViewFactory.kt](): (10, 1): Class 'QRViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: [/Users/flowpottevin/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRViewFactory.kt](): (13, 5): 'create' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':qr_code_scanner:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at [https://help.gradle.org]()

BUILD FAILED in 9s
Exception: Gradle task assembleDebug failed with exit code 1
Exited

**Comment by binaris-no** [comment]
Flutter stable is now on ver. 3 and this seems a showstopper...

**Comment by dugganl1** [comment]
Has it stopped working?

**Comment by binaris-no** [comment]
@dugganl1 I've been on stable without any issues, and now with 3.0 I'm seeing these qr_code_scanner build errors for the first time.

**Comment by BenCherif** [comment]
i've upgrade to flutter 3.0.0 and got the error any updates about that?

**Comment by dugganl1** [comment]
Did this get resolved? Afraid to make any updates in case it throws the error

**Comment by BenCherif** [comment]
@dugganl1  They release a new update for this package and it works without any issue .
