### ISSUE TITLE
[BUG] Notify in the README.md that version 0.7.0 only works in Android devices with API 24+

### ISSUE THREAD

**Issue by svprdga** [juliuscanute/qr_code_scanner#508]
The latest version of this plugin implements zxing lib version 3.4.x. This version is only supported for android devices with API 24+. Executing this plugin in lower versions can cause a [crash like this](https://github.com/journeyapps/zxing-android-embedded/issues/508).

I think that the README.md should reflect that requirement.

**Comment by juliansteenbakker** [comment]
Please see https://github.com/journeyapps/zxing-android-embedded#option-2-desugaring-advanced

With desugaring, api 24 < are supported.
