### ISSUE TITLE
Fatal Exception: java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)

### ISSUE THREAD

**Issue by xang555** [juliuscanute/qr_code_scanner#514]
**Describe the bug**
app crash on android 6 and 11(SM-F22 5G)

**Flutter information**
 - **qr_code_scanner version:** qr_code_scanner: ^0.7.0
 - **flutter doctor:**

[✓] Flutter (Channel stable, 2.10.2, on macOS 12.0.1 21A559 darwin-arm, locale en)
    • Flutter version 2.10.2 at /Users/laoitdev/Documents/flutter2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (4 weeks ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/laoitdev/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/laoitdev/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[!] Connected device
    ! No devices available

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Device :**

<img width="423" alt="Screen Shot 2022-03-21 at 01 16 50" src="https://user-images.githubusercontent.com/14501918/159176675-f1784895-249e-44f8-aaf8-97afa41cb9d0.png">

<img width="399" alt="Screen Shot 2022-03-21 at 01 16 56" src="https://user-images.githubusercontent.com/14501918/159176693-34768e32-9549-4ec8-924f-bcb783827412.png">

**Additional context**
Fatal Exception: java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
       at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java)
       at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java)
       at com.google.zxing.qrcode.detector.Detector.detect(Detector.java)
       at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java)
       at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java)
       at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java)
       at com.journeyapps.barcodescanner.Decoder.decode(Decoder.java)
       at com.journeyapps.barcodescanner.Decoder.decode(Decoder.java)
       at com.journeyapps.barcodescanner.DecoderThread.decode(DecoderThread.java)
       at com.journeyapps.barcodescanner.DecoderThread.access$000(DecoderThread.java)
       at com.journeyapps.barcodescanner.DecoderThread$1.handleMessage(DecoderThread.java)
       at android.os.Handler.dispatchMessage(Handler.java:116)
       at android.os.Looper.loop(Looper.java:207)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by neylsongularte** [comment]
https://stackoverflow.com/a/66775562

https://github.com/journeyapps/zxing-android-embedded#older-sdk-versions

**Comment by Dooks123** [comment]
@neylsongularte 
The links you posted suggests adding desugaring to the gradle file.
I currently have `qr_code_scanner: ^0.7.0` and if you look inside the library:

![Untitled](https://user-images.githubusercontent.com/11367243/172997611-6a3f447d-08b0-4789-8bde-85337ace9f9a.png)

Those have already been added.

I do see that the `zxing-android-embedded` link it says you have to enable `hardwareAccelerated`:

> Make sure it is enabled in your manifest file:
> 
>     <application android:hardwareAccelerated="true" ... >

My manifest does not have that in, so I guess this is the next thing to try.

*`android:hardwareAccelerated`* _is used from API level 11 and higher_

**Comment by okanulkr** [comment]
Lines below solved the issue for me. (Desugaring)


```
android {
    ....

    compileOptions {
        ...
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```



--------


```
dependencies {
    ...
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
}
```

**Comment by xang555** [comment]
> 

i add this to `build.gradle` in project level work well

thanks

**Comment by xang555** [comment]
> 



> Lines below solved the issue for me. (Desugaring)
> 
> ```
> android {
>     ....
> 
>     compileOptions {
>         ...
>         coreLibraryDesugaringEnabled true
>         sourceCompatibility JavaVersion.VERSION_1_8
>         targetCompatibility JavaVersion.VERSION_1_8
>     }
> ```
> 
> ```
> dependencies {
>     ...
>     coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
> }
> ```

I add this to `build.gradle` in project level work well

thanks

**Comment by shaheer20** [comment]
> > 
> 
> > Lines below solved the issue for me. (Desugaring)
> > ```
> > android {
> >     ....
> > 
> >     compileOptions {
> >         ...
> >         coreLibraryDesugaringEnabled true
> >         sourceCompatibility JavaVersion.VERSION_1_8
> >         targetCompatibility JavaVersion.VERSION_1_8
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > dependencies {
> >     ...
> >     coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
> > }
> > ```
> 
> I add this to `build.gradle` in project level work well
> 
> thanks

Adding this resolves the issue but my app is crashing when starting on Samsung Tab8+

**Comment by Dooks123** [comment]
@shaheer20  If you have the log, please post it here. If it is in production, please implement firebase crashlytics in your app, then if you still can't figure out why it crashes - post your firebase crash log here.

**Comment by fauzipadlaw** [comment]
Solution above is causing crash when opening app on Samsung Tab A8, 
This is stacktrace from Firebase Crashlytics

```
Fatal Exception: java.lang.NoSuchMethodError: No interface method addWindowLayoutInfoListener(Landroid/app/Activity;Lj$/util/function/Consumer;)V in class Landroidx/window/extensions/layout/WindowLayoutComponent; or its super classes (declaration of 'androidx.window.extensions.layout.WindowLayoutComponent' appears in /system_ext/framework/androidx.window.extensions.jar)
       at androidx.window.layout.ExtensionWindowLayoutInfoBackend.registerLayoutChangeCallback(ExtensionWindowLayoutInfoBackend.kt:68)
       at androidx.window.layout.WindowInfoTrackerImpl$windowLayoutInfo$1.invokeSuspend(WindowInfoTrackerImpl.kt:52)
       at androidx.window.layout.WindowInfoTrackerImpl$windowLayoutInfo$1.invoke(WindowInfoTrackerImpl.kt:2)
       at androidx.window.layout.WindowInfoTrackerImpl$windowLayoutInfo$1.invoke(WindowInfoTrackerImpl.kt:1)
       at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
       at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
       at androidx.window.java.layout.WindowInfoTrackerCallbackAdapter$addListener$1$1.invokeSuspend(WindowInfoTrackerCallbackAdapter.kt:96)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by fauzipadlaw** [comment]
This issue should reopen, because the solution is causing other issue.

**Comment by fauzipadlaw** [comment]
> > > 
> > 
> > 
> > > Lines below solved the issue for me. (Desugaring)
> > > ```
> > > android {
> > >     ....
> > > 
> > >     compileOptions {
> > >         ...
> > >         coreLibraryDesugaringEnabled true
> > >         sourceCompatibility JavaVersion.VERSION_1_8
> > >         targetCompatibility JavaVersion.VERSION_1_8
> > >     }
> > > ```
> > > 
> > > 
> > > ```
> > > dependencies {
> > >     ...
> > >     coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
> > > }
> > > ```
> > 
> > 
> > I add this to `build.gradle` in project level work well
> > thanks
> 
> Adding this resolves the issue but my app is crashing when starting on Samsung Tab8+

I fixed the crash issue with this solution: https://stackoverflow.com/questions/74163927/flutter-chrash-in-android-12l-with-no-interface-method-addwindowlayoutinfoliste/74257036#74257036

**Comment by Dooks123** [comment]
@shaheer20 What Android version does the Tab8+ run?
@fauzipadlaw What Android version does the Tab A8 run?

**Comment by fauzipadlaw** [comment]
> @shaheer20 What Android version does the Tab8+ run? @fauzipadlaw What Android version does the Tab A8 run?

@Dooks123 Android 13

**Comment by Parthakbari15** [comment]
i am adding your mentioned solution still i am getting this issue  and app crashed after showing splash screen

  Built build\app\outputs\flutter-apk\app-debug.apk.
E/AndroidRuntime( 6757): FATAL EXCEPTION: main
E/AndroidRuntime( 6757): Process: com.package.name, PID: 6757
E/AndroidRuntime( 6757): java.lang.NoSuchMethodError: No interface method addWindowLayoutInfoListener(Landroid/app/Activity;Lj$/util/function/Consumer;)V in class Landroidx/window/extensions/layout/WindowLayoutComponent; or its super classes (declaration of 'androidx.window.extensions.layout.WindowLayoutComponent' appears in /system_ext/framework/androidx.window.extensions.jar)
E/AndroidRuntime( 6757): 	at androidx.window.layout.ExtensionWindowLayoutInfoBackend.registerLayoutChangeCallback(ExtensionWindowLayoutInfoBackend.kt:68)
