### ISSUE TITLE
[BUG] Can't run in flutter 3

### ISSUE THREAD

**Issue by WingCH** [juliuscanute/qr_code_scanner#532]
**Describe the bug**
When running on flutter 3, I get the following error

```
e: /Users/wingch/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt: (23, 1): Class 'QRView' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
e: /Users/wingch/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt: (216, 26): Null can not be a value of a non-null type String
e: /Users/wingch/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt: (247, 26): Null can not be a value of a non-null type String
e: /Users/wingch/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt: (310, 5): 'onRequestPermissionsResult' overrides nothing
e: /Users/wingch/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRViewFactory.kt: (10, 1): Class 'QRViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: /Users/wingch/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRViewFactory.kt: (13, 5): 'create' overrides nothing

FAILURE: Build failed with an exception.
```

**Flutter information**
Always provide the output of `flutter doctor -v` as it is needed in order to know on which Flutter versions the bug exists in.
```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale zh-Hant-HK)
    • Flutter version 3.0.0 at /Users/wingch/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (2 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2
```

**Device (please complete the following information):**
```
 • Pixel 6 (mobile) 
 • android-arm64  
 • Android 12 (API 32)
```

**Screenshots**

**Additional context**

**Comment by aaassseee** [comment]
Pull request #512 already cover Flutter 3 breaking changes you can wait for @juliuscanute merge the pull request or directly import the library by
``` yaml
  qr_code_scanner:
    git:
      url: https://github.com/xeinebiu/qr_code_scanner.git
      ref: fix_break_changes_platform
```

**Comment by James-A-White** [comment]
> ```yaml
>   qr_code_scanner:
>     git:
>       url: https://github.com/xeinebiu/qr_code_scanner.git
>       ref: fix_break_changes_platform
> ```

Unfortunately, I've upgraded my pubspec.yaml file as indicated above, cleaned my .pub-cache file, done a >flutter clean and I'm still getting the error.  

I'm on an M1 Mac running VS Code

Any suggestions? Thanks!

**Comment by kimathi-phil** [comment]
`git/qr_code_scanner-0feca6f15042c279ff575c559a3430df917b623d/lib/src/qr_code_scanner.dart:68:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.`

**Comment by onur-akdogan** [comment]
same error keeps happening to me

**Comment by M2dL1fe** [comment]
+1

**Comment by liu731** [comment]
Try this.
```
  flutter_easyloading:
    git:
      url: https://github.com/lazyfatcat/flutter_easyloading.git
      ref: flutter3
```

**Comment by alkosa** [comment]
I have the same issue

**Comment by BenCherif** [comment]
> Pull request #512 already cover Flutter 3 breaking changes you can wait for @juliuscanute to merge the pull request or directly import the library by
> 
> ```yaml
>   qr_code_scanner:
>     git:
>       url: https://github.com/xeinebiu/qr_code_scanner.git
>       ref: fix_break_changes_platform
> ```

thanks for this temp fix , i use your solution but when i try to open qr code view the camera doesn't work ,just showing a black screen .

**Comment by aaassseee** [comment]
> > Pull request #512 already cover Flutter 3 breaking changes you can wait for @juliuscanute to merge the pull request or directly import the library by
> > ```yaml
> >   qr_code_scanner:
> >     git:
> >       url: https://github.com/xeinebiu/qr_code_scanner.git
> >       ref: fix_break_changes_platform
> > ```
> 
> thanks for this temp fix , i use your solution but when i try to open qr code view the camera doesn't work ,just showing a black screen .

It works fine to me. Maybe you can try another branch which is provided by @X-SLAYER https://github.com/juliuscanute/qr_code_scanner/issues/538#issuecomment-1128690758
``` yaml
qr_code_scanner: 
  git:
    url: https://github.com/X-SLAYER/qr_code_scanner.git
    ref: flutter-beta
```

**Comment by Giuliopretis** [comment]
> 

Same issue here, iOS works but android shows black screen and the functionalities are not working

Doctor: 
`[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm (Rosetta), locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.67.1)
[✓] Connected device (5 available)
    ! Error: iPhone 6s is busy: Fetching debug symbols for iPhone 6s. Xcode will continue when iPhone 6s is finished. (code -10)
[✓] HTTP Host Availability`

Test devices:

iPhone 6, iOS 15.4.1
OnePlus 5t, Android 10

**Comment by xmany** [comment]
> 0fe54cbb19d2cba155f5a0f05d1e7f10ebb0590c

This fixed the build error, but the issue I have after using this is that the QR code view will remain dark, will not be able to scan the QR code, and it keeps saying: 

`E/FrameEvents( 6010): updateAcquireFence: Did not find frame.`

**Comment by krButani** [comment]
> > Pull request #512 already cover Flutter 3 breaking changes you can wait for @juliuscanute to merge the pull request or directly import the library by
> > ```yaml
> >   qr_code_scanner:
> >     git:
> >       url: https://github.com/xeinebiu/qr_code_scanner.git
> >       ref: fix_break_changes_platform
> > ```
> 
> thanks for this temp fix , i use your solution but when i try to open qr code view the camera doesn't work ,just showing a black screen .

Try below sloution and resolve it
https://github.com/juliuscanute/qr_code_scanner/issues/538#issuecomment-1133883828

**Comment by juliansteenbakker** [comment]
Sorry for the delay, version 1.0.0 with these fixes is released.

**Comment by KoneruGeetha** [comment]
> Pull request #512 already cover Flutter 3 breaking changes you can wait for @juliuscanute to merge the pull request or directly import the library by
> 
> ```yaml
>   qr_code_scanner:
>     git:
>       url: https://github.com/xeinebiu/qr_code_scanner.git
>       ref: fix_break_changes_platform
> ```

where to import in which file?

**Comment by aaassseee** [comment]
> > Pull request #512 already cover Flutter 3 breaking changes you can wait for @juliuscanute to merge the pull request or directly import the library by
> > ```yaml
> >   qr_code_scanner:
> >     git:
> >       url: https://github.com/xeinebiu/qr_code_scanner.git
> >       ref: fix_break_changes_platform
> > ```
> 
> where to import in which file?

@KoneruGeetha The updated version 1.0.0 already released. You should try update it through pub.

**Comment by KoneruGeetha** [comment]
> > > Pull request #512 already cover Flutter 3 breaking changes you can wait for @juliuscanute to merge the pull request or directly import the library by
> > > ```yaml
> > >   qr_code_scanner:
> > >     git:
> > >       url: https://github.com/xeinebiu/qr_code_scanner.git
> > >       ref: fix_break_changes_platform
> > > ```
> > 
> > 
> > where to import in which file?
> 
> @KoneruGeetha The updated version 1.0.0 already released. You should try update it through pub.

can you help me mentioning the exact command?

**Comment by BenCherif** [comment]
@KoneruGeetha  just add new release : 
`qr_code_scanner: ^1.0.0`
