### ISSUE TITLE
Execution failed for task ':qr_code_scanner:compileDebugKotlin'.[BUG] 

### ISSUE THREAD

**Issue by Mohammadwabeel** [juliuscanute/qr_code_scanner#535]
This happened after installing latest flutter version 3.0.0

**Comment by iamsethsamuel** [comment]
I am experiencing the same issue

**Comment by esaiamuthan** [comment]
yes myself also facing the same issue 

Help me on this please its very urgent for me to update the code ASAP

**Comment by Justin-roy** [comment]
Same Issue With Flutter 3.0.0

**Comment by Mohammadwabeel** [comment]
Now I have to removed "qr_code_scanner: ^0.7.0" and use"mobile_scanner: ^1.1.0" 😒

**Comment by Justin-roy** [comment]
> Now I have to remove "qr_code_scanner: ^0.7.0" and use"mobile_scanner: ^1.1.0" 😒

And Then U Get Same Error !!

**Comment by ch405** [comment]
I have the same issue.

**Comment by AndrewDavydenko** [comment]
Also have this issue.

**Comment by IgorTurcan** [comment]
Me too

**Comment by Justin-roy** [comment]
> Now I have to remove "qr_code_scanner: ^0.7.0" and use"mobile_scanner: ^1.1.0" 😒

Yes Me Too Moved to mobile_scanner plugin

**Comment by X-SLAYER** [comment]
this PR [PR#533](https://github.com/juliuscanute/qr_code_scanner/pull/533) fix the problem we are just waiting for the merge until it gets merged you can use it like that 

```yaml
qr_code_scanner: 
  git:
    url: https://github.com/X-SLAYER/qr_code_scanner.git
    ref: flutter-beta
```

**Comment by creactive-indo** [comment]
> > Now I have to remove "qr_code_scanner: ^0.7.0" and use"mobile_scanner: ^1.1.0" 😒
> 
> Yes Me Too Moved to mobile_scanner plugin

I've checked & use mobile_scanner plugin now, it's much simpler to setup, rich feature & supportability. I like it. Thank you.

**Comment by MostafaElswefy** [comment]
> > > Now I have to remove "qr_code_scanner: ^0.7.0" and use"mobile_scanner: ^1.1.0" 😒
> > 
> > 
> > Yes Me Too Moved to mobile_scanner plugin
> 
> I've checked & use mobile_scanner plugin now, it's much simpler to setup, rich feature & supportability. I like it. Thank you.

Yes Me Too Moved to mobile_scanner plugin

**Comment by juliansteenbakker** [comment]
Please try again with version 1.0.0
