### ISSUE TITLE
Class 'QRView' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener

### ISSUE THREAD

**Issue by krButani** [juliuscanute/qr_code_scanner#538]
Error Come in new Flutter version 3.0.0

e: G:\AAAInstallation\src\flutter\.pub-cache\hosted\pub.dartlang.org\qr_code_scanner-0.7.0\android\src\main\kotlin\net\touchcapture\qr\flutterqr\QRView.kt: (23, 1): Class 'QRView' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
e: G:\AAAInstallation\src\flutter\.pub-cache\hosted\pub.dartlang.org\qr_code_scanner-0.7.0\android\src\main\kotlin\net\touchcapture\qr\flutterqr\QRView.kt: (216, 26): Null can not be a value of a non-null type String
e: G:\AAAInstallation\src\flutter\.pub-cache\hosted\pub.dartlang.org\qr_code_scanner-0.7.0\android\src\main\kotlin\net\touchcapture\qr\flutterqr\QRView.kt: (247, 26): Null can not be a value of a non-null type String
e: G:\AAAInstallation\src\flutter\.pub-cache\hosted\pub.dartlang.org\qr_code_scanner-0.7.0\android\src\main\kotlin\net\touchcapture\qr\flutterqr\QRView.kt: (310, 5): 'onRequestPermissionsResult' overrides nothing
e: G:\AAAInstallation\src\flutter\.pub-cache\hosted\pub.dartlang.org\qr_code_scanner-0.7.0\android\src\main\kotlin\net\touchcapture\qr\flutterqr\QRViewFactory.kt: (10, 1): Class 'QRViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: G:\AAAInstallation\src\flutter\.pub-cache\hosted\pub.dartlang.org\qr_code_scanner-0.7.0\android\src\main\kotlin\net\touchcapture\qr\flutterqr\QRViewFactory.kt: (13, 5): 'create' overrides nothing

**Comment by hubdestro** [comment]
same issue.

**Comment by iulian0512** [comment]
+1

**Comment by X-SLAYER** [comment]
this PR [PR#533](https://github.com/juliuscanute/qr_code_scanner/pull/533) fix the problem we are just waiting for the merge until it get merged you can use it like that 

```yaml
qr_code_scanner: 
  git:
    url: https://github.com/X-SLAYER/qr_code_scanner.git
    ref: flutter-beta
```

**Comment by EngKB** [comment]
+1

**Comment by hanzinhee** [comment]
+1

**Comment by filofan1** [comment]
> > this PR [PR#533](https://github.com/juliuscanute/qr_code_scanner/pull/533) fix the problem we are just waiting for the merge until it get merged you can use it like that
> > ```yaml
> > qr_code_scanner: 
> >   git:
> >     url: https://github.com/X-SLAYER/qr_code_scanner.git
> >     ref: flutter-beta
> > ```
> 
> On Android, the camera screen is not visible and comes out black. What about others? iPhone works fine.

Same here

**Comment by jingjiewei** [comment]
> Title

+1

**Comment by jingjiewei** [comment]
> > > this PR [PR#533](https://github.com/juliuscanute/qr_code_scanner/pull/533) fix the problem we are just waiting for the merge until it get merged you can use it like that
> > > ```yaml
> > > qr_code_scanner: 
> > >   git:
> > >     url: https://github.com/X-SLAYER/qr_code_scanner.git
> > >     ref: flutter-beta
> > > ```
> > 
> > 
> > On Android, the camera screen is not visible and comes out black. What about others? iPhone works fine.
> 
> Same here

+1

**Comment by krButani** [comment]
> > > this PR [PR#533](https://github.com/juliuscanute/qr_code_scanner/pull/533) fix the problem we are just waiting for the merge until it get merged you can use it like that
> > > ```yaml
> > > qr_code_scanner: 
> > >   git:
> > >     url: https://github.com/X-SLAYER/qr_code_scanner.git
> > >     ref: flutter-beta
> > > ```
> > 
> > 
> > On Android, the camera screen is not visible and comes out black. What about others? iPhone works fine.
> 
> Same here

this issue is coming because by the default camera is open on pause mode you need to change some code below

QRView(
            key: qrKey,
            onQRViewCreated: _onQRViewCreated,
            overlay: QrScannerOverlayShape(
                borderColor: whiteColor!,
                borderRadius: 10,
                borderLength: 30,
                borderWidth: 10,
                cutOutSize: k.getWSize(80)),
            onPermissionSet: (ctrl, p) => _onPermissionSet(context, ctrl, p),
          ))

void _onQRViewCreated(QRViewController controller) {
    setState(() {
      this.controller = controller;
      resuecamara();
    });
    controller.scannedDataStream.listen((scanData) {
    
        setState(() {
          result = scanData;
          print(result!.code);
        });
    });
  }

void resuecamara() {
    if (Platform.isAndroid) {
      controller!.pauseCamera();
    }
    controller!.resumeCamera();
  }

**Comment by filofan1** [comment]
Thanks @krButani 
Your tips worked.
In my case i just added controller.resume(); for Android only, onQrViewCreated
I didn't add this line.
`android.enableDexingArtifactTransform=false`, should I ?

**Comment by krButani** [comment]
Yes plugin need

**Comment by vicdotdevelop** [comment]
+ 1 Thanks @X-SLAYER

**Comment by draganjovanovic1** [comment]
I tried switching to github reference but no luck. Any idea?

```yaml
  # qr_code_scanner: ^0.4.0
  qr_code_scanner:
    git:
      url: https://github.com/X-SLAYER/qr_code_scanner
      ref: flutter-beta
```

```bash
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/dragan/Library/flutter/.pub-cache/git/qr_code_scanner-5c8a34b848e4e1bad6b4c987d89634b90fd3ab9e/android/build.gradle' line: 27

* What went wrong:
A problem occurred evaluating project ':qr_code_scanner'.
> No signature of method: build_d05f0gp7fe0zub84vsx4095zp.android() is applicable for argument types: (build_d05f0gp7fe0zub84vsx4095zp$_run_closure2) values: [build_d05f0gp7fe0zub84vsx4095zp$_run_closure2@59a4d957]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 689ms
```

**Comment by allyssonmast** [comment]
> I tried switching to github reference but no luck. Any idea?
> 
> ```yaml
>   # qr_code_scanner: ^0.4.0
>   qr_code_scanner:
>     git:
>       url: https://github.com/X-SLAYER/qr_code_scanner
>       ref: flutter-beta
> ```
> 
>  ```shell
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/Users/dragan/Library/flutter/.pub-cache/git/qr_code_scanner-5c8a34b848e4e1bad6b4c987d89634b90fd3ab9e/android/build.gradle' line: 27
> 
> * What went wrong:
> A problem occurred evaluating project ':qr_code_scanner'.
> > No signature of method: build_d05f0gp7fe0zub84vsx4095zp.android() is applicable for argument types: (build_d05f0gp7fe0zub84vsx4095zp$_run_closure2) values: [build_d05f0gp7fe0zub84vsx4095zp$_run_closure2@59a4d957]
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 689ms
> ```

The url is wrong… change to “ https://github.com/X-SLAYER/qr_code_scanner.git“

**Comment by draganjovanovic1** [comment]
AFAIK It's the same thing. Both works

**Comment by iulian0512** [comment]
> Disregard, migrated to `mobile_scanner` and works great. The build issue I posted was with Android build, iOS worked well.

mobile_scanner does not work ok on ios 15+ physical device, see the issue list on the repo for details.

**Comment by draganjovanovic1** [comment]
> > Disregard, migrated to `mobile_scanner` and works great. The build issue I posted was with Android build, iOS worked well.
> 
> mobile_scanner does not work ok on ios 15+ physical device, see the issue list on the repo for details.

 ☹️

**Comment by draganjovanovic1** [comment]
Managed to make Android build work. The problem was in very old version of Gradle I was using.

**Comment by xshiwei** [comment]
+1

**Comment by juliansteenbakker** [comment]
Version 1.0.0 with these fixes is released.
