### ISSUE TITLE
[BUG] Warning after flutter 3 version update

### ISSUE THREAD

**Issue by BAEK-UNYEONG** [juliuscanute/qr_code_scanner#539]
**Describe the bug**

`../../Documents/libraries/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_hooks-0.18.3/lib/src/widgets_binding_observer.dart:42:29: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Documents/libraries/flutter/packages/flutter/lib/src/widgets/binding.dart').
    _state = WidgetsBinding.instance!.lifecycleState;
                            ^
../../Documents/libraries/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_hooks-0.18.3/lib/src/widgets_binding_observer.dart:43:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Documents/libraries/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
../../Documents/libraries/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_hooks-0.18.3/lib/src/widgets_binding_observer.dart:52:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Documents/libraries/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);
                   ^
../../Documents/libraries/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/lib/src/qr_code_scanner.dart:68:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Documents/libraries/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(_observer);
                   ^
../../Documents/libraries/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/lib/src/qr_code_scanner.dart:86:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Documents/libraries/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(_observer);`

**Flutter information**
Always provide the output of `flutter doctor -v` as it is needed in order to know on which Flutter versions the bug exists in.

flutter version is 3.

**Device (please complete the following information):**

ios 13 pro

**Screenshots**

**Additional context**

**Comment by AbdulbasitSaid** [comment]
I am also facing the same issue when I upgraded flutter to version 3.0. Please help us upgrade the package.

**Comment by rudian** [comment]
> I am also facing the same issue when I upgraded flutter to version 3.0. Please help us upgrade the package.

pls add this to your pubspec.yaml first while this repo haven't approve the PR

`
dependency_overrides:
    qr_code_scanner:
        git:
            url: https://github.com/X-SLAYER/qr_code_scanner.git
            ref: flutter-beta
`

**Comment by rudian** [comment]
```
dependency_overrides:
    qr_code_scanner:
        git:
            url: https://github.com/X-SLAYER/qr_code_scanner.git
            ref: flutter-beta
```

**Comment by BAEK-UNYEONG** [comment]
Thanks you!!

> ```
> dependency_overrides:
>     qr_code_scanner:
>         git:
>             url: https://github.com/X-SLAYER/qr_code_scanner.git
>             ref: flutter-beta
> ```

**Comment by 8138976373** [comment]
Once create qr Controller, bar code readed and then stop. While creating crController Second time, I needed to call resumeCamera function for getting barcode reader camera.

**Comment by JavohirYakubov** [comment]
> ```
> dependency_overrides:
>     qr_code_scanner:
>         git:
>             url: https://github.com/X-SLAYER/qr_code_scanner.git
>             ref: flutter-beta
> ```

it's work for me! Thanks!

**Comment by juliansteenbakker** [comment]
Version 1.0.0 with these fixes is released.
