### ISSUE TITLE
[ASK] Why use minSdkVersion 21?

### ISSUE THREAD

**Issue by fajarainul** [juliuscanute/qr_code_scanner#54]
Your plugin is very helpful, we can use it with custom view. But, why you decide to use Android API 21 for minimum SDK version? Why not using API 16 as minimum SDK version since it's recommended minimum SDK version from Android Studio? Thanks

**Comment by Xuhao** [comment]
Same question here :(

**Comment by bartektartanus** [comment]
And if this package requires SDK 21 it would be nice to mention that in README or in installation instructions.

**Comment by dspicher** [comment]
I just bumped jetified-zxing-android-embedded to 4.0.2 to fix an `ArithmeticException`. Unfortunately, this now requires minSdk 24. I will add a mention to the README.

**Comment by ragu-swaminathan** [comment]
> I just bumped jetified-zxing-android-embedded to 4.0.2 to fix an `ArithmeticException`. Unfortunately, this now requires minSdk 24. I will add a mention to the README.

Is there any way, that we can use the support of min SDK 21?  Currently my app set minimum SDK version as 21. And using your library fails during the compile time because of manifest merge.

Any help appreciated.

**Comment by dspicher** [comment]
Please discuss the minSdk issue at #90.
