### ISSUE TITLE
Camera black screen after reopening

### ISSUE THREAD

**Issue by Aboneyx** [juliuscanute/qr_code_scanner#548]
The camera works only once after the apk dish. The camera shows a black screen after reopening. This has happened since version 1.0.0. And I can't downgrade the package version, since the flutter is 3.0.0.

**Flutter information**
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.4 21F79 darwin-arm, locale ru-KZ)
    • Flutter version 3.0.0 at /Users/rayyvon/FlutterDev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (3 weeks ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/rayyvon/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • EVA AL10 (mobile) • KWG5T16906028969 • android-arm64  • Android 8.0.0 (API 26)
    • macOS (desktop)   • macos            • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by juliansteenbakker** [comment]
On which device are you experiencing this?

**Comment by theamorn** [comment]
I have the problem as well here's my flutter doctor

[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale en-TH)
    • Flutter version 3.0.1 at /Users/amorn/development/flutter_arm64
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (11 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/amorn/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • M2103K19G (mobile) • obsg7horzxfe4du8 • android-arm64  • Android 12 (API 31)
    • macOS (desktop)    • macos            • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

my device is a Redmi note 10 5G. it's a black screen at first but the screen will show up after I use photo in gallery, the camera will pop up normally
I revert to 0.7.0 is working fine

Another thing is can you change androidminSDK to 31 instead of 32? so it's followed with Flutter that requires 31.
32 is too new. Thanks

**Comment by christianfl** [comment]
This should help:

https://github.com/juliuscanute/qr_code_scanner/issues/538#issuecomment-1133883828

**Comment by theamorn** [comment]
> This should help. had the same issue:
> 
> [#538 (comment)](https://github.com/juliuscanute/qr_code_scanner/issues/538#issuecomment-1133883828)

confirm that this link is solved my problem, I just add one line of code

`controller.resumeCamera(); 
`
that's all

**Comment by Aboneyx** [comment]
> > This should help. had the same issue:
> > [#538 (comment)](https://github.com/juliuscanute/qr_code_scanner/issues/538#issuecomment-1133883828)
> 
> confirm that this link is solved my problem, I just add one line of code
> 
> `controller.resumeCamera(); ` that's all

Oh, it really helped, but still, if there is time, it is desirable to change the package to a [mobile_scanner](https://pub.dev/packages/mobile_scanner)
