### ISSUE TITLE
Reduce stream speed?

### ISSUE THREAD

**Issue by ferdiamg** [juliuscanute/qr_code_scanner#55]
Currently I am scanning for QR codes and whenever something is found, I open an alert to show the information of the QR code, however the scannedDataStream provides information so fast that it opens like 20 alert dialogs within a second. 

**How can I reduce the stream speed? (or amount of scans that are being done)**
```
  void _onQRViewCreated(QRViewController controller) {
    this.controller = controller;
    controller.scannedDataStream.listen((scanData) {
      setState(() {
        qrText = scanData;
      });
      displayDialog(scanData);
    });
  }
```

Thanks in advance!

**Comment by luis901101** [comment]
You should use controller?.pauseCamera(); before display the dialog in order to avoid further scans... then when the user dismisses the dialog you can controller?.resumeCamera();

**Comment by jjjachyty** [comment]
> You should use controller?.pauseCamera(); before display the dialog in order to avoid further scans... then when the user dismisses the dialog you can controller?.resumeCamera();

If I keep looking at the QR code, I always receive data, even if I pause scanning
@luis901101

**Comment by luis901101** [comment]
@jjjachyty check you are using the latest version of this lib... the las time I checked the controller.pause() the camera just freezes so no scans were made ergo no data was received... I mainly tried this lib for iOS... anyway you can check the native code to check if data is sent while pause

**Comment by fmiyahira** [comment]
Hey @jjjachyty, i solved it by doing control with a state variable.
 
![image](https://user-images.githubusercontent.com/675320/83099772-38f21700-a07c-11ea-88e9-e9febc4a78f4.png)

**Comment by juliansteenbakker** [comment]
Since the stream will receive data as long as a QR code is present, it wil run the code. This issue is tracked in #11 and hence will close this as a duplicate.
