### ISSUE TITLE
Qr code scanner in flutter 3.0.0 can not build apk in release mode 

### ISSUE THREAD

**Issue by ayechan-maung** [juliuscanute/qr_code_scanner#558]
**Describe the bug**

**Flutter information**
 flutter doctor -v
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.0.1 21A559 darwin-x64, locale en)
    • Flutter version 3.0.0 at /Users/ayechan/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (5 weeks ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/ayechan/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-11.0.12.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 67.1.3
    • Dart plugin version 213.7371

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • HTC U11 (mobile) • FA7AR1800711 • android-arm64  • Android 9 (API 28)
    • Chrome (web)     • chrome       • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Device (please complete the following information):**
 - Device: HTC U11
 - OS: Android

**Additional context**

<img width="1394" alt="Screen Shot 2022-06-13 at 15 15 57" src="https://user-images.githubusercontent.com/49619379/173315599-23f985f0-0cd2-42dc-b636-296fd60e8ee8.png">

**Comment by hnord-vdx** [comment]
It works for me. Accept android licenses and try with `flutter clean && flutter pub get && flutter build appbundle`

**Comment by ayechan-maung** [comment]
> It works for me. Accept android licenses and try with `flutter clean && flutter pub get && flutter build appbundle`

I accepted the android licenses and tried what you said but still got that issue.

**Comment by secretmoo35** [comment]
Same issue on iOS & Android.

**Comment by Ahmed-Mechrir** [comment]
same problem
