### ISSUE TITLE
Change return [ASK]

### ISSUE THREAD

**Issue by jp4bidube** [juliuscanute/qr_code_scanner#57]
hello im having some trouble  handling the data back from the QR reader

im trying to read a binary QR 2D em transform de data to a base64 string to be compared to an existing base 64;

here below is the code im using:

 void _onQRViewCreated(QRViewController controller) {
    this.controller = controller;
    controller.scannedDataStream.listen((scanData) {

      var bytes = utf8.encode(scanData);
      print(base64.encode(bytes));

      setState(() {
        qrText = scanData;
      });
    });
  }

this is the output:
Xe+/vXENBQARAEUwQwIgXUdMOe+/vQbvv73vv73vv70LSTvvv71E77+9KE/vv73IsO+/vV/vv73vv70J77+9b++/vSTvv71P77+9Ah8eya9l77+9R++/ve+/ve+/vU3vv73vv73vv71Y77+9SGTvv71jUTnvv73vv70b77+9C1kr77+977+9KgAAAAxF77+9UEEUEGVEVlFF77+9

this is what it should be : 
XaRxDQUAEQBFMEMCIF1HTDnDBpuxtwtJO/1E4ShPxMiw5l+HkgmZb7skqk+KAh8eya9lrEe3sYhNwczoWLRIZJBjUTmd3hvcC1kr+YUqAAAADEWUUEEUEGVEVlFFwA==

the conversion is wrong and i dont think its my code, but i think it is becaude the type of return of the variable, i need the raw data from de reading..

is there a way to do it on this lib ??

in native android a use the zxing lib and get it from the mMap of the data...but i dont see a way to do it here

here is the QR im trying to read.
![WhatsApp Image 2019-11-05 at 15 45 19](https://user-images.githubusercontent.com/52284888/68330763-8f810f00-00b2-11ea-8bca-21a9ffba0f90.jpeg)

**Comment by laruche** [comment]
Do you find a solution ? 
I've a similar issue ? 

Your qr contain the good vlaue (test with scandit app) 
I've use hex conversion to base64

**Comment by bbrazsilveira** [comment]
@jp4bidube @laruche 
Did you find any solution?

**Comment by pinpong** [comment]
Hi, you need to get the rawbytes:

Android: 

> channel.invokeMethod("onRecognizeQR", result.getRawBytes())

IOS: 

> guard let rawValue = code.rawValue else { continue }

I'll provide a PR soon.

**Comment by juliansteenbakker** [comment]
I've managed to fix this for android by adding rawBytes to barcode object. However, i wasn't able to fix this for iOS. If you have any solution please feel free to comment.
