### ISSUE TITLE
[BUG] Crash app when scanned on android 6.0

### ISSUE THREAD

**Issue by zhgwu** [juliuscanute/qr_code_scanner#587]
**Describe the bug**
Crash app when scanned on android 6.0.

**Flutter information**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 11.6 20G165 darwin-x64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Community Edition (version 2021.3.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Device (please complete the following information):**
 - Device: Pixel 5 emulator
 - OS: Android 6.0

**Screenshots**
![Screen Shot 2022-09-07 at 10 07 30](https://user-images.githubusercontent.com/48649647/188780448-cacafad8-a310-4292-9214-315063e3b255.png)

**Comment by devguusta** [comment]
I have the same error, but I don't use android 6.0

**Comment by PhRezende-eng** [comment]
Same here

**Comment by mateusdevelopes** [comment]
Same here :/

**Comment by xang555** [comment]
solved #514
