### ISSUE TITLE
[ASK] QR Overlay design question

### ISSUE THREAD

**Issue by ferdiamg** [juliuscanute/qr_code_scanner#59]
I need your help guys, I've now tried several different QR scanners for Flutter and none of them provide easy to customize overlays/heights, widths, etc.

I've realised the following app in React Native and have to rebuild it **_exactly_** like this in Flutter aswell:
![Screen](https://user-images.githubusercontent.com/19799412/68372926-0fa28580-0142-11ea-923a-888dad395d85.png)

Now my question: Is it possible to realise the same with this qr_code_scanner by @juliuscanute ? Everytime I try to put the scanner into a Stack widget it tells me theres an issue regarding flex and that the scanner can't have a parent widget that constrains its flex properties. But I need the Stack to be able to overlay the animated scanning line and the rounded corners.. Also I can't get it to add padding to the left and right sides because again, flex properties misbehaving..

Is this even possible?

**Comment by ferdiamg** [comment]
@juliuscanute Your thoughts maybe? Still struggling :(

**Comment by novas1r1** [comment]
@ferdiamg did you find a solution for it? Because I will need it also. Having a react app which has a custom qr-scanner layout with half the screen the scanner and the other half some custom layout with buttons texts and so on. Would love to hear from you!

**Comment by ferdiamg** [comment]
@novas1r1 and for everybody else coming across this post: I've got a perfectly working solution, but I had to fork this repository and restructure it "completly". @juliuscanute uses a ShapeBorder for this plugins overlay, but what I needed was a widget with animations that I could pass in as a variable to the QR scanner. Check the forked repo for further information (also: I am not going to maintain this or file a PR (at this moment) since that is probably not a current use case of the scanner).

Best of luck!

**Comment by yogithesymbian** [comment]
just using **animatedWidget** with stack on qrcode, animationScannerWidget
reference : https://api.flutter.dev/flutter/widgets/AnimatedWidget-class.html

fullcode i have implemented and works like your screenshot.
https://gist.github.com/webianks/e0655fb723cd16d433a397933f8771a2
