### ISSUE TITLE
[ASK] Is there a way to handle Android permissions?

### ISSUE THREAD

**Issue by lyio** [juliuscanute/qr_code_scanner#60]
I noticed that the `QRView` is handling the Android permission flow itself/internally and is prompting the user with the Android dialog asking for permission to access the device's camera.

Is there a way that I can get the result of this dialog? If the user rejects the permission, I can see an Android stacktrace in the console but have no way of catching the exception.

**Comment by luis901101** [comment]
Currently this is not implemented. In fact this should be done for iOS too because in case the user rejects the permission there is no way to get the permission activated unless the user activates it manually from iOS settings.

**Comment by pedromassango** [comment]
Any update on this?

**Comment by cyrilOrderoo** [comment]
Hi, it will be very usefull to implement a such featured, for now it's a bad experience when user doesn't accept the permission.
Thank you.

**Comment by luis901101** [comment]
I recommend you to use this plugin to manage permissions by your own in the mean time:

https://pub.dev/packages/permission

**Comment by juliansteenbakker** [comment]
This is not possible right now because the permission is handled inside the ZXING framework we are using. Since this framework is in a maintaince only status i'm considering switching from framework, which eventually would allow a permission to be handled. You can track the progress of this in #176.

**Comment by juliansteenbakker** [comment]
As it turns out the permission IS being handled inside this plugin so i am reopening this issue.
