### ISSUE TITLE
Cannot scan after release APK

### ISSUE THREAD

**Issue by taufiqjack** [juliuscanute/qr_code_scanner#609]
why can't scan QRcode scanner after release APK?

**Comment by nezero** [comment]
Same issue, App crashes when using the Qr Scanner in a release build

**Comment by jbrechbuehl** [comment]
Same issue here, app crashes instantly in release build (android 12, qr_code_scanner: 1.0.1)

**Comment by maxammann** [comment]
@juliuscanute can we pin this issue? I guess that way people see more prominent that they should stwitch to mobile_scanner

**Comment by aJIEw** [comment]
I had the same problem, solved by removing the `Expanded`. See #448 and [this comment](https://github.com/juliuscanute/qr_code_scanner/issues/448#issuecomment-980049010)

**Comment by aymench15** [comment]
> I had the same problem, solved by removing the `Expanded`. See #448 and [this comment](https://github.com/juliuscanute/qr_code_scanner/issues/448#issuecomment-980049010)

solved the same way
