### ISSUE TITLE
D8: Program type already present: com.google.zxing.BarcodeFormat

### ISSUE THREAD

**Issue by JiaweiUTSCHINA** [juliuscanute/qr_code_scanner#61]
D8: Program type already present: com.google.zxing.ChecksumException

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
...
...
...
Program type already present: com.google.zxing.ChecksumException

**Comment by dspicher** [comment]
Please try to run `flutter clean` and `flutter packages get`.

If you keep running into this issue, please post a full example that reproduces the problem.
