### ISSUE TITLE
Render QRView In Dialog

### ISSUE THREAD

**Issue by deshario** [juliuscanute/qr_code_scanner#66]
I tried to render QrView inside Dialog ... but it seems like its not rendering in the center of layout .. So i wanna know how to do it. Thanks 

![Screen Shot 2563-01-16 at 15 03 46](https://user-images.githubusercontent.com/11426727/72504989-88743b00-3871-11ea-8454-b7ca92567d9e.png)

![qrcode](https://user-images.githubusercontent.com/11426727/72504863-464af980-3871-11ea-9bad-6fddf15dabe5.jpg)

**Comment by deshario** [comment]
@juliuscanute  OverlayShape is not centering

**Comment by aqwert** [comment]
Looked into this. I believe the code in the OverlayShape inside the paint method. needs to be:

```
  final cutOutRect = Rect.fromLTWH(
      (width / 2 - _cutOutSize / 2 + borderOffset) + rect.left,
      (height / 2 - _cutOutSize / 2 + borderOffset) + rect.top,
      _cutOutSize - borderOffset * 2,
      _cutOutSize - borderOffset * 2,
    );
```

The parent rectangle offsets (left and top) need to be added to the cut out rect.

**Comment by aqwert** [comment]
Also solved here: https://github.com/juliuscanute/qr_code_scanner/issues/40#issuecomment-587271192

**Comment by deshario** [comment]
https://gist.github.com/deshario/7e5968d033c6872b4ddd8d31303d46b8
