### ISSUE TITLE
Example not working with the latest version

### ISSUE THREAD

**Issue by mdalboni** [juliuscanute/qr_code_scanner#67]
I tried a lot running the example from 0.0.12 but it isn't updated.
Some params now are private and others are gone.

**Comment by yunzhouhua** [comment]
I have the same problem!

**Comment by dspicher** [comment]
Can you check again on current master?

**Comment by dspicher** [comment]
Hi @mdalboni.
Both the `example/main.dart` and the one from the `README.md` should run fine on current master. Can you confirm?

**Comment by juliansteenbakker** [comment]
I have tested the example app on iOS 12 and Android 10 and it seems to be working just fine with 0.0.14.
