### ISSUE TITLE
Widget turns black, when keyboard expanded, even though it still scans

### ISSUE THREAD

**Issue by YannickSpoerl** [juliuscanute/qr_code_scanner#68]
When the keyboard on Android is expanded and the view moves, the QRView turns black.
It still successfully captures QR-codes, the camera is just black.

**Comment by edukun** [comment]
Same here, but also it occurs randomly when app starts. After splash screen, first screen is only a Scaffold with AppBar, QRView and a FloatingActionButton, and sometimes camera is just black, but it can scan codes.

**Comment by edukun** [comment]
Also a black screen happens when:
1) Pause camera
2) Pushing a new page and pressing back button
3) Resume camera
Sometimes gets a black screen. Changing orientation makes camera good again

**Comment by OliverNarramore** [comment]
Also facing this issue, are there any updates or work arounds?

**Comment by PingAK9** [comment]
same here

**Comment by djackowski** [comment]
I'm also facing that problem

**Comment by djackowski** [comment]
I found a workaround by removing in AndroidManifest line:
 `android:windowSoftInputMode="adjustResize"` but after that Keyboard overlays TextField, so I decided to use animation to move it up and it works for now. I took animation idea from here:
https://stackoverflow.com/a/50736768/10995898

**Comment by vickymogha** [comment]
Same here, When the keyboard on Android is expanded. QRView became black and still capturing the QR code. can anyone suggest me any solution to solve it.

**Comment by Nirvana-cn** [comment]
You can try "resizeToAvoidBottomPadding".
```
Scaffold(
      resizeToAvoidBottomPadding: false,
       // ...
    )
```

**Comment by VikashMogha** [comment]
> You can try "resizeToAvoidBottomInset".
> 
> ```
> Scaffold(
>     resizeToAvoidBottomInset: false,
>      // ...
> )
> ```

I have tried it but nothing happened perfect. still screen getting black on keyboard expended

**Comment by WingCH** [comment]
> resizeToAvoidBottomInset

成功

**Comment by jjjachyty** [comment]
> Also a black screen happens when:
> 
> 1. Pause camera
> 2. Pushing a new page and pressing back button
> 3. Resume camera
>    Sometimes gets a black screen. Changing orientation makes camera good again

I have this problem. How can I solve it！！The camera limit height setting does not take effect on the first startup

**Comment by i8wu** [comment]
If you have a state change you can tie to the event you might be able to rebuild the QRView.

**Comment by sameertkw** [comment]
I think you face this problem when you use QRView inside Scaffold. You need to put QRView outside Scaffold.
I have used Stack and put Scaffold above the QRView and It's working fine.

**Comment by juliansteenbakker** [comment]
I've looked into this and found a workaround since it cant be fixed natively due to the QRView being an native view.

By wrapping a column with both the QRView and the textfield in a `SingleChildScrollView` and letting that column listen to the width and height of the application we can scroll down to the textfield or scroll up to the QRView. ([source](https://stackoverflow.com/questions/46551268/when-the-keyboard-appears-the-flutter-widgets-resize-how-to-prevent-this))

```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomPadding: true,
      body: SingleChildScrollView(
        child: ConstrainedBox(
          constraints: BoxConstraints(
            minWidth: MediaQuery.of(context).size.width,
            minHeight: MediaQuery.of(context).size.height,
          ),
          child: IntrinsicHeight(
            child: Column(
              children: <Widget>[
                Expanded(flex: 4, child: _buildQrView(context)),
                Expanded(
                  flex: 1,
                  child: TextField(
                    decoration: InputDecoration(
                        border: InputBorder.none,
                        hintText: 'Enter a search term'
                    ),
                  )
                )
              ],
            ),
          ),
        ),
      ),
    );
```

**Comment by adhityabagasmiwa** [comment]
> I've looked into this and found a workaround since it cant be fixed natively due to the QRView being an native view.
> 
> By wrapping a column with both the QRView and the textfield in a `SingleChildScrollView` and letting that column listen to the width and height of the application we can scroll down to the textfield or scroll up to the QRView. ([source](https://stackoverflow.com/questions/46551268/when-the-keyboard-appears-the-flutter-widgets-resize-how-to-prevent-this))
> 
> ```
> @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       resizeToAvoidBottomPadding: true,
>       body: SingleChildScrollView(
>         child: ConstrainedBox(
>           constraints: BoxConstraints(
>             minWidth: MediaQuery.of(context).size.width,
>             minHeight: MediaQuery.of(context).size.height,
>           ),
>           child: IntrinsicHeight(
>             child: Column(
>               children: <Widget>[
>                 Expanded(flex: 4, child: _buildQrView(context)),
>                 Expanded(
>                   flex: 1,
>                   child: TextField(
>                     decoration: InputDecoration(
>                         border: InputBorder.none,
>                         hintText: 'Enter a search term'
>                     ),
>                   )
>                 )
>               ],
>             ),
>           ),
>         ),
>       ),
>     );
> ```

This worked for me, thanks a lot!
