### ISSUE TITLE
No suitable application records were found | org.cocoapods.qr-code-scanner

### ISSUE THREAD

**Issue by gmaxferr** [juliuscanute/qr_code_scanner#70]
I've tried to upload an app that depends on the **qr_code_scanner** plugin, but an error occured during upload: 

> No suitable application records were found. Verify your bundle identifier 'org.cocoapods.qr-code-scanner' is correct.

How do I solve this?

**Comment by ShengjieGeng** [comment]
![image](https://user-images.githubusercontent.com/18364968/87745365-44fa8980-c820-11ea-8339-45a8c6b6edac.png)
I got the same question.
please do me a favor

**Comment by juliansteenbakker** [comment]
Can you please test this with the latest v0.1.0? Please comment if this issue stil persists.

**Comment by ShengjieGeng** [comment]
> ![image](https://user-images.githubusercontent.com/18364968/87745365-44fa8980-c820-11ea-8339-45a8c6b6edac.png)
> I got the same question.
> please do me a favor

I'm using the `qr_code_scanner: 0.0.12`,which works fine.

**Comment by juliansteenbakker** [comment]
I have released version 0.2.0. If the issue persists on that version please let me know.
