### ISSUE TITLE
Dependency ':qr_code_scanner' requires core library desugaring to be enabled for :app.

### ISSUE THREAD

**Issue by UtkuDalmaz** [juliuscanute/qr_code_scanner#723]
I am having this after upgrading gradle

1.  Dependency ':qr_code_scanner' requires core library desugaring to be enabled
           for :app.

           See https://developer.android.com/studio/write/java8-support.html for more
           details.

Any idea how to fix it?

**Comment by miguelangelflores1993** [comment]
same error

**Comment by zakblacki** [comment]
Same error at least tell us how you fixed ?! @UtkuDalmaz

**Comment by UtkuDalmaz** [comment]
> Same error at least tell us how you fixed ?! @UtkuDalmaz

Added this to android place in build.gradle 

```
compileOptions {
        coreLibraryDesugaringEnabled true
    }
```

and this to dependency in build.gradle

   ` coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.4'`
