### ISSUE TITLE
Prevent orientation change

### ISSUE THREAD

**Issue by ReveredMachine** [juliuscanute/qr_code_scanner#73]
Is there already a possibility to pass through the properies for preventing an orientation change to the underlying library when scanning a barcode ?

**Comment by rgb1380** [comment]
You can limit orientation changes for your app such as this:

``` dart
Widget build(BuildContext context) {
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
    ]);

    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
```

**Comment by ReveredMachine** [comment]
@rgb1380 The app itself should be allowed to change their orientation.
The problem with the orientation change is, that it is hard to scan barcodes that are vertically aligned on an item whose orientation cannot be changed.

**Comment by juliansteenbakker** [comment]
Shouldn't this be handled by the device rather than limiting this in the plugin? Otherwise we would force all applications that use this library to be in portrait mode which isn't desirable.
