### ISSUE TITLE
when pauseCamera and  use event_bus resumeCamera the camera was stuck on ios

### ISSUE THREAD

**Issue by jjjachyty** [juliuscanute/qr_code_scanner#77]
``` controller.scannedDataStream.listen((scanData) {
      print("二维码结果=========${scanData}");
      controller?.pauseCamera();
      if (this._tabIndex == 0) {
        eventBus.fire(ScanPatient(scanData));
      } else {
        eventBus.fire(ScanPrescription(scanData));
      }
    }, onDone: () {
      print("onDone");
    }, onError: (onError) {
      print("onerror=======${onError}");
    }, cancelOnError: true);
  }```

```
    eventBus.on().listen((event) {
      print("sacn event======${event.runtimeType.toString()}");
      switch (event.runtimeType.toString()) {
        case "ScanController":
          print("event.state=${event.state}");
          if (event.state == 1) {
            print(this.controller.toString());
            // this.controller.toggleFlash();
            controller?.resumeCamera();  // **camera was stuck**
          }
          break;
        case "PatientSelected":
          if (mounted) {
            setState(() {
              selectPatient = event.patient;
            });
          }
          break;
        default:
      }
    });
```

**Comment by WingCH** [comment]
same problem, any news?

**Comment by mehdico** [comment]
is this solved?

**Comment by juliansteenbakker** [comment]
Please test with latest version 0.1.0 and post a comment if this issue still persists.
