### ISSUE TITLE
Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by Sofianel5** [juliuscanute/qr_code_scanner#82]
Unexpectedly found nil while unwrapping an Optional value: file /Users/sofiane/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.0.12/ios/Classes/QRView.swift, line 29

Super easy fix for you, just check if its nil. The error occured when I swiped up to my apps view on an iPhone X.

**Comment by Nomy1** [comment]
I encountered this problem just a few moments ago. I'll fix it locally as well, but i hope its fixed in the next version

**Comment by dspicher** [comment]
This should be fixed with #72.

**Comment by srikanth-burra** [comment]
I am getting this same error in any version I am using and I am not able to figure out where to check for nil.
