### ISSUE TITLE
Camera preview is black after widget resize by any reason

### ISSUE THREAD

**Issue by MigoTiti** [juliuscanute/qr_code_scanner#87]
If somehow the qr widget resizes after first build, the camera turns full black. How can i solve this?

**Comment by AndryHTC** [comment]
Same problem here... For some reasons also rotating the screen even with fixed size

**Comment by micaelsn** [comment]
SAME PROBLEM TOO... and it's not reading long barcodes

**Comment by RenanDelfanti** [comment]
I have the same problem

**Comment by juliansteenbakker** [comment]
Please check with master branch.
