### ISSUE TITLE
why minSdkVersion changed to 24?

### ISSUE THREAD

**Issue by teknolojia** [juliuscanute/qr_code_scanner#90]
19 would be better
[Look at](https://github.com/zxing/zxing/blob/master/android/AndroidManifest.xml#L34)

**Comment by dspicher** [comment]
We are using zxing-android-embedded, see here for the minSDK reference.
https://github.com/journeyapps/zxing-android-embedded#zxing-android-embedded
Unfortunately I don't have the resources at the moment to test the downgrade described there.  I may come back to it in the future.

**Comment by dkobia** [comment]
24 is pretty high. That basically requires a minimum of Android 7.0.

**Comment by softmarshmallow** [comment]
+1 for this. this is critical. 21 made sense. 24? no way..

**Comment by JFreakDK** [comment]
@dspicher would you be willing to accept a pull request that makes it support a minSdk of 21?

**Comment by dspicher** [comment]
@JFreakDK of course. See the link above for what needs to be done.

**Comment by ragu-swaminathan** [comment]
@dspicher , I understand there is a issue with the Zxing as you mentioned in latest release 0.0.13. But most of the use cases will fall using the minSDK as 21. 

So it will be fine if we have a two versions of library like one that supports 21 and other with 24 if possible.

**Comment by dspicher** [comment]
@ragu-swaminathan I suggest you pin the package to release 0.0.12 then.

**Comment by JmyW** [comment]
I surprised that required minSDK so high at 24. As the history of Android devices, the v6.0 (API 23) was sold a lot and long time.  And understood the tablet was v5.x(API 21) in that same time. So, looks like API-21 is better supportable in most of app. Appreciate if the enhancement can be made.
