### ISSUE TITLE
version 0.0.13 is not reading barcodes corretly

### ISSUE THREAD

**Issue by micaelsn** [juliuscanute/qr_code_scanner#94]
can someone help me?
I love this plugin :/

**Comment by dspicher** [comment]
You will need to provide more info for anybody to be able to help you. A minimal code example would be best. Do you get errors?
Also, please paste your output of `flutter doctor -v`.

**Comment by micaelsn** [comment]
it's already working, but I would like if I could encrease the height of reading area bc it's in square format.. For long barcodes it's hard to fit in the area... That's why I can't read correctly!!

**Comment by juliansteenbakker** [comment]
This may be addressed in a future release, however will close it for now since the primary issue is solved. Please create a seperate issue if it is important.
