### ISSUE TITLE
Not reading properly untill focus is clear.

### ISSUE THREAD

**Issue by Ajaydev4342** [juliuscanute/qr_code_scanner#96]
There is a issues while scanning code the user is need to be scan the code continuously until the clear focus on QR or barcode. maybe the camera auto focus not working. thats why it takes some time to scan if you can resolve this issues that will be great. thanks

**Comment by supratikkoley** [comment]
yes, It happens with me too. Please add focus in he camera.

**Comment by kazume** [comment]
Same here :) focus would be great

**Comment by juliansteenbakker** [comment]
The application uses autofocus so if the code doesn't get in focus, it probably is an issue with the device you are using rather than the application. I'll look into the possibility for manual focus but it's not the biggest priority right now.

**Comment by kazume** [comment]
I just checked and it uses autofocus on the back but not the front camera. I assume the fron camera on my device (Pixel 2XL) is unable to do so.

**Comment by juliansteenbakker** [comment]
Since the framework is setup to use autofocus there is not really anything else we can do. Some devices are bad at focussing, but we can't really improve that with the current frameworks, hence closing this issue for now.
