### ISSUE TITLE
Xcode warnings

### ISSUE THREAD

**Issue by enricobenedos** [juliuscanute/qr_code_scanner#99]
Good morning,

I am aware that warnings some times are not a problem but I think it can be a good idea to solve them. Unfortunately I'm not a iOS native developer, hope that anyone can fix them.

Thank you

![image](https://user-images.githubusercontent.com/12233746/84940667-74628d00-b0e0-11ea-982e-a81ce7736028.png)

**Comment by enricobenedos** [comment]
I think this PR #142 will solve it

**Comment by juliansteenbakker** [comment]
Merged with #142. Will be released in 0.1.0.
